### PR TITLE
Fix pickle and repr for `Duration`.

### LINKED ISSUE #14169: Test `test.python.compiler.test_transpiler.TestTranspile.test_delay_converts_expr_to_dt` fails in Qiskit 2.0
### Environment

- **Qiskit version**:  2.0
- **Python version**: 3.13.2
- **Operating system**: Arch Linux

### What is happening?

I maintain the [qiskit](https://aur.archlinux.org/packages/python-qiskit) packages in AUR for Arch Linux users. After updating to the recent new release 2.0, the test `test.python.compiler.test_transpiler.TestTranspile.test_delay_converts_expr_to_dt` failed with the following error message:

```
==============================
Failed 1 tests - output below:
==============================

test.python.compiler.test_transpiler.TestTranspile.test_delay_converts_expr_to_dt
---------------------------------------------------------------------------------

Captured traceback:
~~~~~~~~~~~~~~~~~~~
    concurrent.futures.process._RemoteTraceback: 
"""
Traceback (most recent call last):
  File "/usr/lib/python3.13/multiprocessing/queues.py", line 262, in _feed
    obj = _ForkingPickler.dumps(obj)
  File "/usr/lib/python3.13/multiprocessing/reduction.py", line 51, in dumps
    cls(buf, protocol).dump(obj)
    ~~~~~~~~~~~~~~~~~~~~~~~^^^^^
TypeError: cannot pickle 'qiskit._accelerate.circuit.Duration_us' object
"""

    
The above exception was the direct cause of the following exception:


    Traceback (most recent call last):

      File "/build/python-qiskit/src/qiskit-2.0.0/test/python/compiler/test_transpiler.py", line 1407, in test_delay_converts_expr_to_dt
    out = transpile([qc, qc], backend, seed_transpiler=42)

      File "/build/python-qiskit/src/test_dir/usr/lib/python3.13/site-packages/qiskit/compiler/transpiler.py", line 291, in transpile
    out_circuits = pm.run(circuits, callback=callback, num_processes=num_processes)

      File "/build/python-qiskit/src/test_dir/usr/lib/python3.13/site-packages/qiskit/transpiler/passmanager.py", line 451, in run
    return super().run(circuits, output_name, callback, num_processes=num_processes)
           ~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

      File "/build/python-qiskit/src/test_dir/usr/lib/python3.13/site-packages/qiskit/transpiler/passmanager.py", line 474, in wrapper
    return meth(*meth_args, **meth_kwargs)

      File "/build/python-qiskit/src/test_dir/usr/lib/python3.13/site-packages/qiskit/transpiler/passmanager.py", line 233, in run
    return super().run(
           ~~~~~~~~~~~^
        in_programs=circuits,
        ^^^^^^^^^^^^^^^^^^^^^
    ...<3 lines>...
        property_set=property_set,
        ^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^

      File "/build/python-qiskit/src/test_dir/usr/lib/python3.13/site-packages/qiskit/passmanager/passmanager.py", line 258, in run
    return parallel_map(
        _run_workflow_in_new_process,
    ...<5 lines>...
        num_processes=num_processes,
    )

      File "/build/python-qiskit/src/test_dir/usr/lib/python3.13/site-packages/qiskit/utils/parallel.py", line 316, in parallel_map
    return list(executor.map(_task_wrapper, work_items))

      File "/usr/lib/python3.13/concurrent/futures/process.py", line 617, in _chain_from_iterable_of_lists
    for element in iterable:
                   ^^^^^^^^

      File "/usr/lib/python3.13/concurrent/futures/_base.py", line 619, in result_iterator
    yield _result_or_cancel(fs.pop())
          ~~~~~~~~~~~~~~~~~^^^^^^^^^^

      File "/usr/lib/python3.13/concurrent/futures/_base.py", line 317, in _result_or_cancel
    return fut.result(timeout)
           ~~~~~~~~~~^^^^^^^^^

      File "/usr/lib/python3.13/concurrent/futures/_base.py", line 456, in result
    return self.__get_result()
           ~~~~~~~~~~~~~~~~~^^

      File "/usr/lib/python3.13/concurrent/futures/_base.py", line 401, in __get_result
    raise self._exception

      File "/usr/lib/python3.13/multiprocessing/queues.py", line 262, in _feed
    obj = _ForkingPickler.dumps(obj)

      File "/usr/lib/python3.13/multiprocessing/reduction.py", line 51, in dumps
    cls(buf, protocol).dump(obj)
    ~~~~~~~~~~~~~~~~~~~~~~~^^^^^

    TypeError: cannot pickle 'qiskit._accelerate.circuit.Duration_us' object

```

I'm running the python tests as close as possible to the GitHub Actions pipeline. In particular, I run:

```bash
stestr run -d test/python -E "test_equivalence_draw"
```

These are run in a clean chroot env with just qiskit and its dependencies installed. All tests were passing with Qiskit 1.4.2.

### How can we reproduce the issue?

If you want to replicate the issue in an identical env, you can try to build the package in a docker/podman container using [Arch Linux image](https://gitlab.archlinux.org/archlinux/archlinux-docker).

### What should happen?

All tests should pass

### Any suggestions?

_No response_

### PR DESCRIPTION
**Pull request by kevinhartman**
### Summary
Adds missing Python pickle support for the new `Duration` type added in Qiskit 2.0.

### Details and comments
To get this working, I needed to manually register the PyO3 generated `Duration_xx` Python classes at the module level, since `pickle` looks for them during deserialization. I'm not sure if there's a better way, but I'm open to suggestions if you can think of something cleaner. Pickle doesn't have explicit support in PyO3, so we're lucky to have any working solution here.

While fixing this, I also noticed that `__repr__` was defined inside an `impl` block that wasn't decorated with `#[pymethods]`, meaning it wasn't actually being used before. That's fixed here too.

Fixes #14169

### CODE REVIEW

File: crates/circuit/src/lib.rs [hunk 1]
```diff
@@ -169,7 +170,31 @@ pub fn circuit(m: &Bound<PyModule>) -> PyResult<()> {
...
+    )?;
+    m.add(
+        "Duration_s",
+        duration::Duration::type_object(m.py()).getattr("s")?,
+    )?;
+    m.add(
+        "Duration_dt",
+        duration::Duration::type_object(m.py()).getattr("dt")?,
+    )?;
+
```
Comment (raynelfss) [inline crates/circuit/src/lib.rs:197]: I'm a bit surprised that this step is needed. But I guess it makes some sense considering that `pickle` will try to access the class objects based on their import paths.

**Review by raynelfss — APPROVED** [review]
Makes sense to me, I'm just a bit surprised that we'd have to explicitly export each variant.

File: crates/circuit/src/lib.rs (hunk 1 above)
Comment (kevinhartman) [reply crates/circuit/src/lib.rs:197]: Yeah, I was too, though I think it makes sense that PyO3 doesn't expose these by default. Users should not be constructing `Duration_xx`s directly, so I don't think the names have a good case for being exposed by the containing module, other than for serialization (which PyO3 doesn't explicitly support).
