### PR TITLE
Fix OpenQASM 2 `gate` definitions following a shadowed built-in `gate`

### LINKED ISSUE #13339: `from_qasm_str` not importing `Fswap` correctly
### Environment

- **Qiskit version**: 1.2.4
- **Python version**: 3.12.2
- **Operating system**: Linux

### What is happening?

When one creates a circuit with `qiskit.QuantumCircuit.from_qasm_str` an Fswap gate will sometimes be mapped to swap. This seems to only happen if there is a swap before the fswap in the qasm file.

```
swap q[0],q[1];
fswap q[0],q[1];
fswap q[0],q[1];
```

gives

```
CircuitInstruction(operation=Instruction(name='swap', num_qubits=2, num_clbits=0, params=[]), qubits=(Qubit(QuantumRegister(2, 'q'), 0), Qubit(QuantumRegister(2, 'q'), 1)), clbits=())
CircuitInstruction(operation=Instruction(name='swap', num_qubits=2, num_clbits=0, params=[]), qubits=(Qubit(QuantumRegister(2, 'q'), 0), Qubit(QuantumRegister(2, 'q'), 1)), clbits=())
CircuitInstruction(operation=Instruction(name='swap', num_qubits=2, num_clbits=0, params=[]), qubits=(Qubit(QuantumRegister(2, 'q'), 0), Qubit(QuantumRegister(2, 'q'), 1)), clbits=())
```

But 

```
fswap q[0],q[1];
swap q[0],q[1];
fswap q[0],q[1];
```

gives

```
CircuitInstruction(operation=Instruction(name='fswap', num_qubits=2, num_clbits=0, params=[]), qubits=(Qubit(QuantumRegister(2, 'q'), 0), Qubit(QuantumRegister(2, 'q'), 1)), clbits=())
CircuitInstruction(operation=Instruction(name='swap', num_qubits=2, num_clbits=0, params=[]), qubits=(Qubit(QuantumRegister(2, 'q'), 0), Qubit(QuantumRegister(2, 'q'), 1)), clbits=())
CircuitInstruction(operation=Instruction(name='fswap', num_qubits=2, num_clbits=0, params=[]), qubits=(Qubit(QuantumRegister(2, 'q'), 0), Qubit(QuantumRegister(2, 'q'), 1)), clbits=())
```

### How can we reproduce the issue?

Run this code:
```py
from qiskit import QuantumCircuit

qasm_str = """OPENQASM 2.0;

gate u3(theta,phi,lambda) q { U(theta,phi,lambda) q; }
gate u2(phi,lambda) q { U(pi/2,phi,lambda) q; }
gate u1(lambda) q { U(0,0,lambda) q; }
gate rx(theta) a { u3(theta,-pi/2,pi/2) a; }
gate ry(theta) a { u3(theta,0,0) a; }
gate rz(phi) a { u1(phi) a; }
gate cx c,t { CX c,t; }

gate swap a,b { cx a,b; cx b,a; cx a,b; }
gate fswap a,b { rz(-pi/2) a; rz(-pi/2) b; rx(pi/2) a; cx a,b; rx(-pi/2) a; ry(-pi/2) b; cx a,b; rx(-pi/2) a; }

qreg q[2];

swap q[0],q[1];
fswap q[0],q[1];
fswap q[0],q[1];"""

qiskit_circuit = QuantumCircuit.from_qasm_str(qasm_str)
for gate in qiskit_circuit:
    print(gate)
qiskit_circuit.draw()
```

It outputs

```
CircuitInstruction(operation=Instruction(name='swap', num_qubits=2, num_clbits=0, params=[]), qubits=(Qubit(QuantumRegister(2, 'q'), 0), Qubit(QuantumRegister(2, 'q'), 1)), clbits=())
CircuitInstruction(operation=Instruction(name='swap', num_qubits=2, num_clbits=0, params=[]), qubits=(Qubit(QuantumRegister(2, 'q'), 0), Qubit(QuantumRegister(2, 'q'), 1)), clbits=())
CircuitInstruction(operation=Instruction(name='swap', num_qubits=2, num_clbits=0, params=[]), qubits=(Qubit(QuantumRegister(2, 'q'), 0), Qubit(QuantumRegister(2, 'q'), 1)), clbits=())

        ┌───────┐┌───────┐
q_0: ─X─┤0      ├┤0      ├
      │ │  Swap ││  Swap │
q_1: ─X─┤1      ├┤1      ├
        └───────┘└───────┘
```

### What should happen?

I should output

```
CircuitInstruction(operation=Instruction(name='swap', num_qubits=2, num_clbits=0, params=[]), qubits=(Qubit(QuantumRegister(2, 'q'), 0), Qubit(QuantumRegister(2, 'q'), 1)), clbits=())
CircuitInstruction(operation=Instruction(name='fswap', num_qubits=2, num_clbits=0, params=[]), qubits=(Qubit(QuantumRegister(2, 'q'), 0), Qubit(QuantumRegister(2, 'q'), 1)), clbits=())
CircuitInstruction(operation=Instruction(name='fswap', num_qubits=2, num_clbits=0, params=[]), qubits=(Qubit(QuantumRegister(2, 'q'), 0), Qubit(QuantumRegister(2, 'q'), 1)), clbits=())

        ┌────────┐┌────────┐
q_0: ─X─┤0       ├┤0       ├
      │ │  Fswap ││  Fswap │
q_1: ─X─┤1       ├┤1       ├
        └────────┘└────────┘
```

### Any suggestions?

_No response_

### PR DESCRIPTION
**Pull request by jakelishman**
### Summary

Previously, when given an OpenQASM 2 program such as

    OPENQASM 2.0;
    gate builtin a { U(0, 0, 0) a; }
    gate not_builtin a { U(pi, pi, pi) a; }
    qreg q[1];

    not_builtin q[0];

and a set of `custom_instructions` including a `builtin=True` definition for `builtin` (but not for `not_builtin`), the Rust and Python sides would get themselves out-of-sync and output a gate that matched a prior definition, rather than `not_builtin`.

This was because the Rust side was still issuing `DefineGate` bytecode instructions, even for gates whose OpenQASM 2 definitions should have been ignored, so Python-space thought there were more gates than Rust-space thought there were.

### Details and comments

Fix #13339.

### CODE REVIEW

File: crates/qasm2/src/parse.rs [hunk 1]
```diff
@@ -1685,12 +1696,14 @@ impl State {
             }
             match self.symbols.get(&name) {
                 None => {
+                    // The gate wasn't a built-in, so we need to move the symbol in, but we don't
+                    // need to increment the number of gates because it's already got a gate ID
+                    // assigned.
                     self.symbols.insert(name, symbol.into());
-                    self.num_gates += 1;
-                    Ok(true)
+                    Ok(false)
```
Comment (ElePT) [inline crates/qasm2/src/parse.rs:1703]: This is probably me missing something, because it looks like the tests pass, but if the gate isn't a built-in, shouldn't the function return `Ok(True)` because it needs a definition?

Comment (jakelishman) [reply crates/qasm2/src/parse.rs:1703]: It's just off the top of the diff, but this is in an `if` block for a gate that's already in the "overrideable gates" symbol table, which requires the user to have given a constructor function to the Python-space entry point in `custom_instructions`.  So it's already got a gate index allocated, and Python space knows how to construct it.

A "built in" here is meaning "pretend that the gate was always defined in OpenQASM 2", whereas "not a built in" means "use this function to construct the gate, but only allow it if you see a `gate` statement with its name (but ignore the body of that statement)".  We're in the second case here - we don't need to return the body of the gate statement to Python space, because we're ignoring it; we just want to assign the gate index of the overrideable gate to the now properly defined symbol.

Comment (ElePT) [reply crates/qasm2/src/parse.rs:1703]: Thanks! That makes sense, and is what I suspected, but wanted to make sure I was understanding it right.

**Review by ElePT — APPROVED** [review]
LGTM for what I can see!
