### PR TITLE
Fix classical bit mapping in HLS pass

### LINKED ISSUE #14569: Results of sampling circuit with custom unitary don't match between qiskit 1.4 and qiskit 2
### Environment

- **Qiskit version**: 1.4.3 (2.0.2)
- **Python version**: 3.11
- **Operating system**: Linux

### What is happening?

When sampling - using Aer 0.17.1 - from a circuit with some custom unitaries, I'm seeing _markedly_ different counts being returned.

* With Qiskit 1.4.3
```
Counts: {'011011': 38, '101100': 149, '001111': 123, '101010': 55, '111111': 48, '000011': 401, '000111': 135, '100100': 149, '100101': 37, '001101': 131, '110101': 47, '000010': 378, '110111': 46, '010100': 161, '010111': 47, '001100': 417, '001000': 388, '111101': 57, '101101': 42, '010000': 413, '100000': 417, '100110': 34, '101110': 48, '111001': 51, '001010': 166, '111100': 123, '110000': 411, '110001': 151, '011101': 46, '011010': 43, '000001': 470, '100001': 136, '010101': 41, '000000': 1230, '011110': 35, '100111': 48, '000100': 439, '111011': 57, '011000': 131, '001011': 160, '011100': 144, '110010': 151, '011001': 48, '101000': 127, '110110': 39, '100011': 131, '110100': 134, '111110': 65, '000110': 140, '010001': 136, '100010': 122, '111000': 145, '010011': 147, '011111': 59, '010010': 132, '001001': 140, '001110': 149, '101011': 49, '101111': 44, '101001': 42, '111010': 41, '010110': 34, '000101': 148, '110011': 134}
```
* With Qiskit 2.0.2
```
Counts: {'000011': 1700, '000010': 1630, '000000': 5015, '000001': 1655}
```

Tagging @fpietra and @matteoacrossi who've been investigating this issue on our side. I've also opened https://github.com/Qiskit/qiskit-aer/issues/2347, as I don't know whether the problem lies with Qiskit, Aer, or the interaction of the two.

### How can we reproduce the issue?

The reproducer circuit and script are in this [repo](https://github.com/Algorithmiq/tmp-qiskit2-issue) Building the two Dockerfiles will provide two images with the dependencies to run the comparison for the two different qiskit versions.

### What should happen?

I'd expect the behavior from qiskit 1.4.3 to be preserved with the new major release series. I'm not sure whether this is a problem with Qiskit Aer though.

### Any suggestions?

_No response_

### PR DESCRIPTION
**Pull request by ElePT**
### Summary
This PR fixes a bug in HLS where classical registers were mapped to the indices in within the high level object they were defined on, instead of the corresponding index in the global circuit. 

Fixes #14569 . 

### Details and comments
The bug was introduced in 2.0, so the fix should be backported to the `stable/2.0` branch, but not `stable/1.4`.

### CODE REVIEW

File: crates/transpiler/src/passes/high_level_synthesis.rs [hunk 1]
```diff
@@ -479,6 +479,11 @@ fn run_on_circuitdata(
             .iter()
             .map(|q| input_qubits[q.index()])
             .collect::<Vec<usize>>();
+        let op_clbits = input_circuit
+            .get_cargs(inst.clbits)
+            .iter()
+            .map(|c| c.index())
+            .collect::<Vec<usize>>();
```
Comment (mtreinish) [inline crates/transpiler/src/passes/high_level_synthesis.rs]: This is already a `Clbit` why do you need to convert it to a usize and then back to a `Clbit` below. Couldn't you just do
```suggestion
            .get_cargs(inst.clbits)
            .to_vec();
```

and then change the `map()` below to `op_clbits[c.0 as usize]`.

Comment (mtreinish) [reply crates/transpiler/src/passes/high_level_synthesis.rs]: I just implemented this in: https://github.com/Qiskit/qiskit/pull/14597/commits/000253d633703708ff60edf625385f028d41e2f3 when I looked at the code again I also realized you don't need to store this in a vec at all since the slice will do. Looking at the qubits path the same optimization can mostly be applied too but since this is a fix for backport I didn't make that change here.

**Review by mtreinish — APPROVED** [review]

**Comment by mtreinish** [comment]
@mergifyio backport stable/2.0
