### PR TITLE
Discard cache for standard gates in `assign_parameters`

### LINKED ISSUE #13504: Basis translation can fail if run in parallel
### Environment

- **Qiskit version**: Qiskit 1.3.0 and `main`
- **Python version**: 3.11.9
- **Operating system**: macOS

### What is happening?

This is the problem underlying https://github.com/Qiskit/qiskit-addon-cutting/issues/714.

Running basis translation in parallel (see snippet below) causes the following failure 
```
[...]
  File "/Users/jul/Qiskit/qiskit/qiskit/transpiler/passes/basis/basis_translator.py", line 129, in run
    return base_run(
           ^^^^^^^^^
ValueError: An invalid parameter was provided. 

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/jul/IBM/snippets/repro.py", line 25, in <module>
    pm.run([qc_a, qc_b]) # This fails with the error
    ^^^^^^^^^^^^^^^^^^^^
[...]

  File "/opt/homebrew/Cellar/python@3.11/3.11.9/Frameworks/Python.framework/Versions/3.11/lib/python3.11/concurrent/futures/_base.py", line 401, in __get_result
    raise self._exception
ValueError: An invalid parameter was provided.
```

This seems to be due to the recent port of the basis translator to Rust (see https://github.com/Qiskit/qiskit/issues/12246 for an overview). Dissecting the code, the error seems to be triggered by `compose_transforms`, so it might be worth checking if this already existed after https://github.com/Qiskit/qiskit/pull/13137 and before the rest of the basis translator was moved to Rust.

### How can we reproduce the issue?

From @mtreinish:
> I just came up with a minimal reproduce:
>
> ```
> from qiskit.circuit import QuantumCircuit, Parameter
> from qiskit import generate_preset_pass_manager
> from qiskit.providers.fake_provider import GenericBackendV2
> from qiskit.circuit.library import RXGate
> 
> backend = GenericBackendV2(5)
> pm = generate_preset_pass_manager(1, backend)
>
> param = Parameter('a')
> gate = RXGate(param)
>
> qc_a = QuantumCircuit(1)
> qc_a.append(gate, [0])
> qc_b = QuantumCircuit(1)
> qc_b.append(gate, [0])
>
> pm.run(qc_a)
> pm.run(qc_b)
> pm.run([qc_a, qc_b]) # This fails with the error
> ```

**Note** that this only happens with multiprocessing turned on. On Mac this is turned off per default but can be enabled with `export QISKIT_PARALLEL=TRUE`.

### What should happen?

The above should run, as it did in 1.2.4.

### Any suggestions?

One possible solution is to delete the cached `py_op` upon parameter assignment, i.e. replace https://github.com/Qiskit/qiskit/blob/6979d918e2250d972b497b09ef7cdd13bbda8829/crates/circuit/src/circuit_data.rs#L1385-L1389 by
```rust
previous.py_op = OnceLock::new();  // or OnceCell on Qiskit 1.3.0
```

But this comes at a ~5% performance overhead on my machine, benchmarked on some utility scale circuits. Maybe there's another way to avoid this overhead?

### PR DESCRIPTION
**Pull request by raynelfss**
### Summary
This is an initial fix to #13504, and should precede #13543.

The following commits discard the cached gate when assigning parameters for a standard gate rather than trying to modify the Python object.

### Details and comments

A more in-depth fix is present in #13543, but since it is such a big change, we've decided to include this smaller fix to allow more time to re-evaluate our approach.

When retrieving a `PackedInstruction` from the `EquivalenceLibrary` during the `compose_transforms` phase of the `BasisTranslator` the parameter modifications done in other places are not reflected on the cached gate, therefore leading to issues when running `QISKIT_PARALLEL=TRUE` due to a modified object reference when calling `CircuitData::assign_parameters()`. 

In the case of a standard gate, we were not removing the old cache but instead modifying it in place (which would not result in the expected outcome), while for other gate instances, we rebuild the non-cached item. Now we instead discard the cache in the `StandardGate` case too, getting rid of the stale shared reference.

### CODE REVIEW

File: crates/circuit/src/circuit_data.rs [hunk 1]
```diff
@@ -1394,13 +1394,7 @@ impl CircuitData {
                                 // Standard gates can all rebuild their definitions, so if the
                                 // cached py_op exists, update the `params` attribute and clear out
                                 // any existing cache.
```
Comment (kevinhartman) [inline crates/circuit/src/circuit_data.rs]: Should we update this comment and perhaps add a GitHub link to the relevant issue?

**Review by kevinhartman — COMMENTED** [review]
Thanks @raynelfss, this seems to work nicely.

I left just one comment and will merge once addressed.

File: crates/circuit/src/circuit_data.rs (hunk 1 above)
Comment (raynelfss) [reply crates/circuit/src/circuit_data.rs]: Sure!

File: releasenotes/notes/fix-assign-parameters-ffa284ebde429704.yaml [hunk 2]
```diff
@@ -0,0 +1,7 @@
+---
+fixes:
+  - |
+    Fix incorrect behavior in :class:`.CircuitData` in which, upon parameter assignment,
+    we attempted to modify the cached operation inside of a ``PackedInstruction``. Now
+    we instead discard said cache prompting the ``PackedInstruction`` to build a new Python
+    operation should it be needed.
```
Comment (Cryoris) [inline releasenotes/notes/fix-assign-parameters-ffa284ebde429704.yaml:7]: It would be nice to link the issue here, but let's do that in #13556.

**Review by Cryoris — APPROVED** [review]
LGTM, this is how the original fix looked like 🙂 It seems that Kevin's comments is also addressed and I double checked that this fixed the original bug reported in #13504.
