### PR TITLE
Avoid panics in `Optimize1qGatesDecomposition`

### LINKED ISSUE #15116: `optimize_1q_gates_decomposition` raises `PanicException` when an input circuit contains more qubits than supported by a backend
### Environment

- **Qiskit version**: 2.2.1
- **Python version**: 3.13.6
- **Operating system**: macOS 15.7

### What is happening?

`optimize_1q_gates_decomposition` raises `PanicException` when the input circuit contains more qubits than supported by the target backend.

### How can we reproduce the issue?

```python
from qiskit import QuantumCircuit, __version__, generate_preset_pass_manager
from qiskit_aer import AerSimulator

print(f"qiskit_version={__version__}")
backend = AerSimulator()
print(backend.num_qubits)
num_qubits = backend.num_qubits + 1
qc = QuantumCircuit(num_qubits)
qc.h(range(num_qubits))
pm = generate_preset_pass_manager(optimization_level=1, backend=backend)
t_qc = pm.run(qc)
```

```python
qiskit_version=2.2.1
30

thread '<unnamed>' panicked at crates/transpiler/src/passes/optimize_1q_gates_decomposition.rs:79:81:
called `Result::unwrap()` on an `Err` value: QargsWithoutInstruction("[PhysicalQubit(30)]")
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
Traceback (most recent call last):
  File "/Users/ima/tasks/5_2025/scripts/2025/terra/opt-err.py", line 11, in <module>
    t_qc = pm.run(qc)
  File "/Users/ima/envs/qiskit/lib/python3.13/site-packages/qiskit/transpiler/passmanager.py", line 415, in run
    return super().run(circuits, output_name, callback, num_processes=num_processes)
           ~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ima/envs/qiskit/lib/python3.13/site-packages/qiskit/transpiler/passmanager.py", line 438, in wrapper
    return meth(*meth_args, **meth_kwargs)
  File "/Users/ima/envs/qiskit/lib/python3.13/site-packages/qiskit/transpiler/passmanager.py", line 197, in run
    return super().run(
           ~~~~~~~~~~~^
        in_programs=circuits,
        ^^^^^^^^^^^^^^^^^^^^^
    ...<3 lines>...
        property_set=property_set,
        ^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "/Users/ima/envs/qiskit/lib/python3.13/site-packages/qiskit/passmanager/passmanager.py", line 238, in run
    _run_workflow(
    ~~~~~~~~~~~~~^
        program=program,
        ^^^^^^^^^^^^^^^^
    ...<3 lines>...
        **kwargs,
        ^^^^^^^^^
    )
    ^
  File "/Users/ima/envs/qiskit/lib/python3.13/site-packages/qiskit/passmanager/passmanager.py", line 311, in _run_workflow
    passmanager_ir, final_state = flow_controller.execute(
                                  ~~~~~~~~~~~~~~~~~~~~~~~^
        passmanager_ir=passmanager_ir,
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    ...<3 lines>...
        callback=kwargs.get("callback", None),
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "/Users/ima/envs/qiskit/lib/python3.13/site-packages/qiskit/passmanager/base_tasks.py", line 218, in execute
    passmanager_ir, state = next_task.execute(
                            ~~~~~~~~~~~~~~~~~^
        passmanager_ir=passmanager_ir,
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        state=state,
        ^^^^^^^^^^^^
        callback=callback,
        ^^^^^^^^^^^^^^^^^^
    )
    ^
  File "/Users/ima/envs/qiskit/lib/python3.13/site-packages/qiskit/passmanager/base_tasks.py", line 218, in execute
    passmanager_ir, state = next_task.execute(
                            ~~~~~~~~~~~~~~~~~^
        passmanager_ir=passmanager_ir,
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        state=state,
        ^^^^^^^^^^^^
        callback=callback,
        ^^^^^^^^^^^^^^^^^^
    )
    ^
  File "/Users/ima/envs/qiskit/lib/python3.13/site-packages/qiskit/transpiler/basepasses.py", line 167, in execute
    new_dag, state = super().execute(
                     ~~~~~~~~~~~~~~~^
        passmanager_ir=passmanager_ir,
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        state=state,
        ^^^^^^^^^^^^
        callback=callback,
        ^^^^^^^^^^^^^^^^^^
    )
    ^
  File "/Users/ima/envs/qiskit/lib/python3.13/site-packages/qiskit/passmanager/base_tasks.py", line 98, in execute
    ret = self.run(passmanager_ir)
  File "/Users/ima/envs/qiskit/lib/python3.13/site-packages/qiskit/transpiler/passes/utils/control_flow.py", line 59, in out
    return method(self, dag)
  File "/Users/ima/envs/qiskit/lib/python3.13/site-packages/qiskit/transpiler/passes/optimization/optimize_1q_decomposition.py", line 211, in run
    optimize_1q_gates_decomposition.optimize_1q_gates_decomposition(
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^
        dag,
        ^^^^
    ...<2 lines>...
        basis_gates=self._basis_gates,
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
pyo3_runtime.PanicException: called `Result::unwrap()` on an `Err` value: QargsWithoutInstruction("[PhysicalQubit(30)]")
```

### What should happen?

It would be nice to raise a more comprehensive exception or error than `PanicException`.
In this case, the reason is obvious (mismatch of the number of qubtis).

### Any suggestions?

_No response_

### PR DESCRIPTION
**Pull request by jakelishman**
These pathways are still error conditions, but at a minimum, we should not be panicking on legitimate (if incorrect) inputs from Python space.

### Details and comments

Fix #15116.

I also wrote in the `expect` condition for a couple of other `unwrap` calls that really weren't obvious to me why we expected them to be ok.

### CODE REVIEW

File: crates/transpiler/src/passes/optimize_1q_gates_decomposition.rs [hunk 1]
```diff
@@ -93,21 +93,23 @@ pub fn run_optimize_1q_gates_decomposition(
...
                             return None;
                         }
                         let basis = EULER_BASIS_NAMES[idx];
                         Some(basis)
                     })
                     .for_each(|basis| target_basis_set.add_basis(basis)),
                 None => match &global_decomposers {
-                    Some(bases) => bases
-                        .iter()
-                        .map(|basis| EulerBasis::__new__(basis).unwrap())
```
Comment (mtreinish) [inline crates/transpiler/src/passes/optimize_1q_gates_decomposition.rs:109]: FWIW, at least in the original version of the port to rust the unwrap here was fine because we validate the global decomposers list Python side are all valid euler bases entries. I agree it's better to return the error now though since from C I don't think we do the same validation of the user input.

**Review by mtreinish — APPROVED** [review]
Thanks for this, this was clearly an oversight in the original pass. I think when we originally ported it to Rust we weren't really thinking about the standalone execution case and more just the full pipeline where we wouldn't have encountered that error condition

File: crates/transpiler/src/passes/optimize_1q_gates_decomposition.rs (hunk 1 above)
Comment (jakelishman) [reply crates/transpiler/src/passes/optimize_1q_gates_decomposition.rs:109]: I couldn't prove it to myself from the codebase so I made it an exception (otherwise I'd have made it an `expect` with the reason) - mostly I'm just trying to remove `unwrap`, since we're now calling the functions from more than one place, and more places are passing direct user input to Rust space, so it's harder to be sure of the invariants.
