### PR TITLE
Represent non-fixed params as `NaN` for `QkTargetOp`

### LINKED ISSUE #15438: Fix tracking of parameters in instances of `QkTargetOp`
### What should we add?

Currently we are returning conflicting information when retreiving a parametric operation using `qk_target_op_get`:

In rust we have
```rust
#[repr(C)]
struct CTargetOp {
    ...
    params: *mut f64 // Returns a list of all fixed parameters.
    num_params: u32 // Represents the number of parameters supported by the operation.
    ....
}
```

One idea suggested by @jakelishman:

> The logic here doesn't result in a boxed slice that's necessarily num_params entries long; it's only valid in C because we didn't provide a way to only specify partially fixed parameters yet. Once Targets can be created (say) by the Python interface and given to C (e.g. https://github.com/Qiskit/qiskit/pull/15337), we can't get away with that kind of assumption in the C API any more, so we'll have to handle it.
> 
> [...], but let's take a follow-up issue to (for example) use f64::NAN as a marker for "arbitrary" so the slice is definitely going to be the correct length and C space will be able to tell.

### PR DESCRIPTION
**Pull request by raynelfss**
### Summary
Fixes #15438 
Due to our decision of provisionally exposing parameters in `QkTargetOp` as `double[]` we mistakenly filtered out any non-fixed parameters instead of showing a placeholder value. This PR provisionally exposes any non-fixed parameter instance as `NaN` until we work out a much cleaner way of exposing the parameters to C.

### Details and comments
- [x] Add release note.

### CODE REVIEW

File: crates/cext/src/transpiler/target.rs [hunk 1]
```diff
@@ -1343,8 +1343,9 @@ pub struct CTargetOp {
     /// `(uint32_t)-1` in the case of a variadic.
     pub num_qubits: u32,
     /// The parameters tied to this operation if fixed, as an array
-    /// of `double`. If the operation doesn't posess any fixed parameters
-    /// or is variadic, this attribute will be a ``NULL`` pointer.
+    /// of `double`. If any of the parameters represented are not fixed angles
+    /// it will be represented as with the `NaN` value. If there are no parameters
+    /// then this value will be represented with a `NULL` pointer.
```
Comment (Cryoris) [inline crates/cext/src/transpiler/target.rs:1348]: This last part isn't true anymore, is it? If all parameters are free then we'd still have an array with all `f64::NAN` entries, right?

**Review by Cryoris — COMMENTED** [review]
From a bugfix POV I don't think we need to backport this (since we can't create a C Target object that would have `params` of unknown length). But from an interface POV this PR changes an all-free `params` from a NULL pointer to an array of `f64::NAN` and it would be good to not change this interface between 2.3 and 2.4, which makes it backportable IMO.

File: crates/cext/src/transpiler/target.rs (hunk 1 above)
Comment (raynelfss) [reply crates/cext/src/transpiler/target.rs:1348]: I guess I could've worded it better. But what I meant was if the operation doesn't accept any parameters.

File: releasenotes/notes/c-api-target-params-848091afd753a6c3.yaml [hunk 2]
```diff
@@ -0,0 +1,6 @@
+---
+upgrade_c:
```
Comment (eliarbel) [inline releasenotes/notes/c-api-target-params-848091afd753a6c3.yaml]: Do we still want this for 2.3? if so, this shouldn't be an upgrade but rather a feature which is actually already covered in #15512, so for 2.3 we actually don't need the reno at all.

File: test/c/test_target.c [hunk 3]
```diff
@@ -1022,6 +1022,24 @@ static int test_target_operation(void) {
                 result = EqualityError;
                 goto cleanup;
             }
+            if (inst_idx == 1) {
```
Comment (eliarbel) [inline test/c/test_target.c]: This comment is for the entire for-loop in this function - we need to call `qk_target_op_clear(&op)` at the end of each iteration otherwise the slices allocated in `qk_target_op_get` are not being freed.

**Review by eliarbel — COMMENTED** [review]
Overall, this LTGM and almost ready to merge, thanks Ray! I had a couple minor comments, please see them inline. 

@Cryoris do you have any other comments?

File: releasenotes/notes/c-api-target-params-848091afd753a6c3.yaml (hunk 2 above)
Comment (raynelfss) [reply releasenotes/notes/c-api-target-params-848091afd753a6c3.yaml]: Sounds good, I will remove the reno.

Edit: Removed in 1568decd2d25ac6b95bfb0ff5fd592a3934f919d

File: test/c/test_target.c (hunk 3 above)
Comment (raynelfss) [reply test/c/test_target.c]: Added in 3b5d31324d9ab0fec13529885b6b9f3156112f28

**Review by eliarbel — DISMISSED** [review]
LGTM, thanks for the changes. I'll go ahead and approve but will not enqueue for now in case Julien has more comments.

File: test/c/test_target.c
Comment (Cryoris) [inline test/c/test_target.c:1]: Do we have a test that checks the parameters are indeed `NULL` for free parameters?

**Review by jakelishman — CHANGES_REQUESTED** [review]
imo changing the typing like this is too big a change to merge after rc1 is released and the same day as the release.  I would have been comfortable leaving all the typing in place and using `nan` as a sentinel for "free parameter" for backport within the rc period, but swapping to `QkParam` has additional borrowing semantics that we haven't checked.

The C API is explicitly unstable and can be changed between versions, while the rc period is a well-established development practice we have to stop us from rushing in major untested changes even to _stable_ APIs.  I'd much rather we stick to the spirit of the rc freeze than rush in changes to an API that we can change in the next release.

**Comment by raynelfss** [comment]
I reverted the PR to its original state for an easier patch. Added a fix release note and kept the commits adding ``QkParam`` in a different branch, for which I will open a new PR.

File: crates/cext/src/transpiler/target.rs (hunk 1 above)
Comment (jakelishman) [reply crates/cext/src/transpiler/target.rs:1348]: I think this comment is correct for the implementation now.

File: releasenotes/notes/c-api-target-params-6a54fcfcbe14de7e.yaml [hunk 4]
```diff
@@ -0,0 +1,8 @@
+---
+fixes:
+  - |
+    Fixed a mismatch in :c:struct:`QkTargetOp` in which the length of the array
+    stored in :c:member:`QkTargetOp.params` did not match the number exposed by
+    :c:member:`QkTargetOp.num_params`. The following PR fixes it by exposing any
+    placeholder parameters as ``NAN`` so the length of the array always matches
+    that of :c:member:`QkTargetOp.num_params`.
```
Comment (jakelishman) [inline releasenotes/notes/c-api-target-params-6a54fcfcbe14de7e.yaml]: We can't say "the following PR" since the release notes don't refer to PRs.  We might also want to comment that the bug is only present in rc1 (I think?).

Maybe something like

> Wildcard parameters are now represented by `nan`, and the length of the array will always be `` :c:member:`QkTargetOp.num_params` ``.  This bug was only present in 2.3.0rc1.

?

**Review by jakelishman — COMMENTED** [review]
Thanks Ray, this looks much more suitable for backport.

File: releasenotes/notes/c-api-target-params-6a54fcfcbe14de7e.yaml (hunk 4 above)
Comment (raynelfss) [reply releasenotes/notes/c-api-target-params-6a54fcfcbe14de7e.yaml]: Changed in 22abd7d3518ff018ef677ed2875cff7614c28b9e

**Review by jakelishman — APPROVED** [review]
Thanks Ray - I think we're good to go now.
