### PR TITLE
Fix param extraction for arrays with a single element

### LINKED ISSUE #15426: Single-qubit permutation causes Rust transpiler to panic
### Environment

- **Qiskit version**: 2.2.3
- **Python version**: 3.12.3
- **Operating system**: Ubuntu 24.04.3 LTS

### What is happening?

I'm getting an internal error from the Rust part of the Qiskit transpiler when trying to compile a single-qubit permutation (which should be a no-op) to a device.

### How can we reproduce the issue?

Run this code:

```
from qiskit_ibm_runtime.fake_provider import FakeTorino
from qiskit.circuit.library import PermutationGate
from qiskit import QuantumCircuit, transpile

c = QuantumCircuit(1)
c.append(PermutationGate([0]), [0])
transpile(c, backend=FakeTorino())
```

### What should happen?

Instead of compiling to an empty circuit, I get this error message:
```
---------------------------------------------------------------------------
PanicException                            Traceback (most recent call last)
Cell In[8], line 7
      5 c = QuantumCircuit(1)
      6 c.append(PermutationGate([0]), [0])
----> 7 transpile(c, backend=FakeTorino())

File path/to/venv/lib/python3.12/site-packages/qiskit/compiler/transpiler.py:291, in transpile(circuits, backend, basis_gates, coupling_map, initial_layout, layout_method, routing_method, translation_method, scheduling_method, dt, approximation_degree, seed_transpiler, optimization_level, callback, output_name, unitary_synthesis_method, unitary_synthesis_plugin_config, target, hls_config, init_method, optimization_method, ignore_backend_supplied_default_methods, num_processes, qubits_initially_zero)
    266 # Edge cases require using the old model (loose constraints) instead of building a target,
    267 # but we don't populate the passmanager config with loose constraints unless it's one of
    268 # the known edge cases to control the execution path.
    269 pm = generate_preset_pass_manager(
    270     optimization_level,
    271     target=target,
   (...)
    288     qubits_initially_zero=qubits_initially_zero,
    289 )
--> 291 out_circuits = pm.run(circuits, callback=callback, num_processes=num_processes)
    293 for name, circ in zip(output_name, out_circuits):
    294     circ.name = name

File path/to/venv/lib/python3.12/site-packages/qiskit/transpiler/passmanager.py:415, in StagedPassManager.run(self, circuits, output_name, callback, num_processes, property_set)
    405 def run(
    406     self,
    407     circuits: _CircuitsT,
   (...)
    412     property_set: dict[str, object] | None = None,
    413 ) -> _CircuitsT:
    414     self._update_passmanager()
--> 415     return super().run(circuits, output_name, callback, num_processes=num_processes)

File path/to/venv/lib/python3.12/site-packages/qiskit/transpiler/passmanager.py:438, in _replace_error.<locals>.wrapper(*meth_args, **meth_kwargs)
    435 @wraps(meth)
    436 def wrapper(*meth_args, **meth_kwargs):
    437     try:
--> 438         return meth(*meth_args, **meth_kwargs)
    439     except TranspilerError:
    440         # If it's already a `TranspilerError` subclass, don't erase the extra information.
    441         raise

File path/to/venv/lib/python3.12/site-packages/qiskit/transpiler/passmanager.py:197, in PassManager.run(self, circuits, output_name, callback, num_processes, property_set)
    194 if callback is not None:
    195     callback = _legacy_style_callback(callback)
--> 197 return super().run(
    198     in_programs=circuits,
    199     callback=callback,
    200     output_name=output_name,
    201     num_processes=num_processes,
    202     property_set=property_set,
    203 )

File path/to/venv/lib/python3.12/site-packages/qiskit/passmanager/passmanager.py:238, in BasePassManager.run(self, in_programs, callback, num_processes, property_set, **kwargs)
    234 # If we're not going to run in parallel, we want to avoid spending time `dill` serializing
    235 # ourselves, since that can be quite expensive.
    236 if len(in_programs) == 1 or not should_run_in_parallel(num_processes):
    237     out = [
--> 238         _run_workflow(
    239             program=program,
    240             pass_manager=self,
    241             callback=callback,
    242             initial_property_set=property_set,
    243             **kwargs,
    244         )
    245         for program in in_programs
    246     ]
    247     if len(in_programs) == 1 and not is_list:
    248         return out[0]

File path/to/venv/lib/python3.12/site-packages/qiskit/passmanager/passmanager.py:311, in _run_workflow(program, pass_manager, initial_property_set, **kwargs)
    306 pass_manager.property_set = property_set
    307 passmanager_ir = pass_manager._passmanager_frontend(
    308     input_program=program,
    309     **kwargs,
    310 )
--> 311 passmanager_ir, final_state = flow_controller.execute(
    312     passmanager_ir=passmanager_ir,
    313     state=PassManagerState(
    314         workflow_status=initial_status, property_set=pass_manager.property_set
    315     ),
    316     callback=kwargs.get("callback", None),
    317 )
    318 # The `property_set` has historically been returned as a mutable attribute on `PassManager`
    319 # This makes us non-reentrant (though `PassManager` would be dependent on its internal tasks to
    320 # be re-entrant if that was required), but is consistent with previous interfaces.  We're still
    321 # safe to be called in a serial loop, again assuming internal tasks are re-runnable.  The
    322 # conversion to the backend language is also allowed to use the property set, so it must be set
    323 # before calling it.
    324 pass_manager.property_set = final_state.property_set

File path/to/venv/lib/python3.12/site-packages/qiskit/passmanager/base_tasks.py:218, in BaseController.execute(self, passmanager_ir, state, callback)
    216     return passmanager_ir, state
    217 while True:
--> 218     passmanager_ir, state = next_task.execute(
    219         passmanager_ir=passmanager_ir,
    220         state=state,
    221         callback=callback,
    222     )
    223     try:
    224         # Sending the object through the generator implies the custom controllers
    225         # can always rely on the latest data to choose the next task to run.
    226         next_task = task_generator.send(state)

File path/to/venv/lib/python3.12/site-packages/qiskit/transpiler/basepasses.py:167, in TransformationPass.execute(self, passmanager_ir, state, callback)
    161 def execute(
    162     self,
    163     passmanager_ir: PassManagerIR,
    164     state: PassManagerState,
    165     callback: Callable = None,
    166 ) -> tuple[PassManagerIR, PassManagerState]:
--> 167     new_dag, state = super().execute(
    168         passmanager_ir=passmanager_ir,
    169         state=state,
    170         callback=callback,
    171     )
    173     if state.workflow_status.previous_run == RunState.SUCCESS:
    174         if not isinstance(new_dag, DAGCircuit):

File path/to/venv/lib/python3.12/site-packages/qiskit/passmanager/base_tasks.py:98, in GenericPass.execute(self, passmanager_ir, state, callback)
     96 try:
     97     if self not in state.workflow_status.completed_passes:
---> 98         ret = self.run(passmanager_ir)
     99         run_state = RunState.SUCCESS
    100     else:

File path/to/venv/lib/python3.12/site-packages/qiskit/transpiler/passes/optimization/elide_permutations.py:69, in ElidePermutations.run(self, dag)
     63     logger.warning(
     64         "ElidePermutations is not valid after a layout has been set. This indicates "
     65         "an invalid pass manager construction."
     66     )
     67     return dag
---> 69 result = elide_permutations_rs.run(dag)
     71 # If the pass did not do anything, the result is None
     72 if result is None:

PanicException: internal error: entered unreachable code
```

### Any suggestions?

It seems like the problem is probably in `elide_permutations_rs`, but I haven't looked further.

### PR DESCRIPTION
**Pull request by alexanderivrii**
### Summary

Fixes #15426.

### Details and comments

When we define a permutation gate such as `perm = PermutationGate([0, 2, 1])` in Python, the permutation pattern `[0, 2, 1]` is stored in `gate.params[0]` as `numpy.ndarray`. On the Rust side, PyGate's `params_view()` matches `Param::Obj`, from which one can then extract `PyReadonlyArray1`. However, when the pattern consists of a single entry `[0]`, then on the Rust side `params_view()` matches `Param::Float(0.0)` and extraction of `PyReadonlyArray1` fails.

This PR implements Jake's suggestion of adding a cheap Numpy-array catch in the `impl FromPyObject` for `Param` block before the float extraction.

While this fixes the original issue, I am worried whether adding the extra check poses an overhead, and I am wondering if I should make this a bit more generic to handle more than just `PyReadonlyArray1<i32>>` specifically.

### CODE REVIEW

File: crates/circuit/src/operations.rs [hunk 1]
```diff
@@ -80,6 +80,8 @@ impl<'a, 'py> FromPyObject<'a, 'py> for Param {
     fn extract(b: Borrowed<'a, 'py, PyAny>) -> Result<Self, Self::Error> {
         Ok(if let Ok(py_expr) = b.extract::<PyParameterExpression>() {
             Param::ParameterExpression(Arc::new(py_expr.inner))
+        } else if b.extract::<PyReadonlyArray1<i32>>().is_ok() {
+            Param::Obj(b.to_owned().unbind())
```
Comment (debasmita2102) [inline crates/circuit/src/operations.rs:84]: just trying to understand.... is it needed to check ASV benchmark results comparing transpilation time for large circuits before and after adding the PyReadonlyArray1<i32> ??  Since the PR description specifically mentions concern about overhead from this "cheap catch" in hot parameter extraction paths, confirming it stays under a reasonable threshold (say <1-2% regression) would help ensure performance.

Comment (debasmita2102) [reply crates/circuit/src/operations.rs:84]: also... in the new code path where we do Param::Obj(b.to_owned().unbind()) for detected arrays, are we validating the array's length and shape (e.g., ensuring len() > 0 and ndim() == 1) before storing it as an opaque object, or is that expected to be handled by downstream transpiler passes? Since permutation gates fundamentally require non-empty patterns and malformed arrays may lead to crashes may be? trying to understandi the robustness strategy.

Comment (alexanderivrii) [reply crates/circuit/src/operations.rs:84]: This is a more general problem: pyo3 interprets single-element numpy arrays as scalars.

The particular user issue where this came up is the rather unusual use-case of defining a single-element permutation gate, in which case the single-element numpy array representing the permutation gets interpreted as float, breaking the `ElidePemutations` pass (which expects the parameter to be of type `Param::Obj` and not of type `Param::Float`). If I remember correctly, we do the "valid pattern" check when creating the `PermutationGate`, so we can indeed expect that the permutation pattern is valid. 

I do agree that we might be paying a (hopefully small) price for this extra check, I will run some tests to see how much it really is. I am a bit worried though that for a fully robust solution, we should also check if this is an `PyReadonlyArray1` or `PyReadonlyArray2` for every other possible type (`u32`, `f64`, etc.). So far I couldn't find a way to check all these different types at once. But hopefully we don't have too many cases of storing numpy arrays in instructions' `params`.

Comment (raynelfss) [inline crates/circuit/src/operations.rs]: Would it be easier to do something like this instead?? That way if the object is an instance it will not perform an extraction. Though this may be reaching the point of over-optimization but if we can make it easier then it should be bettr.

```suggestion
        } else if b.is_instance_of::<PyArray1<i32>>() {
            Param::Obj(b.to_owned().unbind())
```

**Review by raynelfss — COMMENTED** [review]
Would we be able to simplify by using ``T::is_instance_of::<V>()``?

File: crates/circuit/src/operations.rs (hunk 1 above)
Comment (alexanderivrii) [reply crates/circuit/src/operations.rs]: Thanks @raynelfss, this is a good suggestion, implemented in [77746cb](https://github.com/Qiskit/qiskit/pull/15436/commits/77746cbb6914485e324ca1041506e951812af1ca).

**Review by Cryoris — COMMENTED** [review]
Did you get around to checking if this has any runtime implications? I'm not super fond of  this additional check, especially since NumPy deprecated casting arrays (with dim>0) to float in 1.25, so this problem would go away at some point. But since we support NumPy from 1.17 onwards I guess we have to fix this on our end.

**Comment by mtreinish** [comment]
> Did you get around to checking if this has any runtime implications? I'm not super fond of this additional check, especially since NumPy deprecated casting arrays (with dim>0) to float in 1.25, so this problem would go away at some point. But since we support NumPy from 1.17 onwards I guess we have to fix this on our end.

If this is the case why don't we just bump the minimum numpy requirement? We try to be conservative on such changes but there isn't anything tying us to 1.17 in particular.

**Comment by jakelishman** [comment]
Also worth pointing out that the most recent version of Python that Numpy 1.17 supports is 3.8 lol

**Comment by Cryoris** [comment]
> If this is the case why don't we just bump the minimum numpy requirement? 

Unfortunately for this case, casting to a float is actually only removed in NumPy 2.4 -- that seems a bit to recent to require for this case 😅

**Review by raynelfss — DISMISSED** [review]

**Comment by raynelfss** [comment]
> > If this is the case why don't we just bump the minimum numpy requirement?
> 
> Unfortunately for this case, casting to a float is actually only removed in NumPy 2.4 -- that seems a bit to recent to require for this case 😅

I agree to not raise the version all the way to 2.4, I mean it's not like we could anyway since the minimum required version for that is Python 3.11 while we're going to be supporting 3.10 for the time being. And even if we were to go up to a different version (before 2.4) it will still turn the array into a scalar, so we need to get around it for now. This approach, for now, seems fair in my opinion.

However, it might be good to add a `TODO` note to remove it whenever we update NumPy to 2.4+ as it will `Err` in those cases which automatically cancels the extraction. The question then being who's going to remember to address this old comment? 😅

**Comment by alexanderivrii** [comment]
A "micro-local" benchmark shows that the time for the `extract` function itself is increased by about 1.5x - 2x, but each run is so fast that it's not observable on a higher level: running ASV benchmarks returns "BENCHMARKS NOT SIGNIFICANTLY CHANGED" (all of the ratios close to 1, with the outliers going up to `1.04` or down to `0.98`, but I believe is probably just noise).

**Review by Cryoris — APPROVED** [review]

**Comment by alexanderivrii** [comment]
Added a TODO remark (see [a3d0205](https://github.com/Qiskit/qiskit/pull/15436/commits/a3d02050e433a2d5cb10277c782a228aa99385ee)) as per @raynelfss's suggestion.

> The question then being who's going to remember to address this old comment?

I have a feeling that with so many external contributors eagerly willing to contribute to Qiskit, we will get 5 different PRs as soon as the NumPy version is increased. :)
