### PR TITLE
Fix "`BreakLoopOp' object has no attribute 'blocks" bug

### LINKED ISSUE #15579: `BreakLoopOp` does not have `blocks` attribute expected by pass `ContractIdleWiresInControlFlow`
### Environment

- **Qiskit version**: 2.3.0
- **Python version**: 3.14.0
- **Operating system**: Arch Linux

### What is happening?

Calling `transpile()` on a circuit with break_loop ops fails because the pass `ContractIdleWiresInControlFlow` calls `_contract_control_flow()`, which assumes that all ops have the attribute `blocks`.

This issue causes the test `test/terra/backends/aer_simulator/test_control_flow.py::TestControlFlow::test_transpile_break_and_continue_loop` from qiskit_aer to fail. See https://github.com/Qiskit/qiskit-aer/issues/2354

### How can we reproduce the issue?

1. Install qiskit 2.3.0
2. Get tests from qiskit_aer
3. Run e.g. `python -m pytest test/terra/backends/aer_simulator/test_control_flow.py`

### What should happen?

Test should not fail

### Any suggestions?

I guess the easiest workaround would be to check if the op object has attribute `blocks` before line 60:

https://github.com/Qiskit/qiskit/blob/9186f49af0396d82e7d9880602e719a46826ba1d/qiskit/transpiler/passes/optimization/contract_idle_wires_in_control_flow.py#L60C18-L60C27

Something like this:

```python
if not hasattr(op, "blocks"):
   return inst
```

### PR DESCRIPTION
**Pull request by gadial**
### Summary
Handles a bug arising in `ContractIdleWiresInControlFlow` when trying to iterate on the blocks of `BreakLoopOp` which has no blocks.

Fixes #15579 

### Details and comments
`BreakLoopOp` has no `blocks` property. This makes sense as blocks for this op are meaningless. While `blocks` is an abstract property of `ControlFlowOp`, `BreakLoopOp` is not a `ControlFlowOp` but merely `Instruction` so it should not have this property.

However, in `ContractIdleWiresInControlFlow._contract_control_flow` we iterate on `op.blocks` after performing the check
```
if inner.is_control_flow():
   # In `QuantumCircuit` it's easy to replace an instruction with a narrower one, so it
   # doesn't matter much if this is replacing it with itself.
   block.data[i] = inner = _contract_control_flow(inner)
```
Where `is_control_flow` attempts to use the rust conversion into the rust `ControlFlow` , and `BreakLoop` *is* an instance of `ControlFlow`.

There are two ways to solve this:
1. Add some guard before the iteration on `op.blocks` verifying the control flow indeed has blocks.
2. Decide whether `BreakLoop` is to be considered a control flow or not, and fix accordingly (e.g. make the python class an instance of `ControlFlowOp` and implement `blocks` to return an empty list.

I think 2 will be better since currently we have a problematic discrepancy between Python and Rust.

### CODE REVIEW

**Comment by jakelishman** [comment]
`ContinueLoop` may exhibit the same behaviour, btw.

If one transpiler pass shows this bug, it's pretty likely that others do too.  Imo, if we say that `ContractIdleWires` is doing something wrong here, then we've made the `is_control_flow` method basically useless for its intended purpose, so I'd say we either have to have that method return `false` for break/continue, have break/continue subclass `ControlFlowOp` like you suggested, or add a new method `has_control_flow_blocks` or something.

**Comment by gadial** [comment]
> `ContinueLoop` may exhibit the same behaviour, btw.
> 
> If one transpiler pass shows this bug, it's pretty likely that others do too. Imo, if we say that `ContractIdleWires` is doing something wrong here, then we've made the `is_control_flow` method basically useless for its intended purpose, so I'd say we either have to have that method return `false` for break/continue, have break/continue subclass `ControlFlowOp` like you suggested, or add a new method `has_control_flow_blocks` or something.

The question is - what *is* the intended purpose of `is_control_flow`? If that's to determine that our instruction is `ControlFlowOp` and supports the `ControlFlowOp` interface (e.g. the `blocks` method), then indeed the correct solution is to modify it to return `false` for control flows which currently, in the python code, do not inherit from `ControlFlowOp`. I just want to make sure that's the intended behavior since I didn't write or use `is_control_flow` myself.

**Comment by gadial** [comment]
Here's another example of how `is_control_flow` is used: In the `Decompose` transpiler pass, we have
```
if node.is_control_flow():
    decomposition = control_flow.map_blocks(self.run, node.op)
```

Where `map_block` relies on the node's op having the `replace_blocks` method - another abstract `ControlFlowOp` method.

Also in `CommutativeInverseCancellation` we use `is_control_flow` with `_skip_node`. In this situation we should skip break and continue, so it seems to me that changing `is_control_flow` is not the correct way to go. I think the solution which avoids future pitfalls is the one where we make `BreakLoop` and `ContinueLoop` inherit from `ControlFlowOp`, implementing the abstract methods in the expected way (returning empty list for `blocks` and doing nothing for `replace_blocks` (which is used by iterating on `blocks()` so it will be called on an empty list anyway).

One possible safeguard is to raise an error if `replace_blocks` is called with a nonempty list; but it seems currently our policy is to silently ignore such cases. e.g. for while loop we do
```
def replace_blocks(self, blocks):
        (body,) = blocks
        return WhileLoopOp(self._condition, body, label=self.label)
```
silently ignoring the case of more than one block (and failing ungracefully on zero blocks). Of course, those cases should never arise in practice with the intended usage of `replace_blocks` (by iterating on `blocks`).

**Comment by gadial** [comment]
This turned out even trickier than I thought. In `BreakLoop` instructions we have a qubit list, obtained from the instantiating circuit, although the `BreakLoop` instruction itself uses no qubits. This confuses the idle wires contractor. Even if we explicitly remove the qubits as part of the contraction, it results in test failures, since if we have
```
with expected.if_test((0, True)):
    expected.continue_loop()
```

Then the `if_test` will have a different number of qubits than in the contracted circuit, although the gates are the same.

So the question is - what purpose is served in the first place with `BreakLoop` and `ContinueLoop` having more than 0 qubits and clbits?

**Comment by jakelishman** [comment]
If we think about the dataflow concerns in the DAG, then `break` and `continue` still mark points that affect where _all_ the qubits will change.  For `IfElseOp` and the other block-based structured objects, the "end" of the control is implicitly just the end of the circuit.  For `break` and `continue`, it's a specific _single_ instruction.  So in this form, they have to put a data-flow dependence on all the qubits that are within the block, which is why there's a difference.  (This is kind of an unusual setup for representing a control-flow graph, which is partly why it's awkward.)

One of the things that the control-flow builder interface takes care of, which would be desperately hard to get right otherwise, is to ensure that `break` and `continue` get filled in with all the qubits that they need to, even if they're not all natively used within the same innermost scope as the break/continue.

There's a subtlety here, though, that a qubit that is _only_ touched by breaks/continues is probably still idle in the sense of `ContractIdleWires`.  For the immediate bugfix, I'd be happy just to merge the fix to `is_control_flow`, since then the pass will still be correct, just missing an optimisation it could otherwise do.  We could potentially follow up with a patch that contracts wires that are only touched by break/continue statements as "idle" as well.

---

I'm fairly sure `is_control_flow` was introduced as a way of doing the `ControlFlowOp` subclass check without actually creating a Python instance of a standard gate for a check that would automatically fail.  The right thing is to make it respect that again.  The use in `CommutativeInverseCancellation` shouldn't become _wrong_ by doing that, it'll just not see a potential short-circuit.  We could add another short-circuit catch if we wanted, but it's probably not worth it.

**Comment by gadial** [comment]
Trying to make `BreakLoop` a `ControlFlowOp` resulted in problems from multiple areas of the code, so obviously fixing `is_control_flow` is better, so that's what I settled on.

File: crates/circuit/src/circuit_instruction.rs [hunk 1]
```diff
@@ -271,7 +271,13 @@ impl CircuitInstruction {
...
     /// instance of :class:`.ControlFlowOp`)?
     pub fn is_control_flow(&self) -> bool {
-        self.operation.try_control_flow().is_some()
+        let control_flow_op = self.operation.try_control_flow();
+        if let Some(control_flow) = control_flow_op {
+            !matches!(control_flow.control_flow, ControlFlow::BreakLoop)
+                && !matches!(control_flow.control_flow, ControlFlow::ContinueLoop)
+        } else {
+            false
+        }
```
Comment (alexanderivrii) [inline crates/circuit/src/circuit_instruction.rs]: Thanks Gadi for the fix. This seems consistent with Jake's suggestion ~but I will let him have another look~ (update: since it's just a 1-line fix, no need to pile this on Jake).

Two minor suggestions about the rust code.

You can combine the two match statements into one, something like 
```rust
!matches!(control_flow.control_flow, ControlFlow::BreakLoop | ControlFlow::ContinueLoop)
```

You can also do something like this:
```rust
self.operation.try_control_flow().is_some_and(...)
```

**Comment by alexanderivrii** [comment]
You are also missing a bugfix release note.

File: crates/circuit/src/circuit_instruction.rs (hunk 1 above)
Comment (gadial) [reply crates/circuit/src/circuit_instruction.rs]: Nice! Did it and added release note in https://github.com/Qiskit/qiskit/pull/15581/commits/597cfe1c0c88024651b01f6453678b8deac5558c

File: releasenotes/notes/fix_is_control_flow-7e48e552d41f80b8.yaml [hunk 2]
```diff
@@ -0,0 +1,5 @@
+---
+fixes:
+  - |
+    The rust ``is_control_flow`` method now returns ``false``` on BreakLoop and ContinueLoop constructs
+    as is expected by the parts of the code that use it. Fixed `#15579 <https://github.com/Qiskit/qiskit/issues/15579>`__.
```
Comment (alexanderivrii) [inline releasenotes/notes/fix_is_control_flow-7e48e552d41f80b8.yaml]: There is an extra tick around `false`.

Other than that, can we make this release note more user-oriented: I am not sure we should explicitly mention internal rust-space objects, maybe we can mention python's 
```
:class:`.ContinueLoopOp` and :class:`.BreakLoopOp`
```
instead?

```suggestion
    The rust ``is_control_flow`` method now returns ``false`` on BreakLoop and ContinueLoop constructs
    as is expected by the parts of the code that use it. Fixed `#15579 <https://github.com/Qiskit/qiskit/issues/15579>`__.
```

**Review by alexanderivrii — COMMENTED** [review]
Just some minor nitpicks about the release note, otherwise it's good to go.

One other question: do we want to backport this fix?

File: releasenotes/notes/fix_is_control_flow-7e48e552d41f80b8.yaml (hunk 2 above)
Comment (gadial) [reply releasenotes/notes/fix_is_control_flow-7e48e552d41f80b8.yaml]: Ok, changed according to your suggestions in [c209825](https://github.com/Qiskit/qiskit/pull/15581/commits/c2098254a40c00c45fee2305676c0cfbcde3e2f4)

**Review by alexanderivrii — APPROVED** [review]
