### PR TITLE
Fix schedule analysis passes with empty circuits

### LINKED ISSUE #15145: ALAP and ASAP schedule analysis fail on empty circuits
### Environment

- **Qiskit version**: 2.2.1
- **Python version**: 3.13
- **Operating system**: macOS

### What is happening?

`ALAPScheduleAnalysis` and `ASAPScheduleAnalysis` both fail with a message saying "No durations provided" when durations _are_ provided, but the circuit has no operations.

### How can we reproduce the issue?

```python
from qiskit import QuantumCircuit
from qiskit.transpiler.passes import ASAPScheduleAnalysis
from qiskit_ibm_runtime.fake_provider import FakeFez

target = FakeFez().target
assert target.durations() is not None

qc = QuantumCircuit(4, 4)
pass_ = ASAPScheduleAnalysis(target=target)
pass_(qc)
```
```
---------------------------------------------------------------------------
TranspilerError                           Traceback (most recent call last)
Cell In[5], line 10
      8 qc = QuantumCircuit(4, 4)
      9 pass_ = ASAPScheduleAnalysis(target=target)
---> 10 pass_(qc)

[... snip ...]

File ~/code/qiskit/terra/qiskit/transpiler/passes/scheduling/scheduling/asap.py:47, in ASAPScheduleAnalysis.run(self, dag)
     43 node_durations = {
     44     node: self._get_node_duration(node, dag) for node in dag.topological_op_nodes()
     45 }
     46 clbit_write_latency = self.property_set.get("clbit_write_latency", 0)
---> 47 self.property_set["node_start_time"] = asap_schedule_analysis(
     48     dag, clbit_write_latency, node_durations
     49 )

TranspilerError: 'No durations provided'
```

### What should happen?

An empty circuit is trivially scheduled - this shouldn't be an error.

### Any suggestions?

_No response_

### PR DESCRIPTION
**Pull request by jakelishman**
Internally the passes look for the time-unit type of the first operation in the circuit, to dispatch to wall-time or clock-cycle handlers.  This caused trouble if there _were_ no durations, even though the circuit is trivially scheduled.

### Details and comments

The diff is a bit awkward, but 90% of the changes are just indentation.

Fix #15145.

### CODE REVIEW

File: crates/transpiler/src/passes/alap_schedule_analysis.rs [hunk 1]
```diff
@@ -190,50 +190,49 @@ pub fn py_run_alap_schedule_analysis(
...
+        }
+        let node_start_time =
+            run_alap_schedule_analysis::<f64>(dag, clbit_write_latency as f64, op_durations)?;
+        for (node_idx, t1) in node_start_time {
+            let node = dag.get_node(py, node_idx)?;
+            py_dict.set_item(node, t1)?;
         }
     } else {
-        return Err(TranspilerError::new_err("No durations provided"));
+        return Err(TranspilerError::new_err("Duration must be int or float"));
```
Comment (ihincks) [inline crates/transpiler/src/passes/alap_schedule_analysis.rs:234]: better error :+1:

Comment (jakelishman) [reply crates/transpiler/src/passes/alap_schedule_analysis.rs:234]: Actually this is a totally different error that already existed, it's just that I fiddled with the indentation so it _looks_ like it's in the same place as the old one in the diff.

The actual fix is removing the outer `if let Some((_, first_durations)) = ...`, whose `else` branch previously returned "No durations given", and replacing it with `let Some((_, first_durations)) = ... else { return PyDict::new(); }` (return an empty Python dictionary).

**Comment by Muri7910** [comment]
Hi @jakelishman, @ihincks  — just wanted to ask if there’s an expected timeline for merging this fix?
I noticed all checks have passed and it looks ready to go, just waiting on final review/approval.
Thanks a lot for the work on this! This fix would greatly help me in my experiments!

**Review by kevinhartman — APPROVED** [review]
LGTM.
