### PR TITLE
Rebalance `CircuitInstruction` and `PackedInstruction`

### LINKED ISSUE #12567: Optimize memory footprint of `OperationType`
This type is exceptionally wide for something that we _want_ to be almost entirely `StandardGate` (which could even be `u8` sized).  Realistically we're not going to get this below a `usize`, but that should be achievable by pointer-indirecting the `PyInstruction` etc variants, and storing the enum discriminant in the 2 low bits of the pointer (if we expand the enum in the future and need more than 2 bits, we'll have to think about our 32-bit platform support).

_Originally posted by @jakelishman in https://github.com/Qiskit/qiskit/pull/12459#discussion_r1631665043_

### LINKED ISSUE #12622: Rework heirarchy of `CircuitInstruction` and `PackedInstruction`
### What should we add?

Since #10827 we had a two level hierarchy for instructions in a circuit. There was `CircuitInstruction` which was a python space representation and `PackedInstruction` which was a rust space representation with a compressed qubit representation. At that point in time this was fine because we never were accessing any data in the circuit via rust and we were only using rust to store a compressed form at rest. However, since #12459 merged this has gotten a bit more muddled because we have frequent use of circuit data via rust. This has led the original abstractions to not holding up as well because the packed instruction is not as compact as it could be and the we're using the python space representation from rust.  We should add a new middle representation for a rust native "unpacked instruction".

### PR DESCRIPTION
**Pull request by jakelishman**
### Summary

This is a large overhaul of how circuit instructions are both stored in Rust (`PackedInstruction`) and how they are presented to Python (`CircuitInstruction`).  In summary:

* The old `OperationType` enum is now collapsed into a manually managed `PackedOperation`.  This is logically equivalent, but stores a `PyGate`/`PyInstruction`/`PyOperation` indirectly through a boxed pointer, and stores a `StandardGate` inline.  As we expect the vast majority of gates to be standard, this hugely reduces the memory usage.  The enumeration is manually compressed to a single pointer, hiding the discriminant in the low, alignment-required bytes of the pointer.

* `PackedOperation::view()` unpacks the operation into a proper reference-like enumeration `OperationRef<'a>`, which implements `Operation` (though there is also a `try_standard_gate` method to get the gate without unpacking the whole enumeration).

* Both `PackedInstruction` and `CircuitInstruction` use this `PackedOperation` as the operation storage.

* `PackedInstruction` is now completely the Rust-space format for data, and `CircuitInstruction` is purely for communication with Python.

On my machine, this commit brings the utility-scale benchmarks to within 10% of the runtime of 1.1.0 (and some to parity), despite all the additional overhead.

Changes to accepting and building Python objects
------------------------------------------------

* A `PackedInstruction` is created by copy constructor from a `CircuitInstruction` by `CircuitData::pack`.  There is no `pack_owned` (really, there never was - the previous method didn't take ownership) because there's never owned `CircuitInstruction`s coming in; they're Python-space interop, so we never own them (unless we clone them) other than when we're unpacking them.

* `PackedInstruction` is currently just created manually when not coming from a `CircuitInstruction`.  It's not hard, and makes it easier to re-use known intern indices than to waste time re-interning them. There is no need to go via `CircuitInstruction`.

* `CircuitInstruction` now has two separated Python-space constructors: the old one, which is the default and takes `(operation, qubits, clbits)` (and extracts the information), and a new fast-path `from_standard` which asks only for the standard gate, qubits and params, avoiding operator construction.

* To accept a Python-space operation, extract a Python object to `OperationFromPython`.  This extracts the components that are separate in Rust space, but joined in Python space (the operation, params and extra attributes).  This replaces `OperationInput` and `OperationTypeConstruct`, being more efficient at the extraction, including providing the data in the formats needed for `PackedInstruction` or `CircuitInstruction`.

* To retrieve the Python-space operation, use `CircuitInstruction::get_operation` or `PackedInstruction::unpack_py_op` as appropriate.  Both will cache and reuse the op, if `cache_pygates` is active.  (Though note that if the op is created by `CircuitInstruction`, it will not propagate back to a `PackedInstruction`.)

Avoiding operation creation
---------------------------

The `_raw_op` field of `CircuitInstruction` is gone, because `PyGate`, `PyInstruction` and `PyOperation` are no longer pyclasses and no longer exposed to Python.  Instead, we avoid operation creation by:

* having an internal `DAGNode::_to_circuit_instruction`, which returns a copy of the internal `CircuitInstruction`, which can then be used with `CircuitInstruction.replace`, etc.

* having `CircuitInstruction::is_standard_gate` to query from Python space if we should bother to create the operator.

* changing `CircuitData::map_ops` to `map_nonstandard_ops`, and having it only call the Python callback function if the operation is not an unconditional standard gate.

Memory usage
------------

Given the very simple example construction script:

```python
from qiskit.circuit import QuantumCircuit

qc = QuantumCircuit(1_000)
for _ in range(3_000):
    for q in qc.qubits:
        qc.rz(0.0, q)
    for q in qc.qubits:
        qc.rx(0.0, q)
    for q in qc.qubits:
        qc.rz(0.0, q)
    for a, b in zip(qc.qubits[:-1], qc.qubits[1:]):
        qc.cx(a, b)
```

This uses 1.5GB in max resident set size on my Macbook (note that it's about 12 million gates) on both 1.1.0 and with this commit, so we've undone our memory losses.  The parent of this commit uses 2GB.

However, we're in a strong position to beat 1.1.0 in the future now; there are two obvious large remaining costs:

* There are 16 bytes per `PackedInstruction` for the Python-operation caching (worth about 180MB in this benchmark, since no Python operations are actually created).

* There is also significant memory wastage in the current `SmallVec<[Param; 3]>` storage of the parameters; for all standard gates, we know statically how many parameters are / should be stored, and we never need to increase the capacity.  Further, the `Param` enum is 16 bytes wide per parameter, of which nearly 8 bytes is padding, but for all our current use cases, we only care if _all_ the parameters or floats (for everything else, we're going to have to defer to Python).  We could move the discriminant out to the level of the parameters structure, and save a large amount of padding.

Further work
------------

There's still performance left on the table here:

* We still copy-in and copy-out of `CircuitInstruction` too much right now; we might want to make all the `CircuitInstruction` fields nullable and have `CircuitData::append` take them by _move_ rather than by copy.

* The qubits/clbits interner requires owned arrays going in, but most interning should return an existing entry.  We probably want to switch to have the interner take references/iterators by default, and clone when necessary.  We could have a small circuit optimisation where the intern contexts reserve the first n entries to use for an all-to-all connectivity interning for up to (say) 8 qubits, since the transpiler will want to create a lot of ephemeral small circuits.

* The `Param` vectors are too heavy at the moment; `SmallVec<[Param; 3]>` is 56 bytes wide, despite the vast majority of gates we care about having at most one single float (8 bytes).  Dead padding is a large chunk of the memory use currently.

### Details and comments

Benchmarks in follow-up comments because GitHub complained I went over the limit.  Top-level summary:

* this is faster than its parent commit by over 2x pretty much across the board of `QuantumCircuit` creation and manipulation, and has non-trivial improvements for `DAGCircuit` manipulation
* this brings the utility-scale transpilation benchmarks back to within 10% of the runtime of 1.1.0, and equal on a couple.  #12705 and #12550 (or at least the subsequent porting of transpiler passes) should get us beyond 1.1.0 performance.
* we're getting closer to 1.1.0 performance across the board.  `assign_parameters` is still currently taking a big hit, but moving the orchestration of that down to Rust would likely get us back to parity.

Closes:
* Fix #12622
* Fix #12567

### CODE REVIEW

**Comment by jakelishman** [comment]
Benchmarking against its parent commit (bb60891a), showing only changed benchmarks.  This is almost universally better across the board of circuit construction and manipulation, by half to a full order of magnitude.  Transpile and DAG-related operations are faster too, most likely because the conversions are _slightly_ cheaper now and there's less data to iterate through on copies.

```text
| Change   | Before [bb60891a] <repack-instruction~1>   | After [d9e31ed5] <repack-instruction>   |   Ratio | Benchmark (Parameter)                                                                                           |
|----------|--------------------------------------------|-----------------------------------------|---------|-----------------------------------------------------------------------------------------------------------------|
| -        | 12.0±0.4ms                                 | 10.5±0.2ms                              |    0.87 | circuit_construction.CircuitConstructionBench.time_circuit_construction(2, 2048)                                |
| -        | 766±20ms                                   | 693±10ms                                |    0.9  | circuit_construction.CircuitConstructionBench.time_circuit_construction(5, 131072)                              |
| -        | 12.7±0.2ms                                 | 10.8±0.2ms                              |    0.85 | circuit_construction.CircuitConstructionBench.time_circuit_construction(5, 2048)                                |
| -        | 153±10μs                                   | 124±3μs                                 |    0.81 | circuit_construction.CircuitConstructionBench.time_circuit_construction(8, 8)                                   |
| -        | 13.2±0.4μs                                 | 10.7±0.3μs                              |    0.81 | circuit_construction.CircuitConstructionBench.time_circuit_copy(1, 128)                                         |
| -        | 14.9±0.5ms                                 | 2.92±0.6ms                              |    0.2  | circuit_construction.CircuitConstructionBench.time_circuit_copy(1, 131072)                                      |
| -        | 76.2±10μs                                  | 37.8±5μs                                |    0.5  | circuit_construction.CircuitConstructionBench.time_circuit_copy(1, 2048)                                        |
| -        | 1.58±0.4ms                                 | 543±200μs                               |    0.34 | circuit_construction.CircuitConstructionBench.time_circuit_copy(1, 32768)                                       |
| -        | 286±30μs                                   | 106±20μs                                |    0.37 | circuit_construction.CircuitConstructionBench.time_circuit_copy(1, 8192)                                        |
| -        | 14.7±2ms                                   | 3.68±0.1ms                              |    0.25 | circuit_construction.CircuitConstructionBench.time_circuit_copy(14, 131072)                                     |
| -        | 84.0±20μs                                  | 40.8±5μs                                |    0.49 | circuit_construction.CircuitConstructionBench.time_circuit_copy(14, 2048)                                       |
| -        | 1.77±0.2ms                                 | 532±100μs                               |    0.3  | circuit_construction.CircuitConstructionBench.time_circuit_copy(14, 32768)                                      |
| -        | 417±50μs                                   | 122±30μs                                |    0.29 | circuit_construction.CircuitConstructionBench.time_circuit_copy(14, 8192)                                       |
| -        | 15.1±2ms                                   | 3.73±0.2ms                              |    0.25 | circuit_construction.CircuitConstructionBench.time_circuit_copy(2, 131072)                                      |
| -        | 90.6±30μs                                  | 32.2±5μs                                |    0.36 | circuit_construction.CircuitConstructionBench.time_circuit_copy(2, 2048)                                        |
| -        | 2.69±0.7ms                                 | 541±100μs                               |    0.2  | circuit_construction.CircuitConstructionBench.time_circuit_copy(2, 32768)                                       |
| -        | 434±70μs                                   | 142±20μs                                |    0.33 | circuit_construction.CircuitConstructionBench.time_circuit_copy(2, 8192)                                        |
| -        | 13.6±1ms                                   | 3.67±0.1ms                              |    0.27 | circuit_construction.CircuitConstructionBench.time_circuit_copy(20, 131072)                                     |
| -        | 87.4±10μs                                  | 50.9±6μs                                |    0.58 | circuit_construction.CircuitConstructionBench.time_circuit_copy(20, 2048)                                       |
| -        | 2.38±0.4ms                                 | 577±100μs                               |    0.24 | circuit_construction.CircuitConstructionBench.time_circuit_copy(20, 32768)                                      |
| -        | 403±100μs                                  | 117±8μs                                 |    0.29 | circuit_construction.CircuitConstructionBench.time_circuit_copy(20, 8192)                                       |
| -        | 18.8±3ms                                   | 3.62±0.3ms                              |    0.19 | circuit_construction.CircuitConstructionBench.time_circuit_copy(5, 131072)                                      |
| -        | 79.3±10μs                                  | 34.0±3μs                                |    0.43 | circuit_construction.CircuitConstructionBench.time_circuit_copy(5, 2048)                                        |
| -        | 2.95±0.5ms                                 | 576±100μs                               |    0.19 | circuit_construction.CircuitConstructionBench.time_circuit_copy(5, 32768)                                       |
| -        | 317±100μs                                  | 108±30μs                                |    0.34 | circuit_construction.CircuitConstructionBench.time_circuit_copy(5, 8192)                                        |
| -        | 18.8±2ms                                   | 3.61±0.3ms                              |    0.19 | circuit_construction.CircuitConstructionBench.time_circuit_copy(8, 131072)                                      |
| -        | 87.3±20μs                                  | 44.5±8μs                                |    0.51 | circuit_construction.CircuitConstructionBench.time_circuit_copy(8, 2048)                                        |
| -        | 1.83±0.2ms                                 | 484±200μs                               |    0.26 | circuit_construction.CircuitConstructionBench.time_circuit_copy(8, 32768)                                       |
| -        | 346±40μs                                   | 118±20μs                                |    0.34 | circuit_construction.CircuitConstructionBench.time_circuit_copy(8, 8192)                                        |
| -        | 141±7μs                                    | 30.9±0.3μs                              |    0.22 | circuit_construction.CircuitConstructionBench.time_circuit_extend(1, 128)                                       |
| -        | 129±2ms                                    | 23.0±0.9ms                              |    0.18 | circuit_construction.CircuitConstructionBench.time_circuit_extend(1, 131072)                                    |
| -        | 1.83±0.07ms                                | 343±8μs                                 |    0.19 | circuit_construction.CircuitConstructionBench.time_circuit_extend(1, 2048)                                      |
| -        | 29.5±0.7ms                                 | 5.68±0.2ms                              |    0.19 | circuit_construction.CircuitConstructionBench.time_circuit_extend(1, 32768)                                     |
| -        | 16.9±0.5μs                                 | 11.3±0.5μs                              |    0.67 | circuit_construction.CircuitConstructionBench.time_circuit_extend(1, 8)                                         |
| -        | 8.00±0.3ms                                 | 1.39±0.08ms                             |    0.17 | circuit_construction.CircuitConstructionBench.time_circuit_extend(1, 8192)                                      |
| -        | 139±4μs                                    | 54.1±7μs                                |    0.39 | circuit_construction.CircuitConstructionBench.time_circuit_extend(14, 128)                                      |
| -        | 146±1ms                                    | 34.7±0.2ms                              |    0.24 | circuit_construction.CircuitConstructionBench.time_circuit_extend(14, 131072)                                   |
| -        | 1.94±0.03ms                                | 439±10μs                                |    0.23 | circuit_construction.CircuitConstructionBench.time_circuit_extend(14, 2048)                                     |
| -        | 34.4±2ms                                   | 7.24±0.4ms                              |    0.21 | circuit_construction.CircuitConstructionBench.time_circuit_extend(14, 32768)                                    |
| -        | 43.0±0.8μs                                 | 27.0±0.7μs                              |    0.63 | circuit_construction.CircuitConstructionBench.time_circuit_extend(14, 8)                                        |
| -        | 8.01±0.3ms                                 | 1.83±0.09ms                             |    0.23 | circuit_construction.CircuitConstructionBench.time_circuit_extend(14, 8192)                                     |
| -        | 129±7μs                                    | 36.0±2μs                                |    0.28 | circuit_construction.CircuitConstructionBench.time_circuit_extend(2, 128)                                       |
| -        | 143±3ms                                    | 33.6±2ms                                |    0.23 | circuit_construction.CircuitConstructionBench.time_circuit_extend(2, 131072)                                    |
| -        | 1.87±0.03ms                                | 380±20μs                                |    0.2  | circuit_construction.CircuitConstructionBench.time_circuit_extend(2, 2048)                                      |
| -        | 32.6±0.8ms                                 | 7.02±0.3ms                              |    0.22 | circuit_construction.CircuitConstructionBench.time_circuit_extend(2, 32768)                                     |
| -        | 20.0±3μs                                   | 11.5±0.2μs                              |    0.58 | circuit_construction.CircuitConstructionBench.time_circuit_extend(2, 8)                                         |
| -        | 7.57±0.1ms                                 | 1.62±0.05ms                             |    0.21 | circuit_construction.CircuitConstructionBench.time_circuit_extend(2, 8192)                                      |
| -        | 158±4μs                                    | 57.8±10μs                               |    0.37 | circuit_construction.CircuitConstructionBench.time_circuit_extend(20, 128)                                      |
| -        | 144±6ms                                    | 35.6±2ms                                |    0.25 | circuit_construction.CircuitConstructionBench.time_circuit_extend(20, 131072)                                   |
| -        | 1.92±0.06ms                                | 447±7μs                                 |    0.23 | circuit_construction.CircuitConstructionBench.time_circuit_extend(20, 2048)                                     |
| -        | 33.7±1ms                                   | 7.42±0.5ms                              |    0.22 | circuit_construction.CircuitConstructionBench.time_circuit_extend(20, 32768)                                    |
| -        | 52.8±2μs                                   | 26.5±0.8μs                              |    0.5  | circuit_construction.CircuitConstructionBench.time_circuit_extend(20, 8)                                        |
| -        | 7.61±0.2ms                                 | 1.90±0.1ms                              |    0.25 | circuit_construction.CircuitConstructionBench.time_circuit_extend(20, 8192)                                     |
| -        | 136±3μs                                    | 38.4±0.8μs                              |    0.28 | circuit_construction.CircuitConstructionBench.time_circuit_extend(5, 128)                                       |
| -        | 141±5ms                                    | 34.9±1ms                                |    0.25 | circuit_construction.CircuitConstructionBench.time_circuit_extend(5, 131072)                                    |
| -        | 1.95±0.06ms                                | 457±20μs                                |    0.24 | circuit_construction.CircuitConstructionBench.time_circuit_extend(5, 2048)                                      |
| -        | 34.8±0.9ms                                 | 7.04±0.2ms                              |    0.2  | circuit_construction.CircuitConstructionBench.time_circuit_extend(5, 32768)                                     |
| -        | 21.0±0.9μs                                 | 13.0±0.3μs                              |    0.62 | circuit_construction.CircuitConstructionBench.time_circuit_extend(5, 8)                                         |
| -        | 7.92±0.3ms                                 | 1.77±0.06ms                             |    0.22 | circuit_construction.CircuitConstructionBench.time_circuit_extend(5, 8192)                                      |
| -        | 147±1μs                                    | 41.8±2μs                                |    0.28 | circuit_construction.CircuitConstructionBench.time_circuit_extend(8, 128)                                       |
| -        | 143±5ms                                    | 35.4±1ms                                |    0.25 | circuit_construction.CircuitConstructionBench.time_circuit_extend(8, 131072)                                    |
| -        | 1.88±0.1ms                                 | 446±30μs                                |    0.24 | circuit_construction.CircuitConstructionBench.time_circuit_extend(8, 2048)                                      |
| -        | 36.2±1ms                                   | 7.14±0.3ms                              |    0.2  | circuit_construction.CircuitConstructionBench.time_circuit_extend(8, 32768)                                     |
| -        | 28.8±0.4μs                                 | 16.0±0.5μs                              |    0.56 | circuit_construction.CircuitConstructionBench.time_circuit_extend(8, 8)                                         |
| -        | 7.82±0.3ms                                 | 1.74±0.07ms                             |    0.22 | circuit_construction.CircuitConstructionBench.time_circuit_extend(8, 8192)                                      |
| -        | 3.45±0.07ms                                | 2.61±0.02ms                             |    0.75 | circuit_construction.ParameterizedCircuitBindBench.time_bind_params(20, 128, 128)                               |
| -        | 3.30±0.2ms                                 | 2.69±0.02ms                             |    0.82 | circuit_construction.ParameterizedCircuitBindBench.time_bind_params(20, 128, 8)                                 |
| -        | 2.72±0.01s                                 | 2.13±0.03s                              |    0.78 | circuit_construction.ParameterizedCircuitBindBench.time_bind_params(20, 131072, 128)                            |
| -        | 3.17±0.05s                                 | 2.47±0.01s                              |    0.78 | circuit_construction.ParameterizedCircuitBindBench.time_bind_params(20, 131072, 131072)                         |
| -        | 2.72±0.03s                                 | 2.21±0.07s                              |    0.81 | circuit_construction.ParameterizedCircuitBindBench.time_bind_params(20, 131072, 2048)                           |
| -        | 2.87±0.02s                                 | 2.25±0.03s                              |    0.78 | circuit_construction.ParameterizedCircuitBindBench.time_bind_params(20, 131072, 32768)                          |
| -        | 2.78±0.05s                                 | 2.17±0.03s                              |    0.78 | circuit_construction.ParameterizedCircuitBindBench.time_bind_params(20, 131072, 8)                              |
| -        | 2.79±0.02s                                 | 2.14±0.01s                              |    0.77 | circuit_construction.ParameterizedCircuitBindBench.time_bind_params(20, 131072, 8192)                           |
| -        | 41.1±0.3ms                                 | 31.7±0.3ms                              |    0.77 | circuit_construction.ParameterizedCircuitBindBench.time_bind_params(20, 2048, 128)                              |
| -        | 44.7±1ms                                   | 35.3±0.2ms                              |    0.79 | circuit_construction.ParameterizedCircuitBindBench.time_bind_params(20, 2048, 2048)                             |
| -        | 41.4±2ms                                   | 33.7±2ms                                |    0.81 | circuit_construction.ParameterizedCircuitBindBench.time_bind_params(20, 2048, 8)                                |
| -        | 662±7ms                                    | 535±10ms                                |    0.81 | circuit_construction.ParameterizedCircuitBindBench.time_bind_params(20, 32768, 128)                             |
| -        | 691±10ms                                   | 522±10ms                                |    0.76 | circuit_construction.ParameterizedCircuitBindBench.time_bind_params(20, 32768, 2048)                            |
| -        | 757±30ms                                   | 594±9ms                                 |    0.79 | circuit_construction.ParameterizedCircuitBindBench.time_bind_params(20, 32768, 32768)                           |
| -        | 669±10ms                                   | 529±10ms                                |    0.79 | circuit_construction.ParameterizedCircuitBindBench.time_bind_params(20, 32768, 8)                               |
| -        | 662±10ms                                   | 516±8ms                                 |    0.78 | circuit_construction.ParameterizedCircuitBindBench.time_bind_params(20, 32768, 8192)                            |
| -        | 859±10μs                                   | 666±6μs                                 |    0.78 | circuit_construction.ParameterizedCircuitBindBench.time_bind_params(20, 8, 8)                                   |
| -        | 177±2ms                                    | 134±1ms                                 |    0.76 | circuit_construction.ParameterizedCircuitBindBench.time_bind_params(20, 8192, 2048)                             |
| -        | 167±2ms                                    | 128±1ms                                 |    0.77 | circuit_construction.ParameterizedCircuitBindBench.time_bind_params(20, 8192, 8)                                |
| -        | 185±4ms                                    | 148±3ms                                 |    0.8  | circuit_construction.ParameterizedCircuitBindBench.time_bind_params(20, 8192, 8192)                             |
| -        | 2.04±0.05ms                                | 1.77±0.02ms                             |    0.86 | circuit_construction.ParameterizedCircuitConstructionBench.time_build_parameterized_circuit(20, 128, 128)       |
| -        | 1.53±0.02ms                                | 648±7μs                                 |    0.42 | converters.ConverterBenchmarks.time_circuit_to_dag(1, 128)                                                      |
| -        | 23.7±1ms                                   | 8.50±0.2ms                              |    0.36 | converters.ConverterBenchmarks.time_circuit_to_dag(1, 2048)                                                     |
| -        | 148±5μs                                    | 59.2±0.7μs                              |    0.4  | converters.ConverterBenchmarks.time_circuit_to_dag(1, 8)                                                        |
| -        | 97.7±5ms                                   | 35.3±2ms                                |    0.36 | converters.ConverterBenchmarks.time_circuit_to_dag(1, 8192)                                                     |
| -        | 13.7±0.4ms                                 | 6.46±0.2ms                              |    0.47 | converters.ConverterBenchmarks.time_circuit_to_dag(14, 128)                                                     |
| -        | 204±5ms                                    | 95.0±3ms                                |    0.47 | converters.ConverterBenchmarks.time_circuit_to_dag(14, 2048)                                                    |
| -        | 1.15±0.01ms                                | 667±9μs                                 |    0.58 | converters.ConverterBenchmarks.time_circuit_to_dag(14, 8)                                                       |
| -        | 2.39±0.03ms                                | 1.11±0.02ms                             |    0.46 | converters.ConverterBenchmarks.time_circuit_to_dag(2, 128)                                                      |
| -        | 37.9±2ms                                   | 15.2±0.2ms                              |    0.4  | converters.ConverterBenchmarks.time_circuit_to_dag(2, 2048)                                                     |
| -        | 238±9μs                                    | 119±2μs                                 |    0.5  | converters.ConverterBenchmarks.time_circuit_to_dag(2, 8)                                                        |
| -        | 155±4ms                                    | 59.9±1ms                                |    0.39 | converters.ConverterBenchmarks.time_circuit_to_dag(2, 8192)                                                     |
| -        | 19.7±0.3ms                                 | 10.9±1ms                                |    0.55 | converters.ConverterBenchmarks.time_circuit_to_dag(20, 128)                                                     |
| -        | 1.82±0.06ms                                | 1.03±0.01ms                             |    0.57 | converters.ConverterBenchmarks.time_circuit_to_dag(20, 8)                                                       |
| -        | 33.2±0.6ms                                 | 16.9±2ms                                |    0.51 | converters.ConverterBenchmarks.time_circuit_to_dag(32, 128)                                                     |
| -        | 2.62±0.1ms                                 | 1.53±0.06ms                             |    0.58 | converters.ConverterBenchmarks.time_circuit_to_dag(32, 8)                                                       |
| -        | 5.27±0.7ms                                 | 2.27±0.03ms                             |    0.43 | converters.ConverterBenchmarks.time_circuit_to_dag(5, 128)                                                      |
| -        | 74.9±0.7ms                                 | 32.0±0.9ms                              |    0.43 | converters.ConverterBenchmarks.time_circuit_to_dag(5, 2048)                                                     |
| -        | 455±4μs                                    | 218±10μs                                |    0.48 | converters.ConverterBenchmarks.time_circuit_to_dag(5, 8)                                                        |
| -        | 296±2ms                                    | 125±2ms                                 |    0.42 | converters.ConverterBenchmarks.time_circuit_to_dag(5, 8192)                                                     |
| -        | 58.3±0.8ms                                 | 33.2±1ms                                |    0.57 | converters.ConverterBenchmarks.time_circuit_to_dag(53, 128)                                                     |
| -        | 4.66±0.05ms                                | 3.08±0.3ms                              |    0.66 | converters.ConverterBenchmarks.time_circuit_to_dag(53, 8)                                                       |
| -        | 7.87±0.1ms                                 | 3.64±0.04ms                             |    0.46 | converters.ConverterBenchmarks.time_circuit_to_dag(8, 128)                                                      |
| -        | 117±5ms                                    | 49.6±0.4ms                              |    0.42 | converters.ConverterBenchmarks.time_circuit_to_dag(8, 2048)                                                     |
| -        | 725±70μs                                   | 364±5μs                                 |    0.5  | converters.ConverterBenchmarks.time_circuit_to_dag(8, 8)                                                        |
| -        | 468±4ms                                    | 193±1ms                                 |    0.41 | converters.ConverterBenchmarks.time_circuit_to_dag(8, 8192)                                                     |
| -        | 928±20μs                                   | 240±3μs                                 |    0.26 | converters.ConverterBenchmarks.time_circuit_to_instruction(1, 128)                                              |
| -        | 13.7±0.7ms                                 | 2.26±0.06ms                             |    0.17 | converters.ConverterBenchmarks.time_circuit_to_instruction(1, 2048)                                             |
| -        | 141±3μs                                    | 73.0±3μs                                |    0.52 | converters.ConverterBenchmarks.time_circuit_to_instruction(1, 8)                                                |
| -        | 53.0±2ms                                   | 8.84±0.1ms                              |    0.17 | converters.ConverterBenchmarks.time_circuit_to_instruction(1, 8192)                                             |
| -        | 6.60±0.4ms                                 | 1.58±0.03ms                             |    0.24 | converters.ConverterBenchmarks.time_circuit_to_instruction(14, 128)                                             |
| -        | 98.5±1ms                                   | 24.0±0.3ms                              |    0.24 | converters.ConverterBenchmarks.time_circuit_to_instruction(14, 2048)                                            |
| -        | 623±10μs                                   | 315±3μs                                 |    0.51 | converters.ConverterBenchmarks.time_circuit_to_instruction(14, 8)                                               |
| -        | 1.39±0.01ms                                | 555±20μs                                |    0.4  | converters.ConverterBenchmarks.time_circuit_to_instruction(2, 128)                                              |
| -        | 20.7±0.9ms                                 | 4.89±0.07ms                             |    0.24 | converters.ConverterBenchmarks.time_circuit_to_instruction(2, 2048)                                             |
| -        | 186±5μs                                    | 114±9μs                                 |    0.61 | converters.ConverterBenchmarks.time_circuit_to_instruction(2, 8)                                                |
| -        | 81.9±2ms                                   | 19.0±0.5ms                              |    0.23 | converters.ConverterBenchmarks.time_circuit_to_instruction(2, 8192)                                             |
| -        | 8.88±0.2ms                                 | 2.35±0.1ms                              |    0.26 | converters.ConverterBenchmarks.time_circuit_to_instruction(20, 128)                                             |
| -        | 817±10μs                                   | 392±7μs                                 |    0.48 | converters.ConverterBenchmarks.time_circuit_to_instruction(20, 8)                                               |
| -        | 13.6±0.1ms                                 | 3.57±0.3ms                              |    0.26 | converters.ConverterBenchmarks.time_circuit_to_instruction(32, 128)                                             |
| -        | 1.28±0.02ms                                | 550±10μs                                |    0.43 | converters.ConverterBenchmarks.time_circuit_to_instruction(32, 8)                                               |
| -        | 2.62±0.3ms                                 | 793±50μs                                |    0.3  | converters.ConverterBenchmarks.time_circuit_to_instruction(5, 128)                                              |
| -        | 38.5±1ms                                   | 8.82±0.06ms                             |    0.23 | converters.ConverterBenchmarks.time_circuit_to_instruction(5, 2048)                                             |
| -        | 294±3μs                                    | 125±3μs                                 |    0.43 | converters.ConverterBenchmarks.time_circuit_to_instruction(5, 8)                                                |
| -        | 155±3ms                                    | 36.6±0.7ms                              |    0.24 | converters.ConverterBenchmarks.time_circuit_to_instruction(5, 8192)                                             |
| -        | 22.9±0.7ms                                 | 5.82±0.2ms                              |    0.25 | converters.ConverterBenchmarks.time_circuit_to_instruction(53, 128)                                             |
| -        | 2.06±0.06ms                                | 922±100μs                               |    0.45 | converters.ConverterBenchmarks.time_circuit_to_instruction(53, 8)                                               |
| -        | 3.90±0.09ms                                | 1.09±0.09ms                             |    0.28 | converters.ConverterBenchmarks.time_circuit_to_instruction(8, 128)                                              |
| -        | 57.9±1ms                                   | 13.6±0.2ms                              |    0.23 | converters.ConverterBenchmarks.time_circuit_to_instruction(8, 2048)                                             |
| -        | 422±20μs                                   | 191±5μs                                 |    0.45 | converters.ConverterBenchmarks.time_circuit_to_instruction(8, 8)                                                |
| -        | 232±4ms                                    | 55.3±1ms                                |    0.24 | converters.ConverterBenchmarks.time_circuit_to_instruction(8, 8192)                                             |
| -        | 446±4μs                                    | 243±0.9μs                               |    0.55 | converters.ConverterBenchmarks.time_dag_to_circuit(1, 128)                                                      |
| -        | 6.18±0.09ms                                | 3.25±0.05ms                             |    0.53 | converters.ConverterBenchmarks.time_dag_to_circuit(1, 2048)                                                     |
| -        | 60.5±3μs                                   | 37.6±0.4μs                              |    0.62 | converters.ConverterBenchmarks.time_dag_to_circuit(1, 8)                                                        |
| -        | 25.0±0.6ms                                 | 13.1±0.2ms                              |    0.53 | converters.ConverterBenchmarks.time_dag_to_circuit(1, 8192)                                                     |
| -        | 3.83±0.05ms                                | 2.10±0.05ms                             |    0.55 | converters.ConverterBenchmarks.time_dag_to_circuit(14, 128)                                                     |
| -        | 62.1±1ms                                   | 33.5±0.8ms                              |    0.54 | converters.ConverterBenchmarks.time_dag_to_circuit(14, 2048)                                                    |
| -        | 439±20μs                                   | 247±7μs                                 |    0.56 | converters.ConverterBenchmarks.time_dag_to_circuit(14, 8)                                                       |
| -        | 802±20μs                                   | 450±20μs                                |    0.56 | converters.ConverterBenchmarks.time_dag_to_circuit(2, 128)                                                      |
| -        | 11.3±0.4ms                                 | 5.88±0.08ms                             |    0.52 | converters.ConverterBenchmarks.time_dag_to_circuit(2, 2048)                                                     |
| -        | 86.2±3μs                                   | 57.7±1μs                                |    0.67 | converters.ConverterBenchmarks.time_dag_to_circuit(2, 8)                                                        |
| -        | 47.3±1ms                                   | 23.5±0.7ms                              |    0.5  | converters.ConverterBenchmarks.time_dag_to_circuit(2, 8192)                                                     |
| -        | 5.52±0.1ms                                 | 2.99±0.06ms                             |    0.54 | converters.ConverterBenchmarks.time_dag_to_circuit(20, 128)                                                     |
| -        | 557±6μs                                    | 323±3μs                                 |    0.58 | converters.ConverterBenchmarks.time_dag_to_circuit(20, 8)                                                       |
| -        | 8.64±0.2ms                                 | 4.81±0.2ms                              |    0.56 | converters.ConverterBenchmarks.time_dag_to_circuit(32, 128)                                                     |
| -        | 959±40μs                                   | 539±20μs                                |    0.56 | converters.ConverterBenchmarks.time_dag_to_circuit(32, 8)                                                       |
| -        | 1.51±0.06ms                                | 799±40μs                                |    0.53 | converters.ConverterBenchmarks.time_dag_to_circuit(5, 128)                                                      |
| -        | 22.6±0.5ms                                 | 12.2±0.2ms                              |    0.54 | converters.ConverterBenchmarks.time_dag_to_circuit(5, 2048)                                                     |
| -        | 167±0.8μs                                  | 107±6μs                                 |    0.64 | converters.ConverterBenchmarks.time_dag_to_circuit(5, 8)                                                        |
| -        | 92.8±2ms                                   | 50.6±1ms                                |    0.55 | converters.ConverterBenchmarks.time_dag_to_circuit(5, 8192)                                                     |
| -        | 15.0±0.3ms                                 | 8.46±0.2ms                              |    0.56 | converters.ConverterBenchmarks.time_dag_to_circuit(53, 128)                                                     |
| -        | 1.55±0.01ms                                | 873±10μs                                |    0.56 | converters.ConverterBenchmarks.time_dag_to_circuit(53, 8)                                                       |
| -        | 2.31±0.07ms                                | 1.35±0.05ms                             |    0.59 | converters.ConverterBenchmarks.time_dag_to_circuit(8, 128)                                                      |
| -        | 35.1±2ms                                   | 18.8±0.2ms                              |    0.54 | converters.ConverterBenchmarks.time_dag_to_circuit(8, 2048)                                                     |
| -        | 267±3μs                                    | 153±1μs                                 |    0.57 | converters.ConverterBenchmarks.time_dag_to_circuit(8, 8)                                                        |
| -        | 142±8ms                                    | 79.4±4ms                                |    0.56 | converters.ConverterBenchmarks.time_dag_to_circuit(8, 8192)                                                     |
| -        | 138±2ms                                    | 71.8±1ms                                |    0.52 | mapping_passes.PassBenchmarks.time_apply_layout(14, 1024)                                                       |
| -        | 204±3ms                                    | 109±0.7ms                               |    0.53 | mapping_passes.PassBenchmarks.time_apply_layout(20, 1024)                                                       |
| -        | 49.7±2ms                                   | 25.2±0.2ms                              |    0.51 | mapping_passes.PassBenchmarks.time_apply_layout(5, 1024)                                                        |
| -        | 3.80±0.04s                                 | 3.42±0.01s                              |    0.9  | mapping_passes.PassBenchmarks.time_basic_swap(14, 1024)                                                         |
| -        | 22.4±0.5ms                                 | 2.04±0.03ms                             |    0.09 | mapping_passes.PassBenchmarks.time_check_map(14, 1024)                                                          |
| -        | 30.8±0.2ms                                 | 3.01±0.1ms                              |    0.1  | mapping_passes.PassBenchmarks.time_check_map(20, 1024)                                                          |
| -        | 8.23±0.3ms                                 | 774±20μs                                |    0.09 | mapping_passes.PassBenchmarks.time_check_map(5, 1024)                                                           |
| -        | 42.6±1ms                                   | 23.1±0.4ms                              |    0.54 | mapping_passes.PassBenchmarks.time_csp_layout(14, 1024)                                                         |
| -        | 66.7±0.7ms                                 | 40.0±0.5ms                              |    0.6  | mapping_passes.PassBenchmarks.time_csp_layout(20, 1024)                                                         |
| -        | 13.3±0.2ms                                 | 5.86±0.4ms                              |    0.44 | mapping_passes.PassBenchmarks.time_csp_layout(5, 1024)                                                          |
| -        | 24.4±0.4ms                                 | 5.15±0.1ms                              |    0.21 | mapping_passes.PassBenchmarks.time_layout_2q_distance(14, 1024)                                                 |
| -        | 35.5±1ms                                   | 7.63±0.2ms                              |    0.22 | mapping_passes.PassBenchmarks.time_layout_2q_distance(20, 1024)                                                 |
| -        | 9.28±0.2ms                                 | 1.81±0.05ms                             |    0.19 | mapping_passes.PassBenchmarks.time_layout_2q_distance(5, 1024)                                                  |
| -        | 582±10ms                                   | 343±10ms                                |    0.59 | mapping_passes.PassBenchmarks.time_sabre_layout(14, 1024)                                                       |
| -        | 943±10ms                                   | 573±6ms                                 |    0.61 | mapping_passes.PassBenchmarks.time_sabre_layout(20, 1024)                                                       |
| -        | 169±2ms                                    | 83.2±3ms                                |    0.49 | mapping_passes.PassBenchmarks.time_sabre_layout(5, 1024)                                                        |
| -        | 374±2ms                                    | 160±4ms                                 |    0.43 | mapping_passes.PassBenchmarks.time_sabre_swap(14, 1024)                                                         |
| -        | 584±10ms                                   | 266±5ms                                 |    0.45 | mapping_passes.PassBenchmarks.time_sabre_swap(20, 1024)                                                         |
| -        | 127±3ms                                    | 47.5±1ms                                |    0.37 | mapping_passes.PassBenchmarks.time_sabre_swap(5, 1024)                                                          |
| -        | 2.65±0s                                    | 2.29±0.03s                              |    0.87 | mapping_passes.PassBenchmarks.time_stochastic_swap(14, 1024)                                                    |
| -        | 3.85±0.03s                                 | 3.31±0.01s                              |    0.86 | mapping_passes.PassBenchmarks.time_stochastic_swap(20, 1024)                                                    |
| -        | 782±10ms                                   | 670±3ms                                 |    0.86 | mapping_passes.PassBenchmarks.time_stochastic_swap(5, 1024)                                                     |
| -        | 57.4±2ms                                   | 27.4±0.5ms                              |    0.48 | mapping_passes.RoutedPassBenchmarks.time_check_gate_direction(14, 1024)                                         |
| -        | 95.9±0.4ms                                 | 56.2±0.6ms                              |    0.59 | mapping_passes.RoutedPassBenchmarks.time_check_gate_direction(20, 1024)                                         |
| -        | 14.5±0.1ms                                 | 5.27±0.09ms                             |    0.36 | mapping_passes.RoutedPassBenchmarks.time_check_gate_direction(5, 1024)                                          |
| -        | 77.1±2ms                                   | 19.6±0.2ms                              |    0.25 | mapping_passes.RoutedPassBenchmarks.time_check_map(14, 1024)                                                    |
| -        | 132±5ms                                    | 35.3±1ms                                |    0.27 | mapping_passes.RoutedPassBenchmarks.time_check_map(20, 1024)                                                    |
| -        | 22.9±0.2ms                                 | 4.48±0.06ms                             |    0.2  | mapping_passes.RoutedPassBenchmarks.time_check_map(5, 1024)                                                     |
| -        | 82.1±3ms                                   | 19.9±0.2ms                              |    0.24 | mapping_passes.RoutedPassBenchmarks.time_gate_direction(14, 1024)                                               |
| -        | 125±0.4ms                                  | 34.2±0.3ms                              |    0.27 | mapping_passes.RoutedPassBenchmarks.time_gate_direction(20, 1024)                                               |
| -        | 23.2±0.2ms                                 | 4.83±0.05ms                             |    0.21 | mapping_passes.RoutedPassBenchmarks.time_gate_direction(5, 1024)                                                |
| -        | 107±3ms                                    | 54.2±2ms                                |    0.51 | passes.Collect2QPassBenchmarks.time_consolidate_blocks(14, 1024)                                                |
| -        | 154±5ms                                    | 76.7±2ms                                |    0.5  | passes.Collect2QPassBenchmarks.time_consolidate_blocks(20, 1024)                                                |
| -        | 42.7±0.2ms                                 | 20.3±0.1ms                              |    0.47 | passes.Collect2QPassBenchmarks.time_consolidate_blocks(5, 1024)                                                 |
| -        | 133±3ms                                    | 61.5±2ms                                |    0.46 | passes.MultiQBlockPassBenchmarks.time_collect_multiq_block(14, 1024, 1)                                         |
| -        | 137±1ms                                    | 66.9±2ms                                |    0.49 | passes.MultiQBlockPassBenchmarks.time_collect_multiq_block(14, 1024, 2)                                         |
| -        | 144±5ms                                    | 66.6±0.4ms                              |    0.46 | passes.MultiQBlockPassBenchmarks.time_collect_multiq_block(14, 1024, 3)                                         |
| -        | 138±2ms                                    | 66.8±1ms                                |    0.48 | passes.MultiQBlockPassBenchmarks.time_collect_multiq_block(14, 1024, 4)                                         |
| -        | 139±1ms                                    | 64.7±0.5ms                              |    0.47 | passes.MultiQBlockPassBenchmarks.time_collect_multiq_block(14, 1024, 5)                                         |
| -        | 194±2ms                                    | 88.5±1ms                                |    0.46 | passes.MultiQBlockPassBenchmarks.time_collect_multiq_block(20, 1024, 1)                                         |
| -        | 195±1ms                                    | 92.5±0.9ms                              |    0.47 | passes.MultiQBlockPassBenchmarks.time_collect_multiq_block(20, 1024, 2)                                         |
| -        | 204±4ms                                    | 101±6ms                                 |    0.5  | passes.MultiQBlockPassBenchmarks.time_collect_multiq_block(20, 1024, 3)                                         |
| -        | 199±6ms                                    | 94.4±2ms                                |    0.47 | passes.MultiQBlockPassBenchmarks.time_collect_multiq_block(20, 1024, 4)                                         |
| -        | 212±8ms                                    | 93.6±2ms                                |    0.44 | passes.MultiQBlockPassBenchmarks.time_collect_multiq_block(20, 1024, 5)                                         |
| -        | 57.5±4ms                                   | 22.4±0.2ms                              |    0.39 | passes.MultiQBlockPassBenchmarks.time_collect_multiq_block(5, 1024, 1)                                          |
| -        | 52.5±1ms                                   | 23.3±0.2ms                              |    0.44 | passes.MultiQBlockPassBenchmarks.time_collect_multiq_block(5, 1024, 2)                                          |
| -        | 54.1±0.6ms                                 | 23.6±0.2ms                              |    0.44 | passes.MultiQBlockPassBenchmarks.time_collect_multiq_block(5, 1024, 3)                                          |
| -        | 51.8±0.4ms                                 | 22.9±0.2ms                              |    0.44 | passes.MultiQBlockPassBenchmarks.time_collect_multiq_block(5, 1024, 4)                                          |
| -        | 49.8±0.6ms                                 | 21.3±0.4ms                              |    0.43 | passes.MultiQBlockPassBenchmarks.time_collect_multiq_block(5, 1024, 5)                                          |
| -        | 3.11±0.04s                                 | 1.25±0.01s                              |    0.4  | passes.MultipleBasisPassBenchmarks.time_basis_translator(14, 1024, ['rx', 'ry', 'rz', 'r', 'rxx', 'id'])        |
| -        | 1.81±0.04s                                 | 856±9ms                                 |    0.47 | passes.MultipleBasisPassBenchmarks.time_basis_translator(14, 1024, ['rz', 'x', 'sx', 'cx', 'id'])               |
| -        | 1.51±0.02s                                 | 725±10ms                                |    0.48 | passes.MultipleBasisPassBenchmarks.time_basis_translator(14, 1024, ['u', 'cx', 'id'])                           |
| -        | 4.39±0.02s                                 | 1.77±0.03s                              |    0.4  | passes.MultipleBasisPassBenchmarks.time_basis_translator(20, 1024, ['rx', 'ry', 'rz', 'r', 'rxx', 'id'])        |
| -        | 2.53±0.03s                                 | 1.18±0.02s                              |    0.47 | passes.MultipleBasisPassBenchmarks.time_basis_translator(20, 1024, ['rz', 'x', 'sx', 'cx', 'id'])               |
| -        | 2.22±0.06s                                 | 1.03±0.01s                              |    0.46 | passes.MultipleBasisPassBenchmarks.time_basis_translator(20, 1024, ['u', 'cx', 'id'])                           |
| -        | 1.02±0.03s                                 | 430±4ms                                 |    0.42 | passes.MultipleBasisPassBenchmarks.time_basis_translator(5, 1024, ['rx', 'ry', 'rz', 'r', 'rxx', 'id'])         |
| -        | 650±5ms                                    | 328±10ms                                |    0.5  | passes.MultipleBasisPassBenchmarks.time_basis_translator(5, 1024, ['rz', 'x', 'sx', 'cx', 'id'])                |
| -        | 548±10ms                                   | 267±2ms                                 |    0.49 | passes.MultipleBasisPassBenchmarks.time_basis_translator(5, 1024, ['u', 'cx', 'id'])                            |
| -        | 885±10ms                                   | 798±6ms                                 |    0.9  | passes.MultipleBasisPassBenchmarks.time_optimize_1q_commutation(14, 1024, ['rx', 'ry', 'rz', 'r', 'rxx', 'id']) |
| -        | 864±9ms                                    | 779±5ms                                 |    0.9  | passes.MultipleBasisPassBenchmarks.time_optimize_1q_commutation(14, 1024, ['u', 'cx', 'id'])                    |
| -        | 1.39±0.02s                                 | 1.25±0.02s                              |    0.89 | passes.MultipleBasisPassBenchmarks.time_optimize_1q_commutation(20, 1024, ['rx', 'ry', 'rz', 'r', 'rxx', 'id']) |
| -        | 1.53±0.03s                                 | 1.35±0.02s                              |    0.88 | passes.MultipleBasisPassBenchmarks.time_optimize_1q_commutation(20, 1024, ['rz', 'x', 'sx', 'cx', 'id'])        |
| -        | 1.38±0.02s                                 | 1.25±0.03s                              |    0.9  | passes.MultipleBasisPassBenchmarks.time_optimize_1q_commutation(20, 1024, ['u', 'cx', 'id'])                    |
| -        | 315±4ms                                    | 273±3ms                                 |    0.87 | passes.MultipleBasisPassBenchmarks.time_optimize_1q_commutation(5, 1024, ['rx', 'ry', 'rz', 'r', 'rxx', 'id'])  |
| -        | 372±10ms                                   | 301±10ms                                |    0.81 | passes.MultipleBasisPassBenchmarks.time_optimize_1q_commutation(5, 1024, ['rz', 'x', 'sx', 'cx', 'id'])         |
| -        | 39.8±0.9ms                                 | 27.3±0.4ms                              |    0.68 | passes.MultipleBasisPassBenchmarks.time_optimize_1q_decompose(14, 1024, ['u', 'cx', 'id'])                      |
| -        | 17.4±0.3ms                                 | 12.2±0.1ms                              |    0.7  | passes.MultipleBasisPassBenchmarks.time_optimize_1q_decompose(5, 1024, ['rx', 'ry', 'rz', 'r', 'rxx', 'id'])    |
| -        | 20.7±0.8ms                                 | 10.6±0.06ms                             |    0.51 | passes.MultipleBasisPassBenchmarks.time_optimize_1q_decompose(5, 1024, ['rz', 'x', 'sx', 'cx', 'id'])           |
| -        | 10.1±0.3ms                                 | 7.84±0.2ms                              |    0.78 | passes.PassBenchmarks.time_barrier_before_final_measurements(5, 1024)                                           |
| -        | 48.4±1ms                                   | 27.0±0.2ms                              |    0.56 | passes.PassBenchmarks.time_collect_2q_blocks(14, 1024)                                                          |
| -        | 69.3±0.3ms                                 | 40.8±0.7ms                              |    0.59 | passes.PassBenchmarks.time_collect_2q_blocks(20, 1024)                                                          |
| -        | 20.9±0.3ms                                 | 6.57±0.4ms                              |    0.31 | passes.PassBenchmarks.time_collect_2q_blocks(5, 1024)                                                           |
| -        | 3.83±0.1ms                                 | 1.89±0.1ms                              |    0.49 | passes.PassBenchmarks.time_count_ops_longest_path(14, 1024)                                                     |
| -        | 5.11±0.3ms                                 | 2.78±0.09ms                             |    0.54 | passes.PassBenchmarks.time_count_ops_longest_path(20, 1024)                                                     |
| -        | 2.78±0.06ms                                | 933±40μs                                |    0.34 | passes.PassBenchmarks.time_count_ops_longest_path(5, 1024)                                                      |
| -        | 18.8±0.7ms                                 | 6.48±0.2ms                              |    0.34 | passes.PassBenchmarks.time_cx_cancellation(14, 1024)                                                            |
| -        | 26.9±0.5ms                                 | 11.5±0.6ms                              |    0.43 | passes.PassBenchmarks.time_cx_cancellation(20, 1024)                                                            |
| -        | 7.34±0.1ms                                 | 1.79±0.06ms                             |    0.24 | passes.PassBenchmarks.time_cx_cancellation(5, 1024)                                                             |
| -        | 1.56±0.02s                                 | 1.04±0.03s                              |    0.67 | passes.PassBenchmarks.time_decompose_pass(14, 1024)                                                             |
| -        | 2.39±0.04s                                 | 1.62±0.02s                              |    0.68 | passes.PassBenchmarks.time_decompose_pass(20, 1024)                                                             |
| -        | 533±10ms                                   | 335±10ms                                |    0.63 | passes.PassBenchmarks.time_decompose_pass(5, 1024)                                                              |
| -        | 2.46±0.05s                                 | 611±7ms                                 |    0.25 | passes.PassBenchmarks.time_optimize_swap_before_measure(14, 1024)                                               |
| -        | 4.48±0.09s                                 | 1.10±0.02s                              |    0.24 | passes.PassBenchmarks.time_optimize_swap_before_measure(20, 1024)                                               |
| -        | 359±10ms                                   | 90.2±2ms                                |    0.25 | passes.PassBenchmarks.time_optimize_swap_before_measure(5, 1024)                                                |
| -        | 30.6±0.7ms                                 | 8.07±0.07ms                             |    0.26 | passes.PassBenchmarks.time_remove_barriers(14, 1024)                                                            |
| -        | 44.6±0.3ms                                 | 15.2±0.9ms                              |    0.34 | passes.PassBenchmarks.time_remove_barriers(20, 1024)                                                            |
| -        | 12.8±0.5ms                                 | 2.28±0.02ms                             |    0.18 | passes.PassBenchmarks.time_remove_barriers(5, 1024)                                                             |
| -        | 31.6±0.3ms                                 | 8.74±0.2ms                              |    0.28 | passes.PassBenchmarks.time_remove_diagonal_gates_before_measurement(14, 1024)                                   |
| -        | 47.7±3ms                                   | 15.8±0.5ms                              |    0.33 | passes.PassBenchmarks.time_remove_diagonal_gates_before_measurement(20, 1024)                                   |
| -        | 13.8±0.4ms                                 | 2.74±0.06ms                             |    0.2  | passes.PassBenchmarks.time_remove_diagonal_gates_before_measurement(5, 1024)                                    |
| -        | 56.7±2μs                                   | 28.1±0.3μs                              |    0.5  | passes.PassBenchmarks.time_remove_final_measurements(14, 1024)                                                  |
| -        | 107±5μs                                    | 34.1±1μs                                |    0.32 | passes.PassBenchmarks.time_remove_final_measurements(20, 1024)                                                  |
| -        | 26.8±0.9μs                                 | 17.9±0.6μs                              |    0.67 | passes.PassBenchmarks.time_remove_final_measurements(5, 1024)                                                   |
| -        | 16.4±0.3ms                                 | 5.06±0.2ms                              |    0.31 | passes.PassBenchmarks.time_remove_reset_in_zero_state(14, 1024)                                                 |
| -        | 23.7±1ms                                   | 9.55±0.1ms                              |    0.4  | passes.PassBenchmarks.time_remove_reset_in_zero_state(20, 1024)                                                 |
| -        | 6.85±0.2ms                                 | 1.43±0.01ms                             |    0.21 | passes.PassBenchmarks.time_remove_reset_in_zero_state(5, 1024)                                                  |
| -        | 1.38±0.02s                                 | 928±10ms                                |    0.67 | passes.PassBenchmarks.time_unroll_3q_or_more(14, 1024)                                                          |
| -        | 2.14±0.01s                                 | 1.43±0.01s                              |    0.67 | passes.PassBenchmarks.time_unroll_3q_or_more(20, 1024)                                                          |
| -        | 375±5ms                                    | 249±4ms                                 |    0.66 | passes.PassBenchmarks.time_unroll_3q_or_more(5, 1024)                                                           |
| -        | 1.26±0m                                    | 42.4±0.2s                               |    0.56 | qft.LargeQFTMappingTimeBench.time_sabre_swap(1081, 'decay')                                                     |
| -        | 729±10ms                                   | 209±2ms                                 |    0.29 | qft.LargeQFTMappingTimeBench.time_sabre_swap(115, 'decay')                                                      |
| -        | 731±8ms                                    | 214±4ms                                 |    0.29 | qft.LargeQFTMappingTimeBench.time_sabre_swap(115, 'lookahead')                                                  |
| -        | 117±2ms                                    | 50.6±1ms                                |    0.43 | qft.QftTranspileBench.time_ibmq_backend_transpile(13)                                                           |
| -        | 148±3ms                                    | 63.5±0.9ms                              |    0.43 | qft.QftTranspileBench.time_ibmq_backend_transpile(14)                                                           |
| -        | 15.0±0.08ms                                | 10.5±0.1ms                              |    0.7  | qft.QftTranspileBench.time_ibmq_backend_transpile(3)                                                            |
| -        | 25.1±1ms                                   | 14.1±0.2ms                              |    0.56 | qft.QftTranspileBench.time_ibmq_backend_transpile(5)                                                            |
| -        | 48.5±0.9ms                                 | 23.7±0.4ms                              |    0.49 | qft.QftTranspileBench.time_ibmq_backend_transpile(8)                                                            |
| -        | 949±20ms                                   | 780±10ms                                |    0.82 | quantum_info.CliffordDecomposeBench.time_decompose('2,500')                                                     |
| -        | 2.75±0.05s                                 | 2.23±0.01s                              |    0.81 | quantum_volume.LargeQuantumVolumeMappingTimeBench.time_sabre_swap(1081, 10, 'lookahead')                        |
| -        | 47.6±0.5ms                                 | 35.1±1ms                                |    0.74 | quantum_volume.LargeQuantumVolumeMappingTimeBench.time_sabre_swap(115, 10, 'decay')                             |
| -        | 49.8±1ms                                   | 35.4±2ms                                |    0.71 | quantum_volume.LargeQuantumVolumeMappingTimeBench.time_sabre_swap(115, 10, 'lookahead')                         |
| -        | 457±10ms                                   | 312±4ms                                 |    0.68 | quantum_volume.LargeQuantumVolumeMappingTimeBench.time_sabre_swap(115, 100, 'decay')                            |
| -        | 444±10ms                                   | 301±4ms                                 |    0.68 | quantum_volume.LargeQuantumVolumeMappingTimeBench.time_sabre_swap(115, 100, 'lookahead')                        |
| -        | 581±3ms                                    | 431±6ms                                 |    0.74 | quantum_volume.LargeQuantumVolumeMappingTimeBench.time_sabre_swap(409, 10, 'decay')                             |
| -        | 1.05±0.01s                                 | 828±10ms                                |    0.79 | quantum_volume.LargeQuantumVolumeMappingTimeBench.time_sabre_swap(409, 10, 'lookahead')                         |
| -        | 320±10ms                                   | 129±5ms                                 |    0.4  | quantum_volume.QuantumVolumeBenchmark.time_ibmq_backend_transpile(14, 'synthesis')                              |
| -        | 282±7ms                                    | 90.9±0.7ms                              |    0.32 | quantum_volume.QuantumVolumeBenchmark.time_ibmq_backend_transpile(14, 'translator')                             |
| -        | 10.2±0.2ms                                 | 6.86±0.1ms                              |    0.67 | quantum_volume.QuantumVolumeBenchmark.time_ibmq_backend_transpile(2, 'translator')                              |
| -        | 777±10ms                                   | 295±10ms                                |    0.38 | quantum_volume.QuantumVolumeBenchmark.time_ibmq_backend_transpile(20, 'synthesis')                              |
| -        | 574±10ms                                   | 187±6ms                                 |    0.33 | quantum_volume.QuantumVolumeBenchmark.time_ibmq_backend_transpile(20, 'translator')                             |
| -        | 1.57±0.01s                                 | 584±20ms                                |    0.37 | quantum_volume.QuantumVolumeBenchmark.time_ibmq_backend_transpile(27, 'synthesis')                              |
| -        | 1.05±0.02s                                 | 330±4ms                                 |    0.31 | quantum_volume.QuantumVolumeBenchmark.time_ibmq_backend_transpile(27, 'translator')                             |
| -        | 14.0±0.1ms                                 | 9.06±0.8ms                              |    0.65 | quantum_volume.QuantumVolumeBenchmark.time_ibmq_backend_transpile(3, 'translator')                              |
| -        | 30.0±2ms                                   | 15.9±1ms                                |    0.53 | quantum_volume.QuantumVolumeBenchmark.time_ibmq_backend_transpile(5, 'synthesis')                               |
| -        | 32.4±0.8ms                                 | 15.8±1ms                                |    0.49 | quantum_volume.QuantumVolumeBenchmark.time_ibmq_backend_transpile(5, 'translator')                              |
| -        | 90.0±7ms                                   | 38.3±0.6ms                              |    0.43 | quantum_volume.QuantumVolumeBenchmark.time_ibmq_backend_transpile(8, 'synthesis')                               |
| -        | 89.7±2ms                                   | 32.5±0.7ms                              |    0.36 | quantum_volume.QuantumVolumeBenchmark.time_ibmq_backend_transpile(8, 'translator')                              |
| -        | 37.6±1ms                                   | 24.0±0.6ms                              |    0.64 | queko.QUEKOTranspilerBench.time_transpile_bigd(0, 'sabre')                                                      |
| -        | 63.7±0.6ms                                 | 44.7±0.7ms                              |    0.7  | queko.QUEKOTranspilerBench.time_transpile_bigd(0, None)                                                         |
| -        | 19.3±1ms                                   | 11.7±0.3ms                              |    0.61 | queko.QUEKOTranspilerBench.time_transpile_bigd(1, 'sabre')                                                      |
| -        | 42.4±0.9ms                                 | 32.6±0.3ms                              |    0.77 | queko.QUEKOTranspilerBench.time_transpile_bigd(2, 'sabre')                                                      |
| -        | 33.2±1ms                                   | 26.0±0.3ms                              |    0.78 | queko.QUEKOTranspilerBench.time_transpile_bigd(2, None)                                                         |
| -        | 64.4±1ms                                   | 41.3±0.7ms                              |    0.64 | queko.QUEKOTranspilerBench.time_transpile_bigd(3, 'sabre')                                                      |
| -        | 363±7ms                                    | 192±4ms                                 |    0.53 | queko.QUEKOTranspilerBench.time_transpile_bntf(0, 'sabre')                                                      |
| -        | 822±20ms                                   | 455±5ms                                 |    0.55 | queko.QUEKOTranspilerBench.time_transpile_bntf(0, None)                                                         |
| -        | 238±5ms                                    | 102±2ms                                 |    0.43 | queko.QUEKOTranspilerBench.time_transpile_bntf(1, 'sabre')                                                      |
| -        | 58.8±0.8ms                                 | 30.0±0.3ms                              |    0.51 | queko.QUEKOTranspilerBench.time_transpile_bntf(1, None)                                                         |
| -        | 564±7ms                                    | 388±4ms                                 |    0.69 | queko.QUEKOTranspilerBench.time_transpile_bntf(2, 'sabre')                                                      |
| -        | 134±2ms                                    | 85.9±2ms                                |    0.64 | queko.QUEKOTranspilerBench.time_transpile_bntf(2, None)                                                         |
| -        | 810±10ms                                   | 486±5ms                                 |    0.6  | queko.QUEKOTranspilerBench.time_transpile_bntf(3, 'sabre')                                                      |
| -        | 181±4ms                                    | 113±3ms                                 |    0.62 | queko.QUEKOTranspilerBench.time_transpile_bntf(3, None)                                                         |
| -        | 331±3ms                                    | 177±2ms                                 |    0.53 | queko.QUEKOTranspilerBench.time_transpile_bss(0, 'sabre')                                                       |
| -        | 2.30±0.02s                                 | 1.93±0.01s                              |    0.84 | queko.QUEKOTranspilerBench.time_transpile_bss(0, None)                                                          |
| -        | 281±5ms                                    | 138±1ms                                 |    0.49 | queko.QUEKOTranspilerBench.time_transpile_bss(1, 'sabre')                                                       |
| -        | 169±3ms                                    | 82.0±4ms                                |    0.49 | queko.QUEKOTranspilerBench.time_transpile_bss(1, None)                                                          |
| -        | 640±6ms                                    | 482±6ms                                 |    0.75 | queko.QUEKOTranspilerBench.time_transpile_bss(2, 'sabre')                                                       |
| -        | 364±10ms                                   | 245±3ms                                 |    0.67 | queko.QUEKOTranspilerBench.time_transpile_bss(2, None)                                                          |
| -        | 1.05±0.01s                                 | 725±6ms                                 |    0.69 | queko.QUEKOTranspilerBench.time_transpile_bss(3, 'sabre')                                                       |
| -        | 479±6ms                                    | 318±10ms                                |    0.66 | queko.QUEKOTranspilerBench.time_transpile_bss(3, None)                                                          |
| -        | 94.5±4ms                                   | 41.1±0.7ms                              |    0.44 | random_circuit_hex.BenchRandomCircuitHex.time_ibmq_backend_transpile(10)                                        |
| -        | 121±2ms                                    | 57.4±3ms                                |    0.47 | random_circuit_hex.BenchRandomCircuitHex.time_ibmq_backend_transpile(12)                                        |
| -        | 212±9ms                                    | 85.2±2ms                                |    0.4  | random_circuit_hex.BenchRandomCircuitHex.time_ibmq_backend_transpile(14)                                        |
| -        | 20.6±0.8ms                                 | 12.1±0.2ms                              |    0.59 | random_circuit_hex.BenchRandomCircuitHex.time_ibmq_backend_transpile(4)                                         |
| -        | 36.5±1ms                                   | 20.1±1ms                                |    0.55 | random_circuit_hex.BenchRandomCircuitHex.time_ibmq_backend_transpile(6)                                         |
| -        | 58.8±1ms                                   | 31.8±1ms                                |    0.54 | random_circuit_hex.BenchRandomCircuitHex.time_ibmq_backend_transpile(8)                                         |
| -        | 23.4±0.05s                                 | 18.3±0s                                 |    0.78 | randomized_benchmarking.RandomizedBenchmarkingBenchmark.time_ibmq_backend_transpile_single_thread([0, 1])       |
| -        | 1.06±0.05ms                                | 884±8μs                                 |    0.84 | ripple_adder.RippleAdderConstruction.time_build_ripple_adder(10)                                                |
| -        | 9.04±0.1ms                                 | 8.11±0.1ms                              |    0.9  | ripple_adder.RippleAdderConstruction.time_build_ripple_adder(100)                                               |
| -        | 4.69±0.06ms                                | 4.08±0.08ms                             |    0.87 | ripple_adder.RippleAdderConstruction.time_build_ripple_adder(50)                                                |
| -        | 239±3ms                                    | 183±1ms                                 |    0.77 | ripple_adder.RippleAdderTranspile.time_transpile_square_grid_ripple_adder(10, 0)                                |
| -        | 107±2ms                                    | 41.1±0.6ms                              |    0.39 | ripple_adder.RippleAdderTranspile.time_transpile_square_grid_ripple_adder(10, 1)                                |
| -        | 198±2ms                                    | 124±3ms                                 |    0.63 | ripple_adder.RippleAdderTranspile.time_transpile_square_grid_ripple_adder(10, 2)                                |
| -        | 243±2ms                                    | 149±3ms                                 |    0.61 | ripple_adder.RippleAdderTranspile.time_transpile_square_grid_ripple_adder(10, 3)                                |
| -        | 675±8ms                                    | 548±7ms                                 |    0.81 | ripple_adder.RippleAdderTranspile.time_transpile_square_grid_ripple_adder(20, 0)                                |
| -        | 216±2ms                                    | 78.1±1ms                                |    0.36 | ripple_adder.RippleAdderTranspile.time_transpile_square_grid_ripple_adder(20, 1)                                |
| -        | 418±8ms                                    | 258±2ms                                 |    0.62 | ripple_adder.RippleAdderTranspile.time_transpile_square_grid_ripple_adder(20, 2)                                |
| -        | 515±20ms                                   | 309±3ms                                 |    0.6  | ripple_adder.RippleAdderTranspile.time_transpile_square_grid_ripple_adder(20, 3)                                |
| -        | 1.93±0.03s                                 | 1.27±0.03s                              |    0.66 | scheduling_passes.SchedulingPassBenchmarks.time_alap_schedule_pass(10, 1000)                                    |
| -        | 944±20ms                                   | 632±20ms                                |    0.67 | scheduling_passes.SchedulingPassBenchmarks.time_alap_schedule_pass(10, 500)                                     |
| -        | 774±10ms                                   | 497±10ms                                |    0.64 | scheduling_passes.SchedulingPassBenchmarks.time_alap_schedule_pass(5, 1000)                                     |
| -        | 367±4ms                                    | 244±9ms                                 |    0.66 | scheduling_passes.SchedulingPassBenchmarks.time_alap_schedule_pass(5, 500)                                      |
| -        | 1.90±0.01s                                 | 1.28±0.02s                              |    0.67 | scheduling_passes.SchedulingPassBenchmarks.time_asap_schedule_pass(10, 1000)                                    |
| -        | 986±20ms                                   | 639±10ms                                |    0.65 | scheduling_passes.SchedulingPassBenchmarks.time_asap_schedule_pass(10, 500)                                     |
| -        | 793±30ms                                   | 499±7ms                                 |    0.63 | scheduling_passes.SchedulingPassBenchmarks.time_asap_schedule_pass(5, 1000)                                     |
| -        | 384±20ms                                   | 239±2ms                                 |    0.62 | scheduling_passes.SchedulingPassBenchmarks.time_asap_schedule_pass(5, 500)                                      |
| -        | 185±10ms                                   | 149±5ms                                 |    0.8  | scheduling_passes.SchedulingPassBenchmarks.time_time_unit_conversion_pass(10, 500)                              |
| -        | 155±3ms                                    | 121±0.5ms                               |    0.78 | scheduling_passes.SchedulingPassBenchmarks.time_time_unit_conversion_pass(5, 1000)                              |
| -        | 76.4±3ms                                   | 59.4±1ms                                |    0.78 | scheduling_passes.SchedulingPassBenchmarks.time_time_unit_conversion_pass(5, 500)                               |
| -        | 986±20ms                                   | 503±7ms                                 |    0.51 | transpiler_benchmarks.TranspilerBenchSuite.time_compile_from_large_qasm                                         |
| -        | 1.67±0.01s                                 | 1.21±0.01s                              |    0.73 | transpiler_levels.TranspilerLevelBenchmarks.time_quantum_volume_transpile_50_x_20(0)                            |
| -        | 1.07±0.01s                                 | 386±6ms                                 |    0.36 | transpiler_levels.TranspilerLevelBenchmarks.time_quantum_volume_transpile_50_x_20(1)                            |
| -        | 2.97±0.05s                                 | 2.10±0.03s                              |    0.71 | transpiler_levels.TranspilerLevelBenchmarks.time_quantum_volume_transpile_50_x_20(2)                            |
| -        | 3.77±0.1s                                  | 2.47±0.03s                              |    0.66 | transpiler_levels.TranspilerLevelBenchmarks.time_quantum_volume_transpile_50_x_20(3)                            |
| -        | 244±4ms                                    | 149±1ms                                 |    0.61 | transpiler_levels.TranspilerLevelBenchmarks.time_schedule_qv_14_x_14(0)                                         |
| -        | 242±6ms                                    | 107±3ms                                 |    0.44 | transpiler_levels.TranspilerLevelBenchmarks.time_schedule_qv_14_x_14(1)                                         |
| -        | 242±5ms                                    | 83.9±3ms                                |    0.35 | transpiler_levels.TranspilerLevelBenchmarks.time_transpile_from_large_qasm(0)                                   |
| -        | 366±3ms                                    | 111±0.8ms                               |    0.3  | transpiler_levels.TranspilerLevelBenchmarks.time_transpile_from_large_qasm(1)                                   |
| -        | 477±10ms                                   | 172±4ms                                 |    0.36 | transpiler_levels.TranspilerLevelBenchmarks.time_transpile_from_large_qasm(2)                                   |
| -        | 484±6ms                                    | 174±2ms                                 |    0.36 | transpiler_levels.TranspilerLevelBenchmarks.time_transpile_from_large_qasm(3)                                   |
| -        | 245±4ms                                    | 89.4±1ms                                |    0.36 | transpiler_levels.TranspilerLevelBenchmarks.time_transpile_from_large_qasm_backend_with_prop(0)                 |
| -        | 416±20ms                                   | 145±0.8ms                               |    0.35 | transpiler_levels.TranspilerLevelBenchmarks.time_transpile_from_large_qasm_backend_with_prop(1)                 |
| -        | 461±3ms                                    | 184±3ms                                 |    0.4  | transpiler_levels.TranspilerLevelBenchmarks.time_transpile_from_large_qasm_backend_with_prop(2)                 |
| -        | 495±8ms                                    | 190±2ms                                 |    0.38 | transpiler_levels.TranspilerLevelBenchmarks.time_transpile_from_large_qasm_backend_with_prop(3)                 |
| -        | 166±2ms                                    | 109±0.4ms                               |    0.66 | transpiler_levels.TranspilerLevelBenchmarks.time_transpile_qv_14_x_14(0)                                        |
| -        | 210±3ms                                    | 94.3±3ms                                |    0.45 | transpiler_levels.TranspilerLevelBenchmarks.time_transpile_qv_14_x_14(1)                                        |
| -        | 473±7ms                                    | 326±8ms                                 |    0.69 | transpiler_levels.TranspilerLevelBenchmarks.time_transpile_qv_14_x_14(2)                                        |
| -        | 547±10ms                                   | 358±3ms                                 |    0.65 | transpiler_levels.TranspilerLevelBenchmarks.time_transpile_qv_14_x_14(3)                                        |
| -        | 67.9±2ms                                   | 49.7±2ms                                |    0.73 | transpiler_qualitative.TranspilerQualitativeBench.time_transpile_time_cnt3_5_179(0, 'sabre', 'dense')           |
| -        | 63.9±2ms                                   | 47.6±1ms                                |    0.75 | transpiler_qualitative.TranspilerQualitativeBench.time_transpile_time_cnt3_5_179(0, 'sabre', 'sabre')           |
| -        | 126±2ms                                    | 106±1ms                                 |    0.84 | transpiler_qualitative.TranspilerQualitativeBench.time_transpile_time_cnt3_5_179(0, 'stochastic', 'dense')      |
| -        | 122±1ms                                    | 106±0.8ms                               |    0.87 | transpiler_qualitative.TranspilerQualitativeBench.time_transpile_time_cnt3_5_179(0, 'stochastic', 'sabre')      |
| -        | 79.6±2ms                                   | 56.9±2ms                                |    0.71 | transpiler_qualitative.TranspilerQualitativeBench.time_transpile_time_cnt3_5_179(1, 'sabre', 'dense')           |
| -        | 73.7±3ms                                   | 55.5±0.7ms                              |    0.75 | transpiler_qualitative.TranspilerQualitativeBench.time_transpile_time_cnt3_5_179(1, 'sabre', 'sabre')           |
| -        | 143±3ms                                    | 114±3ms                                 |    0.8  | transpiler_qualitative.TranspilerQualitativeBench.time_transpile_time_cnt3_5_179(1, 'stochastic', 'dense')      |
| -        | 126±1ms                                    | 103±1ms                                 |    0.82 | transpiler_qualitative.TranspilerQualitativeBench.time_transpile_time_cnt3_5_179(1, 'stochastic', 'sabre')      |
| -        | 124±3ms                                    | 93.6±3ms                                |    0.75 | transpiler_qualitative.TranspilerQualitativeBench.time_transpile_time_cnt3_5_179(2, 'sabre', 'dense')           |
| -        | 144±2ms                                    | 112±1ms                                 |    0.78 | transpiler_qualitative.TranspilerQualitativeBench.time_transpile_time_cnt3_5_179(2, 'sabre', 'sabre')           |
| -        | 240±3ms                                    | 189±3ms                                 |    0.79 | transpiler_qualitative.TranspilerQualitativeBench.time_transpile_time_cnt3_5_179(2, 'stochastic', 'dense')      |
| -        | 214±8ms                                    | 169±1ms                                 |    0.79 | transpiler_qualitative.TranspilerQualitativeBench.time_transpile_time_cnt3_5_179(2, 'stochastic', 'sabre')      |
| -        | 160±2ms                                    | 113±2ms                                 |    0.71 | transpiler_qualitative.TranspilerQualitativeBench.time_transpile_time_cnt3_5_179(3, 'sabre', 'dense')           |
| -        | 199±3ms                                    | 144±3ms                                 |    0.72 | transpiler_qualitative.TranspilerQualitativeBench.time_transpile_time_cnt3_5_179(3, 'sabre', 'sabre')           |
| -        | 313±5ms                                    | 232±1ms                                 |    0.74 | transpiler_qualitative.TranspilerQualitativeBench.time_transpile_time_cnt3_5_179(3, 'stochastic', 'dense')      |
| -        | 248±2ms                                    | 198±1ms                                 |    0.8  | transpiler_qualitative.TranspilerQualitativeBench.time_transpile_time_cnt3_5_179(3, 'stochastic', 'sabre')      |
| -        | 104±1ms                                    | 70.4±1ms                                |    0.68 | transpiler_qualitative.TranspilerQualitativeBench.time_transpile_time_cnt3_5_180(0, 'sabre', 'dense')           |
| -        | 99.8±0.7ms                                 | 69.1±0.7ms                              |    0.69 | transpiler_qualitative.TranspilerQualitativeBench.time_transpile_time_cnt3_5_180(0, 'sabre', 'sabre')           |
| -        | 274±2ms                                    | 231±4ms                                 |    0.84 | transpiler_qualitative.TranspilerQualitativeBench.time_transpile_time_cnt3_5_180(0, 'stochastic', 'dense')      |
| -        | 285±2ms                                    | 242±5ms                                 |    0.85 | transpiler_qualitative.TranspilerQualitativeBench.time_transpile_time_cnt3_5_180(0, 'stochastic', 'sabre')      |
| -        | 141±2ms                                    | 84.7±2ms                                |    0.6  | transpiler_qualitative.TranspilerQualitativeBench.time_transpile_time_cnt3_5_180(1, 'sabre', 'dense')           |
| -        | 138±2ms                                    | 84.6±1ms                                |    0.61 | transpiler_qualitative.TranspilerQualitativeBench.time_transpile_time_cnt3_5_180(1, 'sabre', 'sabre')           |
| -        | 329±3ms                                    | 246±6ms                                 |    0.75 | transpiler_qualitative.TranspilerQualitativeBench.time_transpile_time_cnt3_5_180(1, 'stochastic', 'dense')      |
| -        | 326±4ms                                    | 258±2ms                                 |    0.79 | transpiler_qualitative.TranspilerQualitativeBench.time_transpile_time_cnt3_5_180(1, 'stochastic', 'sabre')      |
| -        | 326±3ms                                    | 231±6ms                                 |    0.71 | transpiler_qualitative.TranspilerQualitativeBench.time_transpile_time_cnt3_5_180(2, 'sabre', 'dense')           |
| -        | 354±10ms                                   | 262±9ms                                 |    0.74 | transpiler_qualitative.TranspilerQualitativeBench.time_transpile_time_cnt3_5_180(2, 'sabre', 'sabre')           |
| -        | 555±20ms                                   | 415±5ms                                 |    0.75 | transpiler_qualitative.TranspilerQualitativeBench.time_transpile_time_cnt3_5_180(2, 'stochastic', 'dense')      |
| -        | 585±4ms                                    | 467±10ms                                |    0.8  | transpiler_qualitative.TranspilerQualitativeBench.time_transpile_time_cnt3_5_180(2, 'stochastic', 'sabre')      |
| -        | 479±10ms                                   | 305±4ms                                 |    0.64 | transpiler_qualitative.TranspilerQualitativeBench.time_transpile_time_cnt3_5_180(3, 'sabre', 'dense')           |
| -        | 495±4ms                                    | 336±6ms                                 |    0.68 | transpiler_qualitative.TranspilerQualitativeBench.time_transpile_time_cnt3_5_180(3, 'sabre', 'sabre')           |
| -        | 676±10ms                                   | 511±10ms                                |    0.76 | transpiler_qualitative.TranspilerQualitativeBench.time_transpile_time_cnt3_5_180(3, 'stochastic', 'dense')      |
| -        | 716±20ms                                   | 554±10ms                                |    0.77 | transpiler_qualitative.TranspilerQualitativeBench.time_transpile_time_cnt3_5_180(3, 'stochastic', 'sabre')      |
| -        | 110±4ms                                    | 67.6±0.8ms                              |    0.61 | transpiler_qualitative.TranspilerQualitativeBench.time_transpile_time_qft_16(0, 'sabre', 'dense')               |
| -        | 102±3ms                                    | 64.9±3ms                                |    0.63 | transpiler_qualitative.TranspilerQualitativeBench.time_transpile_time_qft_16(0, 'sabre', 'sabre')               |
| -        | 238±3ms                                    | 185±4ms                                 |    0.78 | transpiler_qualitative.TranspilerQualitativeBench.time_transpile_time_qft_16(0, 'stochastic', 'dense')          |
| -        | 255±4ms                                    | 200±7ms                                 |    0.78 | transpiler_qualitative.TranspilerQualitativeBench.time_transpile_time_qft_16(0, 'stochastic', 'sabre')          |
| -        | 151±2ms                                    | 81.9±2ms                                |    0.54 | transpiler_qualitative.TranspilerQualitativeBench.time_transpile_time_qft_16(1, 'sabre', 'dense')               |
| -        | 142±2ms                                    | 79.8±4ms                                |    0.56 | transpiler_qualitative.TranspilerQualitativeBench.time_transpile_time_qft_16(1, 'sabre', 'sabre')               |
| -        | 312±10ms                                   | 204±2ms                                 |    0.65 | transpiler_qualitative.TranspilerQualitativeBench.time_transpile_time_qft_16(1, 'stochastic', 'dense')          |
| -        | 305±2ms                                    | 205±1ms                                 |    0.67 | transpiler_qualitative.TranspilerQualitativeBench.time_transpile_time_qft_16(1, 'stochastic', 'sabre')          |
| -        | 19.5±1ms                                   | 12.6±0.2ms                              |    0.65 | utility_scale.UtilityScaleBenchmarks.time_parse_qaoa_n100('cx')                                                 |
| -        | 19.2±0.6ms                                 | 12.9±0.5ms                              |    0.67 | utility_scale.UtilityScaleBenchmarks.time_parse_qaoa_n100('cz')                                                 |
| -        | 19.7±0.9ms                                 | 12.5±0.2ms                              |    0.63 | utility_scale.UtilityScaleBenchmarks.time_parse_qaoa_n100('ecr')                                                |
| -        | 221±4ms                                    | 144±5ms                                 |    0.65 | utility_scale.UtilityScaleBenchmarks.time_parse_qft_n100('cx')                                                  |
| -        | 216±6ms                                    | 143±2ms                                 |    0.66 | utility_scale.UtilityScaleBenchmarks.time_parse_qft_n100('cz')                                                  |
| -        | 221±3ms                                    | 142±6ms                                 |    0.64 | utility_scale.UtilityScaleBenchmarks.time_parse_qft_n100('ecr')                                                 |
| -        | 68.9±1ms                                   | 45.8±0.3ms                              |    0.67 | utility_scale.UtilityScaleBenchmarks.time_parse_square_heisenberg_n100('cx')                                    |
| -        | 67.5±0.6ms                                 | 46.2±2ms                                |    0.68 | utility_scale.UtilityScaleBenchmarks.time_parse_square_heisenberg_n100('cz')                                    |
| -        | 71.7±2ms                                   | 45.4±2ms                                |    0.63 | utility_scale.UtilityScaleBenchmarks.time_parse_square_heisenberg_n100('ecr')                                   |
| -        | 2.66±0.05s                                 | 1.83±0.02s                              |    0.69 | utility_scale.UtilityScaleBenchmarks.time_qaoa('cx')                                                            |
| -        | 3.47±0.02s                                 | 1.83±0.02s                              |    0.53 | utility_scale.UtilityScaleBenchmarks.time_square_heisenberg('cx')                                               |
| -        | 4.80±0s                                    | 2.66±0.03s                              |    0.55 | utility_scale.UtilityScaleBenchmarks.time_square_heisenberg('cz')                                               |
| -        | 4.69±0.01s                                 | 2.49±0.04s                              |    0.53 | utility_scale.UtilityScaleBenchmarks.time_square_heisenberg('ecr')                                              |
| Change   | Before [bb60891a] <repack-instruction~1>   | After [d9e31ed5] <repack-instruction>   |   Ratio | Benchmark (Parameter)                                           |
|----------|--------------------------------------------|-----------------------------------------|---------|-----------------------------------------------------------------|
| +        | 87.1±3ms                                   | 143±4ms                                 |    1.65 | assembler.AssemblerBenchmarks.time_assemble_circuit(8, 4096, 1) |

```

**Comment by jakelishman** [comment]
Benchmarking against 1.1.0, showing only changed.  Note that most utility-scale transpilations are not in this list - they're within 10% of 1.1.0 now.  `assign_parameters` is still much slower; we need to both rework `Param` handling in Rust a bit to avoid the nearly 50% padding factor, and probably move the orchestration down to Rust to avoid allocations.

```text
| Change   | Before [7d29dc1b] <1.1.0^0>   | After [d9e31ed5] <repack-instruction>   |   Ratio | Benchmark (Parameter)                                                                                           |
|----------|-------------------------------|-----------------------------------------|---------|-----------------------------------------------------------------------------------------------------------------|
| -        | 1.07±0.04ms                   | 714±90μs                                |    0.67 | circuit_construction.CircuitConstructionBench.time_circuit_construction(1, 128)                                 |
| -        | 1.04±0.01s                    | 683±30ms                                |    0.65 | circuit_construction.CircuitConstructionBench.time_circuit_construction(1, 131072)                              |
| -        | 17.1±0.8ms                    | 11.2±0.4ms                              |    0.65 | circuit_construction.CircuitConstructionBench.time_circuit_construction(1, 2048)                                |
| -        | 258±5ms                       | 172±6ms                                 |    0.67 | circuit_construction.CircuitConstructionBench.time_circuit_construction(1, 32768)                               |
| -        | 65.6±2ms                      | 42.3±2ms                                |    0.64 | circuit_construction.CircuitConstructionBench.time_circuit_construction(1, 8192)                                |
| -        | 1.22±0.01ms                   | 827±30μs                                |    0.68 | circuit_construction.CircuitConstructionBench.time_circuit_construction(14, 128)                                |
| -        | 1.15±0.01s                    | 713±20ms                                |    0.62 | circuit_construction.CircuitConstructionBench.time_circuit_construction(14, 131072)                             |
| -        | 17.6±0.3ms                    | 10.6±0.09ms                             |    0.6  | circuit_construction.CircuitConstructionBench.time_circuit_construction(14, 2048)                               |
| -        | 284±6ms                       | 183±4ms                                 |    0.64 | circuit_construction.CircuitConstructionBench.time_circuit_construction(14, 32768)                              |
| -        | 297±4μs                       | 210±10μs                                |    0.71 | circuit_construction.CircuitConstructionBench.time_circuit_construction(14, 8)                                  |
| -        | 70.1±6ms                      | 43.1±0.8ms                              |    0.61 | circuit_construction.CircuitConstructionBench.time_circuit_construction(14, 8192)                               |
| -        | 1.18±0.06ms                   | 720±10μs                                |    0.61 | circuit_construction.CircuitConstructionBench.time_circuit_construction(2, 128)                                 |
| -        | 1.11±0.01s                    | 701±5ms                                 |    0.63 | circuit_construction.CircuitConstructionBench.time_circuit_construction(2, 131072)                              |
| -        | 17.1±0.3ms                    | 10.5±0.2ms                              |    0.61 | circuit_construction.CircuitConstructionBench.time_circuit_construction(2, 2048)                                |
| -        | 277±4ms                       | 171±2ms                                 |    0.62 | circuit_construction.CircuitConstructionBench.time_circuit_construction(2, 32768)                               |
| -        | 114±0.8μs                     | 78.1±2μs                                |    0.69 | circuit_construction.CircuitConstructionBench.time_circuit_construction(2, 8)                                   |
| -        | 76.3±4ms                      | 44.4±1ms                                |    0.58 | circuit_construction.CircuitConstructionBench.time_circuit_construction(2, 8192)                                |
| -        | 1.41±0.07ms                   | 929±70μs                                |    0.66 | circuit_construction.CircuitConstructionBench.time_circuit_construction(20, 128)                                |
| -        | 1.11±0.01s                    | 702±10ms                                |    0.63 | circuit_construction.CircuitConstructionBench.time_circuit_construction(20, 131072)                             |
| -        | 17.6±0.2ms                    | 10.9±0.2ms                              |    0.62 | circuit_construction.CircuitConstructionBench.time_circuit_construction(20, 2048)                               |
| -        | 282±10ms                      | 172±3ms                                 |    0.61 | circuit_construction.CircuitConstructionBench.time_circuit_construction(20, 32768)                              |
| -        | 415±30μs                      | 296±8μs                                 |    0.71 | circuit_construction.CircuitConstructionBench.time_circuit_construction(20, 8)                                  |
| -        | 69.5±1ms                      | 42.7±0.5ms                              |    0.61 | circuit_construction.CircuitConstructionBench.time_circuit_construction(20, 8192)                               |
| -        | 1.26±0.06ms                   | 792±100μs                               |    0.63 | circuit_construction.CircuitConstructionBench.time_circuit_construction(5, 128)                                 |
| -        | 1.11±0.02s                    | 693±10ms                                |    0.63 | circuit_construction.CircuitConstructionBench.time_circuit_construction(5, 131072)                              |
| -        | 17.9±0.8ms                    | 10.8±0.2ms                              |    0.6  | circuit_construction.CircuitConstructionBench.time_circuit_construction(5, 2048)                                |
| -        | 279±4ms                       | 170±3ms                                 |    0.61 | circuit_construction.CircuitConstructionBench.time_circuit_construction(5, 32768)                               |
| -        | 123±2μs                       | 84.0±4μs                                |    0.69 | circuit_construction.CircuitConstructionBench.time_circuit_construction(5, 8)                                   |
| -        | 70.5±3ms                      | 43.9±2ms                                |    0.62 | circuit_construction.CircuitConstructionBench.time_circuit_construction(5, 8192)                                |
| -        | 1.30±0.03ms                   | 756±6μs                                 |    0.58 | circuit_construction.CircuitConstructionBench.time_circuit_construction(8, 128)                                 |
| -        | 1.14±0.04s                    | 704±5ms                                 |    0.61 | circuit_construction.CircuitConstructionBench.time_circuit_construction(8, 131072)                              |
| -        | 17.4±0.2ms                    | 11.8±0.5ms                              |    0.68 | circuit_construction.CircuitConstructionBench.time_circuit_construction(8, 2048)                                |
| -        | 282±10ms                      | 181±7ms                                 |    0.64 | circuit_construction.CircuitConstructionBench.time_circuit_construction(8, 32768)                               |
| -        | 192±8μs                       | 124±3μs                                 |    0.64 | circuit_construction.CircuitConstructionBench.time_circuit_construction(8, 8)                                   |
| -        | 71.7±3ms                      | 43.4±0.4ms                              |    0.61 | circuit_construction.CircuitConstructionBench.time_circuit_construction(8, 8192)                                |
| -        | 27.9±0.2μs                    | 10.7±0.3μs                              |    0.38 | circuit_construction.CircuitConstructionBench.time_circuit_copy(1, 128)                                         |
| -        | 18.0±0.4ms                    | 2.92±0.6ms                              |    0.16 | circuit_construction.CircuitConstructionBench.time_circuit_copy(1, 131072)                                      |
| -        | 299±9μs                       | 37.8±5μs                                |    0.13 | circuit_construction.CircuitConstructionBench.time_circuit_copy(1, 2048)                                        |
| -        | 4.59±0.3ms                    | 543±200μs                               |    0.12 | circuit_construction.CircuitConstructionBench.time_circuit_copy(1, 32768)                                       |
| -        | 12.1±0.1μs                    | 9.42±0.07μs                             |    0.78 | circuit_construction.CircuitConstructionBench.time_circuit_copy(1, 8)                                           |
| -        | 1.14±0.01ms                   | 106±20μs                                |    0.09 | circuit_construction.CircuitConstructionBench.time_circuit_copy(1, 8192)                                        |
| -        | 34.9±0.7μs                    | 16.7±0.8μs                              |    0.48 | circuit_construction.CircuitConstructionBench.time_circuit_copy(14, 128)                                        |
| -        | 17.8±0.1ms                    | 3.68±0.1ms                              |    0.21 | circuit_construction.CircuitConstructionBench.time_circuit_copy(14, 131072)                                     |
| -        | 295±2μs                       | 40.8±5μs                                |    0.14 | circuit_construction.CircuitConstructionBench.time_circuit_copy(14, 2048)                                       |
| -        | 4.56±0.2ms                    | 532±100μs                               |    0.12 | circuit_construction.CircuitConstructionBench.time_circuit_copy(14, 32768)                                      |
| -        | 20.1±0.6μs                    | 14.8±0.9μs                              |    0.73 | circuit_construction.CircuitConstructionBench.time_circuit_copy(14, 8)                                          |
| -        | 1.14±0.04ms                   | 122±30μs                                |    0.11 | circuit_construction.CircuitConstructionBench.time_circuit_copy(14, 8192)                                       |
| -        | 29.6±0.3μs                    | 12.4±0.1μs                              |    0.42 | circuit_construction.CircuitConstructionBench.time_circuit_copy(2, 128)                                         |
| -        | 17.9±0.2ms                    | 3.73±0.2ms                              |    0.21 | circuit_construction.CircuitConstructionBench.time_circuit_copy(2, 131072)                                      |
| -        | 286±3μs                       | 32.2±5μs                                |    0.11 | circuit_construction.CircuitConstructionBench.time_circuit_copy(2, 2048)                                        |
| -        | 4.61±0.2ms                    | 541±100μs                               |    0.12 | circuit_construction.CircuitConstructionBench.time_circuit_copy(2, 32768)                                       |
| -        | 12.6±0.1μs                    | 9.87±0.3μs                              |    0.78 | circuit_construction.CircuitConstructionBench.time_circuit_copy(2, 8)                                           |
| -        | 1.18±0.05ms                   | 142±20μs                                |    0.12 | circuit_construction.CircuitConstructionBench.time_circuit_copy(2, 8192)                                        |
| -        | 41.0±0.6μs                    | 19.5±1μs                                |    0.48 | circuit_construction.CircuitConstructionBench.time_circuit_copy(20, 128)                                        |
| -        | 18.2±0.3ms                    | 3.67±0.1ms                              |    0.2  | circuit_construction.CircuitConstructionBench.time_circuit_copy(20, 131072)                                     |
| -        | 312±20μs                      | 50.9±6μs                                |    0.16 | circuit_construction.CircuitConstructionBench.time_circuit_copy(20, 2048)                                       |
| -        | 4.62±0.1ms                    | 577±100μs                               |    0.12 | circuit_construction.CircuitConstructionBench.time_circuit_copy(20, 32768)                                      |
| -        | 1.15±0.02ms                   | 117±8μs                                 |    0.1  | circuit_construction.CircuitConstructionBench.time_circuit_copy(20, 8192)                                       |
| -        | 30.0±0.3μs                    | 12.9±0.2μs                              |    0.43 | circuit_construction.CircuitConstructionBench.time_circuit_copy(5, 128)                                         |
| -        | 18.1±0.1ms                    | 3.62±0.3ms                              |    0.2  | circuit_construction.CircuitConstructionBench.time_circuit_copy(5, 131072)                                      |
| -        | 309±6μs                       | 34.0±3μs                                |    0.11 | circuit_construction.CircuitConstructionBench.time_circuit_copy(5, 2048)                                        |
| -        | 4.63±0.2ms                    | 576±100μs                               |    0.12 | circuit_construction.CircuitConstructionBench.time_circuit_copy(5, 32768)                                       |
| -        | 14.9±0.2μs                    | 10.5±0.1μs                              |    0.71 | circuit_construction.CircuitConstructionBench.time_circuit_copy(5, 8)                                           |
| -        | 1.19±0.03ms                   | 108±30μs                                |    0.09 | circuit_construction.CircuitConstructionBench.time_circuit_copy(5, 8192)                                        |
| -        | 32.0±0.8μs                    | 14.9±2μs                                |    0.47 | circuit_construction.CircuitConstructionBench.time_circuit_copy(8, 128)                                         |
| -        | 18.1±0.6ms                    | 3.61±0.3ms                              |    0.2  | circuit_construction.CircuitConstructionBench.time_circuit_copy(8, 131072)                                      |
| -        | 288±5μs                       | 44.5±8μs                                |    0.15 | circuit_construction.CircuitConstructionBench.time_circuit_copy(8, 2048)                                        |
| -        | 4.42±0.1ms                    | 484±200μs                               |    0.11 | circuit_construction.CircuitConstructionBench.time_circuit_copy(8, 32768)                                       |
| -        | 1.10±0.02ms                   | 118±20μs                                |    0.11 | circuit_construction.CircuitConstructionBench.time_circuit_copy(8, 8192)                                        |
| -        | 187±5μs                       | 30.9±0.3μs                              |    0.17 | circuit_construction.CircuitConstructionBench.time_circuit_extend(1, 128)                                       |
| -        | 168±2ms                       | 23.0±0.9ms                              |    0.14 | circuit_construction.CircuitConstructionBench.time_circuit_extend(1, 131072)                                    |
| -        | 2.75±0.1ms                    | 343±8μs                                 |    0.12 | circuit_construction.CircuitConstructionBench.time_circuit_extend(1, 2048)                                      |
| -        | 41.7±0.3ms                    | 5.68±0.2ms                              |    0.14 | circuit_construction.CircuitConstructionBench.time_circuit_extend(1, 32768)                                     |
| -        | 20.3±0.5μs                    | 11.3±0.5μs                              |    0.56 | circuit_construction.CircuitConstructionBench.time_circuit_extend(1, 8)                                         |
| -        | 11.1±0.3ms                    | 1.39±0.08ms                             |    0.13 | circuit_construction.CircuitConstructionBench.time_circuit_extend(1, 8192)                                      |
| -        | 204±2μs                       | 54.1±7μs                                |    0.26 | circuit_construction.CircuitConstructionBench.time_circuit_extend(14, 128)                                      |
| -        | 184±2ms                       | 34.7±0.2ms                              |    0.19 | circuit_construction.CircuitConstructionBench.time_circuit_extend(14, 131072)                                   |
| -        | 2.87±0.1ms                    | 439±10μs                                |    0.15 | circuit_construction.CircuitConstructionBench.time_circuit_extend(14, 2048)                                     |
| -        | 44.9±0.5ms                    | 7.24±0.4ms                              |    0.16 | circuit_construction.CircuitConstructionBench.time_circuit_extend(14, 32768)                                    |
| -        | 53.2±0.6μs                    | 27.0±0.7μs                              |    0.51 | circuit_construction.CircuitConstructionBench.time_circuit_extend(14, 8)                                        |
| -        | 11.4±0.3ms                    | 1.83±0.09ms                             |    0.16 | circuit_construction.CircuitConstructionBench.time_circuit_extend(14, 8192)                                     |
| -        | 188±2μs                       | 36.0±2μs                                |    0.19 | circuit_construction.CircuitConstructionBench.time_circuit_extend(2, 128)                                       |
| -        | 187±6ms                       | 33.6±2ms                                |    0.18 | circuit_construction.CircuitConstructionBench.time_circuit_extend(2, 131072)                                    |
| -        | 2.98±0.09ms                   | 380±20μs                                |    0.13 | circuit_construction.CircuitConstructionBench.time_circuit_extend(2, 2048)                                      |
| -        | 45.1±1ms                      | 7.02±0.3ms                              |    0.16 | circuit_construction.CircuitConstructionBench.time_circuit_extend(2, 32768)                                     |
| -        | 23.3±1μs                      | 11.5±0.2μs                              |    0.49 | circuit_construction.CircuitConstructionBench.time_circuit_extend(2, 8)                                         |
| -        | 11.9±0.3ms                    | 1.62±0.05ms                             |    0.14 | circuit_construction.CircuitConstructionBench.time_circuit_extend(2, 8192)                                      |
| -        | 246±8μs                       | 57.8±10μs                               |    0.24 | circuit_construction.CircuitConstructionBench.time_circuit_extend(20, 128)                                      |
| -        | 182±1ms                       | 35.6±2ms                                |    0.2  | circuit_construction.CircuitConstructionBench.time_circuit_extend(20, 131072)                                   |
| -        | 2.91±0.05ms                   | 447±7μs                                 |    0.15 | circuit_construction.CircuitConstructionBench.time_circuit_extend(20, 2048)                                     |
| -        | 45.6±1ms                      | 7.42±0.5ms                              |    0.16 | circuit_construction.CircuitConstructionBench.time_circuit_extend(20, 32768)                                    |
| -        | 76.3±4μs                      | 26.5±0.8μs                              |    0.35 | circuit_construction.CircuitConstructionBench.time_circuit_extend(20, 8)                                        |
| -        | 11.6±0.5ms                    | 1.90±0.1ms                              |    0.16 | circuit_construction.CircuitConstructionBench.time_circuit_extend(20, 8192)                                     |
| -        | 213±9μs                       | 38.4±0.8μs                              |    0.18 | circuit_construction.CircuitConstructionBench.time_circuit_extend(5, 128)                                       |
| -        | 185±6ms                       | 34.9±1ms                                |    0.19 | circuit_construction.CircuitConstructionBench.time_circuit_extend(5, 131072)                                    |
| -        | 2.87±0.04ms                   | 457±20μs                                |    0.16 | circuit_construction.CircuitConstructionBench.time_circuit_extend(5, 2048)                                      |
| -        | 48.0±2ms                      | 7.04±0.2ms                              |    0.15 | circuit_construction.CircuitConstructionBench.time_circuit_extend(5, 32768)                                     |
| -        | 24.5±1μs                      | 13.0±0.3μs                              |    0.53 | circuit_construction.CircuitConstructionBench.time_circuit_extend(5, 8)                                         |
| -        | 11.4±0.3ms                    | 1.77±0.06ms                             |    0.16 | circuit_construction.CircuitConstructionBench.time_circuit_extend(5, 8192)                                      |
| -        | 210±6μs                       | 41.8±2μs                                |    0.2  | circuit_construction.CircuitConstructionBench.time_circuit_extend(8, 128)                                       |
| -        | 185±3ms                       | 35.4±1ms                                |    0.19 | circuit_construction.CircuitConstructionBench.time_circuit_extend(8, 131072)                                    |
| -        | 2.89±0.02ms                   | 446±30μs                                |    0.15 | circuit_construction.CircuitConstructionBench.time_circuit_extend(8, 2048)                                      |
| -        | 45.3±1ms                      | 7.14±0.3ms                              |    0.16 | circuit_construction.CircuitConstructionBench.time_circuit_extend(8, 32768)                                     |
| -        | 37.0±0.8μs                    | 16.0±0.5μs                              |    0.43 | circuit_construction.CircuitConstructionBench.time_circuit_extend(8, 8)                                         |
| -        | 11.6±0.3ms                    | 1.74±0.07ms                             |    0.15 | circuit_construction.CircuitConstructionBench.time_circuit_extend(8, 8192)                                      |
| -        | 3.84±0.02ms                   | 1.77±0.02ms                             |    0.46 | circuit_construction.ParameterizedCircuitConstructionBench.time_build_parameterized_circuit(20, 128, 128)       |
| -        | 3.53±0.4ms                    | 1.18±0.1ms                              |    0.34 | circuit_construction.ParameterizedCircuitConstructionBench.time_build_parameterized_circuit(20, 128, 8)         |
| -        | 2.57±0.01s                    | 900±10ms                                |    0.35 | circuit_construction.ParameterizedCircuitConstructionBench.time_build_parameterized_circuit(20, 131072, 128)    |
| -        | 3.52±0.06s                    | 1.62±0.03s                              |    0.46 | circuit_construction.ParameterizedCircuitConstructionBench.time_build_parameterized_circuit(20, 131072, 131072) |
| -        | 2.64±0.06s                    | 912±10ms                                |    0.35 | circuit_construction.ParameterizedCircuitConstructionBench.time_build_parameterized_circuit(20, 131072, 2048)   |
| -        | 2.84±0.02s                    | 1.07±0s                                 |    0.38 | circuit_construction.ParameterizedCircuitConstructionBench.time_build_parameterized_circuit(20, 131072, 32768)  |
| -        | 2.62±0.05s                    | 955±40ms                                |    0.36 | circuit_construction.ParameterizedCircuitConstructionBench.time_build_parameterized_circuit(20, 131072, 8)      |
| -        | 2.63±0.03s                    | 953±10ms                                |    0.36 | circuit_construction.ParameterizedCircuitConstructionBench.time_build_parameterized_circuit(20, 131072, 8192)   |
| -        | 45.1±1ms                      | 14.8±0.4ms                              |    0.33 | circuit_construction.ParameterizedCircuitConstructionBench.time_build_parameterized_circuit(20, 2048, 128)      |
| -        | 50.9±0.7ms                    | 25.1±1ms                                |    0.49 | circuit_construction.ParameterizedCircuitConstructionBench.time_build_parameterized_circuit(20, 2048, 2048)     |
| -        | 38.7±0.3ms                    | 13.8±0.2ms                              |    0.36 | circuit_construction.ParameterizedCircuitConstructionBench.time_build_parameterized_circuit(20, 2048, 8)        |
| -        | 640±20ms                      | 223±1ms                                 |    0.35 | circuit_construction.ParameterizedCircuitConstructionBench.time_build_parameterized_circuit(20, 32768, 128)     |
| -        | 650±7ms                       | 232±10ms                                |    0.36 | circuit_construction.ParameterizedCircuitConstructionBench.time_build_parameterized_circuit(20, 32768, 2048)    |
| -        | 867±20ms                      | 396±4ms                                 |    0.46 | circuit_construction.ParameterizedCircuitConstructionBench.time_build_parameterized_circuit(20, 32768, 32768)   |
| -        | 672±30ms                      | 224±2ms                                 |    0.33 | circuit_construction.ParameterizedCircuitConstructionBench.time_build_parameterized_circuit(20, 32768, 8)       |
| -        | 703±10ms                      | 267±4ms                                 |    0.38 | circuit_construction.ParameterizedCircuitConstructionBench.time_build_parameterized_circuit(20, 32768, 8192)    |
| -        | 873±10μs                      | 393±4μs                                 |    0.45 | circuit_construction.ParameterizedCircuitConstructionBench.time_build_parameterized_circuit(20, 8, 8)           |
| -        | 159±5ms                       | 61.8±2ms                                |    0.39 | circuit_construction.ParameterizedCircuitConstructionBench.time_build_parameterized_circuit(20, 8192, 128)      |
| -        | 174±2ms                       | 67.8±2ms                                |    0.39 | circuit_construction.ParameterizedCircuitConstructionBench.time_build_parameterized_circuit(20, 8192, 2048)     |
| -        | 156±4ms                       | 55.2±0.4ms                              |    0.35 | circuit_construction.ParameterizedCircuitConstructionBench.time_build_parameterized_circuit(20, 8192, 8)        |
| -        | 210±2ms                       | 99.2±2ms                                |    0.47 | circuit_construction.ParameterizedCircuitConstructionBench.time_build_parameterized_circuit(20, 8192, 8192)     |
| -        | 838±10μs                      | 648±7μs                                 |    0.77 | converters.ConverterBenchmarks.time_circuit_to_dag(1, 128)                                                      |
| -        | 12.5±0.3ms                    | 8.50±0.2ms                              |    0.68 | converters.ConverterBenchmarks.time_circuit_to_dag(1, 2048)                                                     |
| -        | 93.5±2μs                      | 59.2±0.7μs                              |    0.63 | converters.ConverterBenchmarks.time_circuit_to_dag(1, 8)                                                        |
| -        | 52.6±1ms                      | 35.3±2ms                                |    0.67 | converters.ConverterBenchmarks.time_circuit_to_dag(1, 8192)                                                     |
| -        | 8.14±0.1ms                    | 6.46±0.2ms                              |    0.79 | converters.ConverterBenchmarks.time_circuit_to_dag(14, 128)                                                     |
| -        | 117±0.8ms                     | 95.0±3ms                                |    0.81 | converters.ConverterBenchmarks.time_circuit_to_dag(14, 2048)                                                    |
| -        | 773±10μs                      | 667±9μs                                 |    0.86 | converters.ConverterBenchmarks.time_circuit_to_dag(14, 8)                                                       |
| -        | 1.45±0.08ms                   | 1.11±0.02ms                             |    0.76 | converters.ConverterBenchmarks.time_circuit_to_dag(2, 128)                                                      |
| -        | 23.3±2ms                      | 15.2±0.2ms                              |    0.65 | converters.ConverterBenchmarks.time_circuit_to_dag(2, 2048)                                                     |
| -        | 157±0.6μs                     | 119±2μs                                 |    0.75 | converters.ConverterBenchmarks.time_circuit_to_dag(2, 8)                                                        |
| -        | 82.2±0.7ms                    | 59.9±1ms                                |    0.73 | converters.ConverterBenchmarks.time_circuit_to_dag(2, 8192)                                                     |
| -        | 1.75±0.02ms                   | 1.53±0.06ms                             |    0.88 | converters.ConverterBenchmarks.time_circuit_to_dag(32, 8)                                                       |
| -        | 3.00±0.1ms                    | 2.27±0.03ms                             |    0.75 | converters.ConverterBenchmarks.time_circuit_to_dag(5, 128)                                                      |
| -        | 40.5±0.8ms                    | 32.0±0.9ms                              |    0.79 | converters.ConverterBenchmarks.time_circuit_to_dag(5, 2048)                                                     |
| -        | 329±20μs                      | 218±10μs                                |    0.66 | converters.ConverterBenchmarks.time_circuit_to_dag(5, 8)                                                        |
| -        | 171±8ms                       | 125±2ms                                 |    0.73 | converters.ConverterBenchmarks.time_circuit_to_dag(5, 8192)                                                     |
| -        | 4.66±0.06ms                   | 3.64±0.04ms                             |    0.78 | converters.ConverterBenchmarks.time_circuit_to_dag(8, 128)                                                      |
| -        | 65.7±2ms                      | 49.6±0.4ms                              |    0.75 | converters.ConverterBenchmarks.time_circuit_to_dag(8, 2048)                                                     |
| -        | 463±20μs                      | 364±5μs                                 |    0.79 | converters.ConverterBenchmarks.time_circuit_to_dag(8, 8)                                                        |
| -        | 258±4ms                       | 193±1ms                                 |    0.75 | converters.ConverterBenchmarks.time_circuit_to_dag(8, 8192)                                                     |
| -        | 299±10μs                      | 240±3μs                                 |    0.8  | converters.ConverterBenchmarks.time_circuit_to_instruction(1, 128)                                              |
| -        | 3.57±0.3ms                    | 2.26±0.06ms                             |    0.63 | converters.ConverterBenchmarks.time_circuit_to_instruction(1, 2048)                                             |
| -        | 12.8±0.1ms                    | 8.84±0.1ms                              |    0.69 | converters.ConverterBenchmarks.time_circuit_to_instruction(1, 8192)                                             |
| -        | 158±10μs                      | 125±3μs                                 |    0.79 | converters.ConverterBenchmarks.time_circuit_to_instruction(5, 8)                                                |
| -        | 548±20μs                      | 243±0.9μs                               |    0.44 | converters.ConverterBenchmarks.time_dag_to_circuit(1, 128)                                                      |
| -        | 8.19±0.8ms                    | 3.25±0.05ms                             |    0.4  | converters.ConverterBenchmarks.time_dag_to_circuit(1, 2048)                                                     |
| -        | 71.3±4μs                      | 37.6±0.4μs                              |    0.53 | converters.ConverterBenchmarks.time_dag_to_circuit(1, 8)                                                        |
| -        | 30.0±0.2ms                    | 13.1±0.2ms                              |    0.44 | converters.ConverterBenchmarks.time_dag_to_circuit(1, 8192)                                                     |
| -        | 3.66±0.03ms                   | 2.10±0.05ms                             |    0.57 | converters.ConverterBenchmarks.time_dag_to_circuit(14, 128)                                                     |
| -        | 59.7±0.5ms                    | 33.5±0.8ms                              |    0.56 | converters.ConverterBenchmarks.time_dag_to_circuit(14, 2048)                                                    |
| -        | 377±50μs                      | 247±7μs                                 |    0.65 | converters.ConverterBenchmarks.time_dag_to_circuit(14, 8)                                                       |
| -        | 787±7μs                       | 450±20μs                                |    0.57 | converters.ConverterBenchmarks.time_dag_to_circuit(2, 128)                                                      |
| -        | 12.3±0.3ms                    | 5.88±0.08ms                             |    0.48 | converters.ConverterBenchmarks.time_dag_to_circuit(2, 2048)                                                     |
| -        | 92.3±2μs                      | 57.7±1μs                                |    0.63 | converters.ConverterBenchmarks.time_dag_to_circuit(2, 8)                                                        |
| -        | 48.6±0.8ms                    | 23.5±0.7ms                              |    0.48 | converters.ConverterBenchmarks.time_dag_to_circuit(2, 8192)                                                     |
| -        | 5.31±0.2ms                    | 2.99±0.06ms                             |    0.56 | converters.ConverterBenchmarks.time_dag_to_circuit(20, 128)                                                     |
| -        | 474±10μs                      | 323±3μs                                 |    0.68 | converters.ConverterBenchmarks.time_dag_to_circuit(20, 8)                                                       |
| -        | 8.54±0.2ms                    | 4.81±0.2ms                              |    0.56 | converters.ConverterBenchmarks.time_dag_to_circuit(32, 128)                                                     |
| -        | 804±20μs                      | 539±20μs                                |    0.67 | converters.ConverterBenchmarks.time_dag_to_circuit(32, 8)                                                       |
| -        | 1.54±0.04ms                   | 799±40μs                                |    0.52 | converters.ConverterBenchmarks.time_dag_to_circuit(5, 128)                                                      |
| -        | 23.3±0.6ms                    | 12.2±0.2ms                              |    0.53 | converters.ConverterBenchmarks.time_dag_to_circuit(5, 2048)                                                     |
| -        | 160±2μs                       | 107±6μs                                 |    0.67 | converters.ConverterBenchmarks.time_dag_to_circuit(5, 8)                                                        |
| -        | 92.6±4ms                      | 50.6±1ms                                |    0.55 | converters.ConverterBenchmarks.time_dag_to_circuit(5, 8192)                                                     |
| -        | 14.3±0.4ms                    | 8.46±0.2ms                              |    0.59 | converters.ConverterBenchmarks.time_dag_to_circuit(53, 128)                                                     |
| -        | 1.19±0.01ms                   | 873±10μs                                |    0.73 | converters.ConverterBenchmarks.time_dag_to_circuit(53, 8)                                                       |
| -        | 2.31±0.1ms                    | 1.35±0.05ms                             |    0.59 | converters.ConverterBenchmarks.time_dag_to_circuit(8, 128)                                                      |
| -        | 35.0±1ms                      | 18.8±0.2ms                              |    0.54 | converters.ConverterBenchmarks.time_dag_to_circuit(8, 2048)                                                     |
| -        | 223±30μs                      | 153±1μs                                 |    0.69 | converters.ConverterBenchmarks.time_dag_to_circuit(8, 8)                                                        |
| -        | 140±6ms                       | 79.4±4ms                                |    0.57 | converters.ConverterBenchmarks.time_dag_to_circuit(8, 8192)                                                     |
| -        | 57.0±2ms                      | 40.5±1ms                                |    0.71 | passes.MultipleBasisPassBenchmarks.time_optimize_1q_decompose(14, 1024, ['rx', 'ry', 'rz', 'r', 'rxx', 'id'])   |
| -        | 60.9±4ms                      | 43.3±0.4ms                              |    0.71 | passes.MultipleBasisPassBenchmarks.time_optimize_1q_decompose(14, 1024, ['rz', 'x', 'sx', 'cx', 'id'])          |
| -        | 49.5±0.8ms                    | 27.3±0.4ms                              |    0.55 | passes.MultipleBasisPassBenchmarks.time_optimize_1q_decompose(14, 1024, ['u', 'cx', 'id'])                      |
| -        | 75.3±0.5ms                    | 58.4±3ms                                |    0.78 | passes.MultipleBasisPassBenchmarks.time_optimize_1q_decompose(20, 1024, ['rx', 'ry', 'rz', 'r', 'rxx', 'id'])   |
| -        | 80.8±1ms                      | 61.7±2ms                                |    0.76 | passes.MultipleBasisPassBenchmarks.time_optimize_1q_decompose(20, 1024, ['rz', 'x', 'sx', 'cx', 'id'])          |
| -        | 68.2±2ms                      | 55.8±2ms                                |    0.82 | passes.MultipleBasisPassBenchmarks.time_optimize_1q_decompose(20, 1024, ['u', 'cx', 'id'])                      |
| -        | 26.2±1ms                      | 12.2±0.1ms                              |    0.47 | passes.MultipleBasisPassBenchmarks.time_optimize_1q_decompose(5, 1024, ['rx', 'ry', 'rz', 'r', 'rxx', 'id'])    |
| -        | 27.8±2ms                      | 10.6±0.06ms                             |    0.38 | passes.MultipleBasisPassBenchmarks.time_optimize_1q_decompose(5, 1024, ['rz', 'x', 'sx', 'cx', 'id'])           |
| -        | 17.0±2ms                      | 9.31±0.5ms                              |    0.55 | passes.MultipleBasisPassBenchmarks.time_optimize_1q_decompose(5, 1024, ['u', 'cx', 'id'])                       |
| -        | 6.65±0.5ms                    | 5.26±0.09ms                             |    0.79 | passes.PassBenchmarks.time_merge_adjacent_barriers(20, 1024)                                                    |
| -        | 46.5±1ms                      | 35.3±0.6ms                              |    0.76 | quantum_info.CliffordDecomposeBench.time_decompose('1,1000')                                                    |
| -        | 350±4ms                       | 3.34±0.1ms                              |    0.01 | quantum_info.CliffordDecomposeBench.time_decompose('4,50')                                                      |
| -        | 106±2ms                       | 856±50μs                                |    0.01 | quantum_info.CliffordDecomposeBench.time_decompose('5,10')                                                      |
| -        | 273±7ms                       | 224±7ms                                 |    0.82 | quantum_info.RandomCnotDihedralBench.time_random_cnotdihedral('1,2000')                                         |
| -        | 246±5ms                       | 174±3ms                                 |    0.71 | quantum_info.RandomCnotDihedralBench.time_random_cnotdihedral('2,1500')                                         |
| -        | 222±2ms                       | 140±1ms                                 |    0.63 | quantum_info.RandomCnotDihedralBench.time_random_cnotdihedral('3,1200')                                         |
| -        | 211±5ms                       | 117±1ms                                 |    0.55 | quantum_info.RandomCnotDihedralBench.time_random_cnotdihedral('4,1000')                                         |
| -        | 187±3ms                       | 96.7±5ms                                |    0.52 | quantum_info.RandomCnotDihedralBench.time_random_cnotdihedral('5,800')                                          |
| -        | 187±4ms                       | 86.9±3ms                                |    0.47 | quantum_info.RandomCnotDihedralBench.time_random_cnotdihedral('6,700')                                          |
| -        | 547                           | 490                                     |    0.9  | quantum_volume.LargeQuantumVolumeMappingTrackBench.track_depth_sabre_swap(115, 10, 'lookahead')                 |
| -        | 104±2ms                       | 90.9±0.7ms                              |    0.88 | quantum_volume.QuantumVolumeBenchmark.time_ibmq_backend_transpile(14, 'translator')                             |
| -        | 369±8ms                       | 295±10ms                                |    0.8  | quantum_volume.QuantumVolumeBenchmark.time_ibmq_backend_transpile(20, 'synthesis')                              |
| -        | 702±20ms                      | 584±20ms                                |    0.83 | quantum_volume.QuantumVolumeBenchmark.time_ibmq_backend_transpile(27, 'synthesis')                              |
| -        | 376±4ms                       | 330±4ms                                 |    0.88 | quantum_volume.QuantumVolumeBenchmark.time_ibmq_backend_transpile(27, 'translator')                             |
| -        | 50.5±2ms                      | 38.3±0.6ms                              |    0.76 | quantum_volume.QuantumVolumeBenchmark.time_ibmq_backend_transpile(8, 'synthesis')                               |
| -        | 394                           | 328                                     |    0.83 | queko.QUEKOTranspilerBench.track_depth_bntf_optimal_depth_25(1, 'sabre')                                        |
| -        | 285                           | 233                                     |    0.82 | queko.QUEKOTranspilerBench.track_depth_bntf_optimal_depth_25(2, 'sabre')                                        |
| -        | 370                           | 281                                     |    0.76 | queko.QUEKOTranspilerBench.track_depth_bss_optimal_depth_100(1, 'sabre')                                        |
| -        | 360                           | 297                                     |    0.82 | queko.QUEKOTranspilerBench.track_depth_bss_optimal_depth_100(2, 'sabre')                                        |
| -        | 1.34±0.02ms                   | 884±8μs                                 |    0.66 | ripple_adder.RippleAdderConstruction.time_build_ripple_adder(10)                                                |
| -        | 14.2±2ms                      | 8.11±0.1ms                              |    0.57 | ripple_adder.RippleAdderConstruction.time_build_ripple_adder(100)                                               |
| -        | 24.4±0.4ms                    | 17.4±1ms                                |    0.71 | ripple_adder.RippleAdderConstruction.time_build_ripple_adder(200)                                               |
| -        | 6.25±0.08ms                   | 4.08±0.08ms                             |    0.65 | ripple_adder.RippleAdderConstruction.time_build_ripple_adder(50)                                                |
| -        | 62.3±0.6ms                    | 40.7±2ms                                |    0.65 | ripple_adder.RippleAdderConstruction.time_build_ripple_adder(500)                                               |
| -        | 28                            | 17                                      |    0.61 | statepreparation.StatePreparationTranspileBench.track_cnot_counts_after_mapping_to_ibmq_16_melbourne(4)         |
| -        | 79                            | 47                                      |    0.59 | statepreparation.StatePreparationTranspileBench.track_cnot_counts_after_mapping_to_ibmq_16_melbourne(5)         |
| -        | 186                           | 111                                     |    0.6  | statepreparation.StatePreparationTranspileBench.track_cnot_counts_after_mapping_to_ibmq_16_melbourne(6)         |
| -        | 411                           | 231                                     |    0.56 | statepreparation.StatePreparationTranspileBench.track_cnot_counts_after_mapping_to_ibmq_16_melbourne(7)         |
| -        | 872                           | 460                                     |    0.53 | statepreparation.StatePreparationTranspileBench.track_cnot_counts_after_mapping_to_ibmq_16_melbourne(8)         |
| -        | 132±3ms                       | 111±0.8ms                               |    0.84 | transpiler_levels.TranspilerLevelBenchmarks.time_transpile_from_large_qasm(1)                                   |
| -        | 174±10ms                      | 145±0.8ms                               |    0.83 | transpiler_levels.TranspilerLevelBenchmarks.time_transpile_from_large_qasm_backend_with_prop(1)                 |
| -        | 336                           | 304                                     |    0.9  | transpiler_levels.TranspilerLevelBenchmarks.track_depth_transpile_qv_14_x_14(1)                                 |
| -        | 110±2ms                       | 93.6±3ms                                |    0.85 | transpiler_qualitative.TranspilerQualitativeBench.time_transpile_time_cnt3_5_179(2, 'sabre', 'dense')           |
| -        | 204±7ms                       | 169±1ms                                 |    0.83 | transpiler_qualitative.TranspilerQualitativeBench.time_transpile_time_cnt3_5_179(2, 'stochastic', 'sabre')      |
| -        | 280±2ms                       | 232±1ms                                 |    0.83 | transpiler_qualitative.TranspilerQualitativeBench.time_transpile_time_cnt3_5_179(3, 'stochastic', 'dense')      |
| -        | 235±3ms                       | 198±1ms                                 |    0.84 | transpiler_qualitative.TranspilerQualitativeBench.time_transpile_time_cnt3_5_179(3, 'stochastic', 'sabre')      |
| -        | 2582                          | 1954                                    |    0.76 | utility_scale.UtilityScaleBenchmarks.track_qft_depth('cx')                                                      |
| -        | 2582                          | 1954                                    |    0.76 | utility_scale.UtilityScaleBenchmarks.track_qft_depth('cz')                                                      |
| -        | 2582                          | 1954                                    |    0.76 | utility_scale.UtilityScaleBenchmarks.track_qft_depth('ecr')                                                     |
| Change   | Before [7d29dc1b] <1.1.0^0>   | After [d9e31ed5] <repack-instruction>   | Ratio   | Benchmark (Parameter)                                                                                           |
|----------|-------------------------------|-----------------------------------------|---------|-----------------------------------------------------------------------------------------------------------------|
| +        | 85.3±3ms                      | 143±4ms                                 | 1.68    | assembler.AssemblerBenchmarks.time_assemble_circuit(8, 4096, 1)                                                 |
| +        | 1.50±0.05ms                   | 2.61±0.02ms                             | 1.73    | circuit_construction.ParameterizedCircuitBindBench.time_bind_params(20, 128, 128)                               |
| +        | 1.19±0.02ms                   | 2.69±0.02ms                             | 2.27    | circuit_construction.ParameterizedCircuitBindBench.time_bind_params(20, 128, 8)                                 |
| +        | 1.16±0.04s                    | 2.13±0.03s                              | 1.84    | circuit_construction.ParameterizedCircuitBindBench.time_bind_params(20, 131072, 128)                            |
| +        | 1.52±0.02s                    | 2.47±0.01s                              | 1.62    | circuit_construction.ParameterizedCircuitBindBench.time_bind_params(20, 131072, 131072)                         |
| +        | 1.07±0.02s                    | 2.21±0.07s                              | 2.06    | circuit_construction.ParameterizedCircuitBindBench.time_bind_params(20, 131072, 2048)                           |
| +        | 1.13±0.01s                    | 2.25±0.03s                              | 1.99    | circuit_construction.ParameterizedCircuitBindBench.time_bind_params(20, 131072, 32768)                          |
| +        | 1.12±0.01s                    | 2.17±0.03s                              | 1.93    | circuit_construction.ParameterizedCircuitBindBench.time_bind_params(20, 131072, 8)                              |
| +        | 1.06±0.01s                    | 2.14±0.01s                              | 2.02    | circuit_construction.ParameterizedCircuitBindBench.time_bind_params(20, 131072, 8192)                           |
| +        | 15.6±0.2ms                    | 31.7±0.3ms                              | 2.03    | circuit_construction.ParameterizedCircuitBindBench.time_bind_params(20, 2048, 128)                              |
| +        | 22.4±1ms                      | 35.3±0.2ms                              | 1.57    | circuit_construction.ParameterizedCircuitBindBench.time_bind_params(20, 2048, 2048)                             |
| +        | 15.2±0.6ms                    | 33.7±2ms                                | 2.21    | circuit_construction.ParameterizedCircuitBindBench.time_bind_params(20, 2048, 8)                                |
| +        | 270±6ms                       | 535±10ms                                | 1.98    | circuit_construction.ParameterizedCircuitBindBench.time_bind_params(20, 32768, 128)                             |
| +        | 264±10ms                      | 522±10ms                                | 1.98    | circuit_construction.ParameterizedCircuitBindBench.time_bind_params(20, 32768, 2048)                            |
| +        | 370±10ms                      | 594±9ms                                 | 1.61    | circuit_construction.ParameterizedCircuitBindBench.time_bind_params(20, 32768, 32768)                           |
| +        | 271±10ms                      | 529±10ms                                | 1.95    | circuit_construction.ParameterizedCircuitBindBench.time_bind_params(20, 32768, 8)                               |
| +        | 274±3ms                       | 516±8ms                                 | 1.88    | circuit_construction.ParameterizedCircuitBindBench.time_bind_params(20, 32768, 8192)                            |
| +        | 347±5μs                       | 666±6μs                                 | 1.92    | circuit_construction.ParameterizedCircuitBindBench.time_bind_params(20, 8, 8)                                   |
| +        | 63.5±2ms                      | 133±3ms                                 | 2.09    | circuit_construction.ParameterizedCircuitBindBench.time_bind_params(20, 8192, 128)                              |
| +        | 67.1±2ms                      | 134±1ms                                 | 2.00    | circuit_construction.ParameterizedCircuitBindBench.time_bind_params(20, 8192, 2048)                             |
| +        | 61.6±2ms                      | 128±1ms                                 | 2.07    | circuit_construction.ParameterizedCircuitBindBench.time_bind_params(20, 8192, 8)                                |
| +        | 87.3±2ms                      | 148±3ms                                 | 1.70    | circuit_construction.ParameterizedCircuitBindBench.time_bind_params(20, 8192, 8192)                             |
| +        | 247±10μs                      | 315±3μs                                 | 1.27    | converters.ConverterBenchmarks.time_circuit_to_instruction(14, 8)                                               |
| +        | 431±7μs                       | 555±20μs                                | 1.29    | converters.ConverterBenchmarks.time_circuit_to_instruction(2, 128)                                              |
| +        | 2.10±0.02ms                   | 2.35±0.1ms                              | 1.12    | converters.ConverterBenchmarks.time_circuit_to_instruction(20, 128)                                             |
| +        | 336±4μs                       | 392±7μs                                 | 1.17    | converters.ConverterBenchmarks.time_circuit_to_instruction(20, 8)                                               |
| +        | 56.2±2ms                      | 71.8±1ms                                | 1.28    | mapping_passes.PassBenchmarks.time_apply_layout(14, 1024)                                                       |
| +        | 89.0±2ms                      | 109±0.7ms                               | 1.22    | mapping_passes.PassBenchmarks.time_apply_layout(20, 1024)                                                       |
| +        | 19.5±0.6ms                    | 25.2±0.2ms                              | 1.29    | mapping_passes.PassBenchmarks.time_apply_layout(5, 1024)                                                        |
| +        | 1.62±0.03ms                   | 2.04±0.03ms                             | 1.26    | mapping_passes.PassBenchmarks.time_check_map(14, 1024)                                                          |
| +        | 2.42±0.07ms                   | 3.01±0.1ms                              | 1.25    | mapping_passes.PassBenchmarks.time_check_map(20, 1024)                                                          |
| +        | 6.34±0.08ms                   | 7.63±0.2ms                              | 1.20    | mapping_passes.PassBenchmarks.time_layout_2q_distance(20, 1024)                                                 |
| +        | 1.54±0.07ms                   | 1.81±0.05ms                             | 1.18    | mapping_passes.PassBenchmarks.time_layout_2q_distance(5, 1024)                                                  |
| +        | 281±2ms                       | 343±10ms                                | 1.22    | mapping_passes.PassBenchmarks.time_sabre_layout(14, 1024)                                                       |
| +        | 480±2ms                       | 573±6ms                                 | 1.19    | mapping_passes.PassBenchmarks.time_sabre_layout(20, 1024)                                                       |
| +        | 68.8±0.5ms                    | 83.2±3ms                                | 1.21    | mapping_passes.PassBenchmarks.time_sabre_layout(5, 1024)                                                        |
| +        | 229±4ms                       | 266±5ms                                 | 1.16    | mapping_passes.PassBenchmarks.time_sabre_swap(20, 1024)                                                         |
| +        | 28.8±0.1ms                    | 35.3±1ms                                | 1.22    | mapping_passes.RoutedPassBenchmarks.time_check_map(20, 1024)                                                    |
| +        | 3.67±0.05ms                   | 4.48±0.06ms                             | 1.22    | mapping_passes.RoutedPassBenchmarks.time_check_map(5, 1024)                                                     |
| +        | 17.1±0.2ms                    | 19.9±0.2ms                              | 1.17    | mapping_passes.RoutedPassBenchmarks.time_gate_direction(14, 1024)                                               |
| +        | 29.5±0.3ms                    | 34.2±0.3ms                              | 1.16    | mapping_passes.RoutedPassBenchmarks.time_gate_direction(20, 1024)                                               |
| +        | 45.2±1ms                      | 61.5±2ms                                | 1.36    | passes.MultiQBlockPassBenchmarks.time_collect_multiq_block(14, 1024, 1)                                         |
| +        | 46.1±2ms                      | 66.9±2ms                                | 1.45    | passes.MultiQBlockPassBenchmarks.time_collect_multiq_block(14, 1024, 2)                                         |
| +        | 52.7±3ms                      | 66.6±0.4ms                              | 1.26    | passes.MultiQBlockPassBenchmarks.time_collect_multiq_block(14, 1024, 3)                                         |
| +        | 48.3±0.5ms                    | 66.8±1ms                                | 1.38    | passes.MultiQBlockPassBenchmarks.time_collect_multiq_block(14, 1024, 4)                                         |
| +        | 46.9±1ms                      | 64.7±0.5ms                              | 1.38    | passes.MultiQBlockPassBenchmarks.time_collect_multiq_block(14, 1024, 5)                                         |
| +        | 66.4±3ms                      | 88.5±1ms                                | 1.33    | passes.MultiQBlockPassBenchmarks.time_collect_multiq_block(20, 1024, 1)                                         |
| +        | 67.3±4ms                      | 92.5±0.9ms                              | 1.38    | passes.MultiQBlockPassBenchmarks.time_collect_multiq_block(20, 1024, 2)                                         |
| +        | 72.6±2ms                      | 101±6ms                                 | 1.39    | passes.MultiQBlockPassBenchmarks.time_collect_multiq_block(20, 1024, 3)                                         |
| +        | 69.5±1ms                      | 94.4±2ms                                | 1.36    | passes.MultiQBlockPassBenchmarks.time_collect_multiq_block(20, 1024, 4)                                         |
| +        | 66.7±2ms                      | 93.6±2ms                                | 1.40    | passes.MultiQBlockPassBenchmarks.time_collect_multiq_block(20, 1024, 5)                                         |
| +        | 16.4±0.9ms                    | 22.4±0.2ms                              | 1.37    | passes.MultiQBlockPassBenchmarks.time_collect_multiq_block(5, 1024, 1)                                          |
| +        | 16.4±0.4ms                    | 23.3±0.2ms                              | 1.42    | passes.MultiQBlockPassBenchmarks.time_collect_multiq_block(5, 1024, 2)                                          |
| +        | 18.2±1ms                      | 23.6±0.2ms                              | 1.30    | passes.MultiQBlockPassBenchmarks.time_collect_multiq_block(5, 1024, 3)                                          |
| +        | 15.9±0.3ms                    | 22.9±0.2ms                              | 1.44    | passes.MultiQBlockPassBenchmarks.time_collect_multiq_block(5, 1024, 4)                                          |
| +        | 15.0±0.3ms                    | 21.3±0.4ms                              | 1.42    | passes.MultiQBlockPassBenchmarks.time_collect_multiq_block(5, 1024, 5)                                          |
| +        | 976±8ms                       | 1.25±0.01s                              | 1.28    | passes.MultipleBasisPassBenchmarks.time_basis_translator(14, 1024, ['rx', 'ry', 'rz', 'r', 'rxx', 'id'])        |
| +        | 709±20ms                      | 856±9ms                                 | 1.21    | passes.MultipleBasisPassBenchmarks.time_basis_translator(14, 1024, ['rz', 'x', 'sx', 'cx', 'id'])               |
| +        | 578±9ms                       | 725±10ms                                | 1.25    | passes.MultipleBasisPassBenchmarks.time_basis_translator(14, 1024, ['u', 'cx', 'id'])                           |
| +        | 1.39±0.03s                    | 1.77±0.03s                              | 1.27    | passes.MultipleBasisPassBenchmarks.time_basis_translator(20, 1024, ['rx', 'ry', 'rz', 'r', 'rxx', 'id'])        |
| +        | 990±10ms                      | 1.18±0.02s                              | 1.20    | passes.MultipleBasisPassBenchmarks.time_basis_translator(20, 1024, ['rz', 'x', 'sx', 'cx', 'id'])               |
| +        | 830±20ms                      | 1.03±0.01s                              | 1.24    | passes.MultipleBasisPassBenchmarks.time_basis_translator(20, 1024, ['u', 'cx', 'id'])                           |
| +        | 343±5ms                       | 430±4ms                                 | 1.25    | passes.MultipleBasisPassBenchmarks.time_basis_translator(5, 1024, ['rx', 'ry', 'rz', 'r', 'rxx', 'id'])         |
| +        | 219±1ms                       | 267±2ms                                 | 1.22    | passes.MultipleBasisPassBenchmarks.time_basis_translator(5, 1024, ['u', 'cx', 'id'])                            |
| +        | 672±7ms                       | 798±6ms                                 | 1.19    | passes.MultipleBasisPassBenchmarks.time_optimize_1q_commutation(14, 1024, ['rx', 'ry', 'rz', 'r', 'rxx', 'id']) |
| +        | 726±10ms                      | 866±20ms                                | 1.19    | passes.MultipleBasisPassBenchmarks.time_optimize_1q_commutation(14, 1024, ['rz', 'x', 'sx', 'cx', 'id'])        |
| +        | 652±8ms                       | 779±5ms                                 | 1.20    | passes.MultipleBasisPassBenchmarks.time_optimize_1q_commutation(14, 1024, ['u', 'cx', 'id'])                    |
| +        | 1.07±0.03s                    | 1.25±0.02s                              | 1.17    | passes.MultipleBasisPassBenchmarks.time_optimize_1q_commutation(20, 1024, ['rx', 'ry', 'rz', 'r', 'rxx', 'id']) |
| +        | 1.14±0.01s                    | 1.35±0.02s                              | 1.18    | passes.MultipleBasisPassBenchmarks.time_optimize_1q_commutation(20, 1024, ['rz', 'x', 'sx', 'cx', 'id'])        |
| +        | 1.04±0.01s                    | 1.25±0.03s                              | 1.20    | passes.MultipleBasisPassBenchmarks.time_optimize_1q_commutation(20, 1024, ['u', 'cx', 'id'])                    |
| +        | 253±2ms                       | 301±10ms                                | 1.19    | passes.MultipleBasisPassBenchmarks.time_optimize_1q_commutation(5, 1024, ['rz', 'x', 'sx', 'cx', 'id'])         |
| +        | 225±1ms                       | 273±7ms                                 | 1.22    | passes.MultipleBasisPassBenchmarks.time_optimize_1q_commutation(5, 1024, ['u', 'cx', 'id'])                     |
| +        | 10.5±0.1ms                    | 28.9±3ms                                | 2.75    | passes.PassBenchmarks.time_barrier_before_final_measurements(14, 1024)                                          |
| +        | 16.9±0.3ms                    | 44.8±0.3ms                              | 2.66    | passes.PassBenchmarks.time_barrier_before_final_measurements(20, 1024)                                          |
| +        | 4.54±0.07ms                   | 7.84±0.2ms                              | 1.73    | passes.PassBenchmarks.time_barrier_before_final_measurements(5, 1024)                                           |
| +        | 11.8±0.4ms                    | 27.0±0.2ms                              | 2.29    | passes.PassBenchmarks.time_collect_2q_blocks(14, 1024)                                                          |
| +        | 17.8±0.5ms                    | 40.8±0.7ms                              | 2.29    | passes.PassBenchmarks.time_collect_2q_blocks(20, 1024)                                                          |
| +        | 4.08±0.2ms                    | 6.57±0.4ms                              | 1.61    | passes.PassBenchmarks.time_collect_2q_blocks(5, 1024)                                                           |
| +        | 715±10μs                      | 933±40μs                                | 1.31    | passes.PassBenchmarks.time_count_ops_longest_path(5, 1024)                                                      |
| +        | 2.68±0.07ms                   | 6.48±0.2ms                              | 2.42    | passes.PassBenchmarks.time_cx_cancellation(14, 1024)                                                            |
| +        | 4.25±0.09ms                   | 11.5±0.6ms                              | 2.70    | passes.PassBenchmarks.time_cx_cancellation(20, 1024)                                                            |
| +        | 976±20μs                      | 1.79±0.06ms                             | 1.83    | passes.PassBenchmarks.time_cx_cancellation(5, 1024)                                                             |
| +        | 924±20ms                      | 1.04±0.03s                              | 1.13    | passes.PassBenchmarks.time_decompose_pass(14, 1024)                                                             |
| +        | 1.42±0.01s                    | 1.62±0.02s                              | 1.14    | passes.PassBenchmarks.time_decompose_pass(20, 1024)                                                             |
| +        | 298±7ms                       | 335±10ms                                | 1.13    | passes.PassBenchmarks.time_decompose_pass(5, 1024)                                                              |
| +        | 532±10ms                      | 611±7ms                                 | 1.15    | passes.PassBenchmarks.time_optimize_swap_before_measure(14, 1024)                                               |
| +        | 3.38±0.05ms                   | 8.07±0.07ms                             | 2.39    | passes.PassBenchmarks.time_remove_barriers(14, 1024)                                                            |
| +        | 4.76±0.1ms                    | 15.2±0.9ms                              | 3.19    | passes.PassBenchmarks.time_remove_barriers(20, 1024)                                                            |
| +        | 1.30±0.03ms                   | 2.28±0.02ms                             | 1.76    | passes.PassBenchmarks.time_remove_barriers(5, 1024)                                                             |
| +        | 4.08±0.1ms                    | 8.74±0.2ms                              | 2.14    | passes.PassBenchmarks.time_remove_diagonal_gates_before_measurement(14, 1024)                                   |
| +        | 6.11±0.3ms                    | 15.8±0.5ms                              | 2.58    | passes.PassBenchmarks.time_remove_diagonal_gates_before_measurement(20, 1024)                                   |
| +        | 1.64±0.03ms                   | 2.74±0.06ms                             | 1.67    | passes.PassBenchmarks.time_remove_diagonal_gates_before_measurement(5, 1024)                                    |
| +        | 2.25±0.07ms                   | 5.06±0.2ms                              | 2.24    | passes.PassBenchmarks.time_remove_reset_in_zero_state(14, 1024)                                                 |
| +        | 3.05±0.1ms                    | 9.55±0.1ms                              | 3.13    | passes.PassBenchmarks.time_remove_reset_in_zero_state(20, 1024)                                                 |
| +        | 924±10μs                      | 1.43±0.01ms                             | 1.55    | passes.PassBenchmarks.time_remove_reset_in_zero_state(5, 1024)                                                  |
| +        | 797±10ms                      | 928±10ms                                | 1.16    | passes.PassBenchmarks.time_unroll_3q_or_more(14, 1024)                                                          |
| +        | 1.25±0.05s                    | 1.43±0.01s                              | 1.15    | passes.PassBenchmarks.time_unroll_3q_or_more(20, 1024)                                                          |
| +        | 211±2ms                       | 249±4ms                                 | 1.18    | passes.PassBenchmarks.time_unroll_3q_or_more(5, 1024)                                                           |
| +        | 131±3ms                       | 209±2ms                                 | 1.60    | qft.LargeQFTMappingTimeBench.time_sabre_swap(115, 'decay')                                                      |
| +        | 135±4ms                       | 214±4ms                                 | 1.58    | qft.LargeQFTMappingTimeBench.time_sabre_swap(115, 'lookahead')                                                  |
| +        | 6.56±0.1ms                    | 7.68±0.1ms                              | 1.17    | qft.QftTranspileBench.time_ibmq_backend_transpile(2)                                                            |
| +        | 3.72±0.01s                    | 5.54±0.01s                              | 1.49    | quantum_volume.LargeQuantumVolumeMappingTimeBench.time_sabre_swap(1081, 10, 'decay')                            |
| +        | 30.1±2ms                      | 35.4±2ms                                | 1.18    | quantum_volume.LargeQuantumVolumeMappingTimeBench.time_sabre_swap(115, 10, 'lookahead')                         |
| +        | 264±2ms                       | 301±4ms                                 | 1.14    | quantum_volume.LargeQuantumVolumeMappingTimeBench.time_sabre_swap(115, 100, 'lookahead')                        |
| +        | 361±20ms                      | 431±6ms                                 | 1.19    | quantum_volume.LargeQuantumVolumeMappingTimeBench.time_sabre_swap(409, 10, 'decay')                             |
| +        | 374±5ms                       | 828±10ms                                | 2.21    | quantum_volume.LargeQuantumVolumeMappingTimeBench.time_sabre_swap(409, 10, 'lookahead')                         |
| +        | 3945                          | 4526                                    | 1.15    | quantum_volume.LargeQuantumVolumeMappingTrackBench.track_depth_sabre_swap(409, 10, 'lookahead')                 |
| +        | 217448                        | 258126                                  | 1.19    | quantum_volume.LargeQuantumVolumeMappingTrackBench.track_size_sabre_swap(1081, 10, 'decay')                     |
| +        | 47894                         | 70053                                   | 1.46    | quantum_volume.LargeQuantumVolumeMappingTrackBench.track_size_sabre_swap(409, 10, 'lookahead')                  |
| +        | 18.1±0.1ms                    | 24.0±0.6ms                              | 1.33    | queko.QUEKOTranspilerBench.time_transpile_bigd(0, 'sabre')                                                      |
| +        | 40.5±0.3ms                    | 44.7±0.7ms                              | 1.11    | queko.QUEKOTranspilerBench.time_transpile_bigd(0, None)                                                         |
| +        | 160±3ms                       | 192±4ms                                 | 1.20    | queko.QUEKOTranspilerBench.time_transpile_bntf(0, 'sabre')                                                      |
| +        | 370±5ms                       | 455±5ms                                 | 1.23    | queko.QUEKOTranspilerBench.time_transpile_bntf(0, None)                                                         |
| +        | 303±3ms                       | 388±4ms                                 | 1.28    | queko.QUEKOTranspilerBench.time_transpile_bntf(2, 'sabre')                                                      |
| +        | 403±10ms                      | 486±5ms                                 | 1.21    | queko.QUEKOTranspilerBench.time_transpile_bntf(3, 'sabre')                                                      |
| +        | 149±2ms                       | 177±2ms                                 | 1.19    | queko.QUEKOTranspilerBench.time_transpile_bss(0, 'sabre')                                                       |
| +        | 1.69±0.01s                    | 1.93±0.01s                              | 1.14    | queko.QUEKOTranspilerBench.time_transpile_bss(0, None)                                                          |
| +        | 602±10ms                      | 725±6ms                                 | 1.21    | queko.QUEKOTranspilerBench.time_transpile_bss(3, 'sabre')                                                       |
| +        | 672                           | 973                                     | 1.45    | queko.QUEKOTranspilerBench.track_depth_bntf_optimal_depth_25(0, 'sabre')                                        |
| +        | 200                           | 310                                     | 1.55    | queko.QUEKOTranspilerBench.track_depth_bntf_optimal_depth_25(3, 'sabre')                                        |
| +        | 261                           | 350                                     | 1.34    | queko.QUEKOTranspilerBench.track_depth_bss_optimal_depth_100(3, 'sabre')                                        |
| +        | 1.01±0.01s                    | 1.27±0.03s                              | 1.26    | scheduling_passes.SchedulingPassBenchmarks.time_alap_schedule_pass(10, 1000)                                    |
| +        | 504±10ms                      | 632±20ms                                | 1.25    | scheduling_passes.SchedulingPassBenchmarks.time_alap_schedule_pass(10, 500)                                     |
| +        | 1.37±0.02s                    | 1.73±0.02s                              | 1.26    | scheduling_passes.SchedulingPassBenchmarks.time_alap_schedule_pass(20, 500)                                     |
| +        | 403±5ms                       | 497±10ms                                | 1.23    | scheduling_passes.SchedulingPassBenchmarks.time_alap_schedule_pass(5, 1000)                                     |
| +        | 1.01±0.02s                    | 1.28±0.02s                              | 1.26    | scheduling_passes.SchedulingPassBenchmarks.time_asap_schedule_pass(10, 1000)                                    |
| +        | 502±10ms                      | 639±10ms                                | 1.27    | scheduling_passes.SchedulingPassBenchmarks.time_asap_schedule_pass(10, 500)                                     |
| +        | 1.37±0.01s                    | 1.74±0.03s                              | 1.27    | scheduling_passes.SchedulingPassBenchmarks.time_asap_schedule_pass(20, 500)                                     |
| +        | 405±8ms                       | 499±7ms                                 | 1.23    | scheduling_passes.SchedulingPassBenchmarks.time_asap_schedule_pass(5, 1000)                                     |
| +        | 206±10ms                      | 239±2ms                                 | 1.16    | scheduling_passes.SchedulingPassBenchmarks.time_asap_schedule_pass(5, 500)                                      |
| +        | 189±6ms                       | 317±10ms                                | 1.68    | scheduling_passes.SchedulingPassBenchmarks.time_time_unit_conversion_pass(10, 1000)                             |
| +        | 90.1±5ms                      | 149±5ms                                 | 1.65    | scheduling_passes.SchedulingPassBenchmarks.time_time_unit_conversion_pass(10, 500)                              |
| +        | 473±4ms                       | 755±5ms                                 | 1.60    | scheduling_passes.SchedulingPassBenchmarks.time_time_unit_conversion_pass(20, 1000)                             |
| +        | 245±7ms                       | 397±4ms                                 | 1.62    | scheduling_passes.SchedulingPassBenchmarks.time_time_unit_conversion_pass(20, 500)                              |
| +        | 73.2±1ms                      | 121±0.5ms                               | 1.66    | scheduling_passes.SchedulingPassBenchmarks.time_time_unit_conversion_pass(5, 1000)                              |
| +        | 36.0±0.8ms                    | 59.4±1ms                                | 1.65    | scheduling_passes.SchedulingPassBenchmarks.time_time_unit_conversion_pass(5, 500)                               |
| +        | 5.62±0.1ms                    | 6.49±1ms                                | 1.15    | transpiler_benchmarks.TranspilerBenchSuite.time_single_gate_compile                                             |
| +        | 129±1ms                       | 149±1ms                                 | 1.16    | transpiler_levels.TranspilerLevelBenchmarks.time_schedule_qv_14_x_14(0)                                         |
| +        | 74.7±0.4ms                    | 83.9±3ms                                | 1.12    | transpiler_levels.TranspilerLevelBenchmarks.time_transpile_from_large_qasm(0)                                   |
| +        | 224±2ms                       | 262±9ms                                 | 1.17    | transpiler_qualitative.TranspilerQualitativeBench.time_transpile_time_cnt3_5_180(2, 'sabre', 'sabre')           |
| +        | 271±4ms                       | 336±6ms                                 | 1.24    | transpiler_qualitative.TranspilerQualitativeBench.time_transpile_time_cnt3_5_180(3, 'sabre', 'sabre')           |
| +        | 11.4±0.2ms                    | 12.9±0.5ms                              | 1.13    | utility_scale.UtilityScaleBenchmarks.time_parse_qaoa_n100('cz')                                                 |
| +        | 40.0±0.3ms                    | 46.2±2ms                                | 1.16    | utility_scale.UtilityScaleBenchmarks.time_parse_square_heisenberg_n100('cz')                                    |
| !        | 29.0±0.08s                    | failed                                  | n/a     | utility_scale.UtilityScaleBenchmarks.time_qft('cz')                                                             |
| !        | 29.2±0.03s                    | failed                                  | n/a     | utility_scale.UtilityScaleBenchmarks.time_qft('ecr')                                                            |
```

**Comment by mtreinish** [comment]
I was a bit concerned by these numbers:

> | Change   | Before [7d29dc1b] <1.1.0^0>   | After [d9e31ed5] <repack-instruction>   | Ratio   | Benchmark (Parameter)                                                                                           > |
> |----------|-------------------------------|-----------------------------------------|---------|-----------------------------------------------------------------------------------------------------------------|
> | !        | 29.0±0.08s                    | failed                                  | n/a     | utility_scale.UtilityScaleBenchmarks.time_qft('cz')                                                             > |
> | !        | 29.2±0.03s                    | failed                                  | n/a     | utility_scale.UtilityScaleBenchmarks.time_qft('ecr')        

since failed either indicates it is no longer running or more likely in this case we hit the 60sec timeout. So to validate I ran the utility benchmarks locally with this PR compared against 1.1.0:

```
Benchmarks that have improved:

| Change   |   Before [7d29dc1b] <1.1.0^0> |   After [a6cd6bb2] <repack-instruction> |   Ratio | Benchmark (Parameter)                                       |
|----------|-------------------------------|-----------------------------------------|---------|-------------------------------------------------------------|
| -        |                          2582 |                                    1954 |    0.76 | utility_scale.UtilityScaleBenchmarks.track_qft_depth('cx')  |
| -        |                          2582 |                                    1954 |    0.76 | utility_scale.UtilityScaleBenchmarks.track_qft_depth('cz')  |
| -        |                          2582 |                                    1954 |    0.76 | utility_scale.UtilityScaleBenchmarks.track_qft_depth('ecr') |

Benchmarks that have stayed the same:

| Change   | Before [7d29dc1b] <1.1.0^0>   | After [a6cd6bb2] <repack-instruction>   |   Ratio | Benchmark (Parameter)                                                     |
|----------|-------------------------------|-----------------------------------------|---------|---------------------------------------------------------------------------|
|          | 1.30±0s                       | 1.42±0s                                 |    1.1  | utility_scale.UtilityScaleBenchmarks.time_square_heisenberg('cx')         |
|          | 1.80±0.01s                    | 1.93±0.01s                              |    1.08 | utility_scale.UtilityScaleBenchmarks.time_square_heisenberg('ecr')        |
|          | 1.95±0.01s                    | 2.08±0.01s                              |    1.07 | utility_scale.UtilityScaleBenchmarks.time_square_heisenberg('cz')         |
|          | 1.13±0s                       | 1.15±0.01s                              |    1.03 | utility_scale.UtilityScaleBenchmarks.time_qaoa('cx')                      |
|          | 2.49±0.01s                    | 2.47±0.02s                              |    0.99 | utility_scale.UtilityScaleBenchmarks.time_qaoa('ecr')                     |
|          | 444                           | 435                                     |    0.98 | utility_scale.UtilityScaleBenchmarks.track_square_heisenberg_depth('cx')  |
|          | 444                           | 435                                     |    0.98 | utility_scale.UtilityScaleBenchmarks.track_square_heisenberg_depth('cz')  |
|          | 444                           | 435                                     |    0.98 | utility_scale.UtilityScaleBenchmarks.track_square_heisenberg_depth('ecr') |
|          | 3.00±0.02s                    | 2.91±0.03s                              |    0.97 | utility_scale.UtilityScaleBenchmarks.time_qaoa('cz')                      |
|          | 20.9±0.02s                    | 19.9±0.1s                               |    0.95 | utility_scale.UtilityScaleBenchmarks.time_qft('cx')                       |
|          | 23.8±0.02s                    | 22.6±0.02s                              |    0.95 | utility_scale.UtilityScaleBenchmarks.time_qft('ecr')                      |
|          | 23.8±0.1s                     | 22.4±0.09s                              |    0.94 | utility_scale.UtilityScaleBenchmarks.time_qft('cz')                       |
|          | 1607                          | 1483                                    |    0.92 | utility_scale.UtilityScaleBenchmarks.track_qaoa_depth('cx')               |
|          | 1622                          | 1488                                    |    0.92 | utility_scale.UtilityScaleBenchmarks.track_qaoa_depth('cz')               |
|          | 1622                          | 1488                                    |    0.92 | utility_scale.UtilityScaleBenchmarks.track_qaoa_depth('ecr')              |

Benchmarks that have got worse:

| Change   | Before [7d29dc1b] <1.1.0^0>   | After [a6cd6bb2] <repack-instruction>   |   Ratio | Benchmark (Parameter)                                                         |
|----------|-------------------------------|-----------------------------------------|---------|-------------------------------------------------------------------------------|
| +        | 32.1±0.2ms                    | 38.1±0.3ms                              |    1.19 | utility_scale.UtilityScaleBenchmarks.time_parse_square_heisenberg_n100('cz')  |
| +        | 9.18±0.1ms                    | 10.7±0.1ms                              |    1.17 | utility_scale.UtilityScaleBenchmarks.time_parse_qaoa_n100('cz')               |
| +        | 9.30±0.06ms                   | 10.8±0.1ms                              |    1.16 | utility_scale.UtilityScaleBenchmarks.time_parse_qaoa_n100('cx')               |
| +        | 99.8±2ms                      | 116±0.6ms                               |    1.16 | utility_scale.UtilityScaleBenchmarks.time_parse_qft_n100('cx')                |
| +        | 101±0.8ms                     | 117±0.2ms                               |    1.16 | utility_scale.UtilityScaleBenchmarks.time_parse_qft_n100('cz')                |
| +        | 32.5±0.3ms                    | 37.7±0.2ms                              |    1.16 | utility_scale.UtilityScaleBenchmarks.time_parse_square_heisenberg_n100('ecr') |
| +        | 101±0.9ms                     | 116±1ms                                 |    1.15 | utility_scale.UtilityScaleBenchmarks.time_parse_qft_n100('ecr')               |
| +        | 33.0±0.4ms                    | 37.8±0.2ms                              |    1.15 | utility_scale.UtilityScaleBenchmarks.time_parse_square_heisenberg_n100('cx')  |
| +        | 9.34±0.09ms                   | 10.7±0.04ms                             |    1.14 | utility_scale.UtilityScaleBenchmarks.time_parse_qaoa_n100('ecr')              |

SOME BENCHMARKS HAVE CHANGED SIGNIFICANTLY.
PERFORMANCE DECREASED.
```

So that failed result might be something tied to @jakelishman's local environment. Like it could be are old friend the medium allocator on MacOS with x86_64.

**Review by kevinhartman — DISMISSED** [review]
This looks excellent! It's nice to see your idea of using the low 3 bits of 8-byte aligned pointers to store the operation type enum come to fruition 😄. I'm also glad to see some cleanup of our Rust operation types and conversion to and from Python. The performance and memory improvements are also nice, ofc.

I think the impact this has on our work to port `DAGCircuit` to Rust should be fairly minimal.

I'm approving this, but holding off on queuing it for merge in case anyone else wants to take a look.

**Comment by jlapeyre** [comment]
I'd like look at it briefly @kevinhartman .

**Comment by jakelishman** [comment]
I've fixed the merge conflicts with #12659 in c4f299f18729bb72751f3971bb72cb28f9694f86, the process of which turned up a couple more ugly corners around conditional / otherwise non-standard "standard" gates during the conversion.  Notably: the use of `CircuitInstruction::new` was masking that we weren't propagating through the pycache in `CircuitData::__getitem__`, which meant that gates that were semi-standard (e.g. standard gates with labels, conditions, etc) were not being retained as `is` compatible even with caching on, when they should have been.

Previously, overzealous rejection of standard gates in `convert_py_to_operation_type` was masking this, by rejecting such gates, even though Rust space _does_ have the necessary representation.

*edit*: ugh, in the mean time, #12704 merged which invalidates the merge.

**Comment by jakelishman** [comment]
Ok, b5a3d9f161 should have fixed the merge conflict with #12704.

**Comment by jlapeyre** [comment]
fwiw, I also got no failures running a few parts of the asv set including the two failures above. Using Arch linux with an AMD processor.

**Comment by jakelishman** [comment]
It turns out that while asv's timeout is 60s, that includes all runs of a benchmark.  Since we have a minimum of 2 runs for those the cut-off is actually 30s - I increased the timeout locally and it was running them in ~30.9s on my laptop or something.

**Comment by jakelishman** [comment]
I've fixed two of the three no-cache test failures in [59d1fc0](https://github.com/Qiskit/qiskit/pull/12730/commits/59d1fc046fbe49ff63cc63a0ab7781b8dd7d71b4), but the last one isn't the fault of this PR (it just exacerbates an existing problem).  That's the problematic OQ3 exporter issue, as #12481 is trying to solve, but I don't think that PR will do the job, and this PR will make things worse.

I'll post a PR to fix the OQ3 thing separately, because it's a fairly large reworking of its symbol table (which as a side-effect will fix the bad output from parametric standard-library gates).

File: crates/circuit/src/packed_instruction.rs [hunk 1]
```diff
@@ -0,0 +1,497 @@
...
+    pub fn try_pointer(&self) -> Option<NonNull<()>> {
+        match self.discriminant() {
+            PackedOperationType::StandardGate => None,
+            PackedOperationType::Gate
+            | PackedOperationType::Instruction
+            | PackedOperationType::Operation => {
+                let ptr = (self.0 & Self::POINTER_MASK) as *mut ();
+                // SAFETY: `PackedOperation` can only be constructed from a pointer via `Box`, which
+                // is always non-null (except in the case that we're partway through a `Drop`).
+                Some(unsafe { NonNull::new_unchecked(ptr) })
```
Comment (jlapeyre) [inline crates/circuit/src/packed_instruction.rs:156]: Would something like this be more useful?
```suggestion
                Some(NonNull::new(ptr).expect("Qiskit bug: Expected a non-null pointer"))
```
In both cases, the function should always exit normally. But if the impossible does happen,  in the second case, the user sees it's a bug and not their fault.

File: crates/circuit/src/packed_instruction.rs [hunk 2]
```diff
@@ -0,0 +1,497 @@
...
+        ::bytemuck::checked::cast((self.0 & Self::DISCRIMINANT_MASK) as u8)
+    }
+
+    /// Get the contained pointer to the `PyGate`/`PyInstruction`/`PyOperation` that this object
+    /// contains.
+    ///
+    /// **Panics** if the object represents a standard gate; see `try_pointer`.
+    #[inline]
+    fn pointer(&self) -> NonNull<()> {
+        self.try_pointer().unwrap()
```
Comment (jlapeyre) [inline crates/circuit/src/packed_instruction.rs]: I lean toward the "always use `expect` instead of `unwrap`" camp. So something like this
```suggestion
        self.try_pointer()
            .expect("Qiskit bug: PackedOperation contains a StandardGate, expecting a pointer")
```
All the logic is very local, so it's unlikely the code is ever changed in a way that triggers this bug. But it also helps the reader of the code understand what's going on. Might even replace the comment.

File: crates/circuit/src/packed_instruction.rs [hunk 3]
```diff
@@ -0,0 +1,497 @@
...
+/// }
+/// ```
+///
+/// including all ownership semantics, except it bit-packs the enumeration into a single pointer.
+/// This works because `PyGate` (and friends) have an alignment of 8, so pointers to them always
+/// have the low three bits set to 0, and `StandardGate` has a width much smaller than a pointer.
+/// This lets us store the enum discriminant in the low data bits, and then type-pun a suitable
+/// bitmask on the contained value back into proper data.
+///
+/// Explicity, this is logical memory layout of `PackedOperation` on a 64-bit system, written out as
```
Comment (jlapeyre) [inline crates/circuit/src/packed_instruction.rs]: "Explicitly"

File: crates/circuit/src/packed_instruction.rs [hunk 4]
```diff
@@ -0,0 +1,497 @@
...
+    }
+
+    /// Get the contained `StandardGate`, if any.
+    #[inline]
+    pub fn try_standard_gate(&self) -> Option<StandardGate> {
+        match self.discriminant() {
+            PackedOperationType::StandardGate => ::bytemuck::checked::try_cast(
+                ((self.0 & Self::STANDARD_GATE_MASK) >> Self::DISCRIMINANT_BITS) as u8,
+            )
+            .ok(),
```
Comment (jlapeyre) [inline crates/circuit/src/packed_instruction.rs:178]: Following the same ideas as above, you could write
```suggestion
            PackedOperationType::StandardGate => Some(
                ::bytemuck::checked::try_cast(
                    ((self.0 & Self::STANDARD_GATE_MASK) >> Self::DISCRIMINANT_BITS) as u8,
                )
                .expect("Qiskit bug: Discriminant encodes no StandardGate"),
```
Again, an argument is that this helps the reader of the code even if the bug is never triggered.

Comment (jakelishman) [reply crates/circuit/src/packed_instruction.rs:178]: imo putting these `expect`s with messages that just say the same thing as the code is making the call sites noisier without helping debugging.  The standard panic includes the file and line number, so we can immediately track down the failing line, and this line of code clearly describes the same as the error (actually, even more than the message).

imo a good error message in one of these would say _why_ the assumptions are the way they are, not re-describe _what_ failed.  Here, the assumption is the basically the entire data representation, so I don't think it's especially helpful to add the noise.

File: crates/circuit/src/packed_instruction.rs (hunk 2 above)
Comment (jakelishman) [reply crates/circuit/src/packed_instruction.rs]: This kind of message is guessing at what's gone wrong - we wouldn't _know_ that it includes a standard gate at this point, just that `try_pointer` failed for some reason.  Were we to expand `PackedOperation` in the future, such as by using the extra 4 discriminants we have available to us to encode something else (for example, maybe we allow something like a custom downstream C / Rust project to have its own `StandardGate` table as a fifth option), the error could easily become out-of-date as well.

This function is entirely private; a user can't violate the assumptions, only Qiskit can do that to itself. If we've done that, we can't really predict _how_ we violated them, and this error message wouldn't help with debugging it, it just makes a one-line function into a noisier two.

(I possibly should have done `unsafe fn pointer(&self) -> NonNull<()> { unsafe { self.try_pointer().unwrap_unchecked() } }` with this - this is a fast path for when it's _known_ safe.)

File: crates/circuit/src/packed_instruction.rs (hunk 4 above)
Comment (jlapeyre) [reply crates/circuit/src/packed_instruction.rs:178]: I disagree. If it were up to me I'd make these changes or something else along these lines.  But I've already stated my arguments.

> imo a good error message in one of these would say why the assumptions 

I don't really follow, but if you think there's a better error message, that would be good. The messages I wrote are not the best or only choices.

I assumed that you wrote the code the way you wanted and wouldn't want to change it. But I thought it's important to make a record of my preference (it's not an uncommon preference). I don't judge it important enough for us to spend the effort debating it at present. Better to leave all of the code I commented on as is and move on.

Comment (jakelishman) [reply crates/circuit/src/packed_instruction.rs:178]: Just to clarify the "why" thing: consider a simpler example of our OQ3 importer hypothetically wanting to read and cache our vendored `stdgates.inc` file when the module initialises. We vendor it, so the file absolutely should exist. In that case, I'd write `File::open(...).expect("'stdgates.inc' should be vendored with Qiskit")` or similar. The panic still shows the line and the `Err` variant data (which is the _what_), but the message now explains the programmer's intent as to _why_ they expected it to work.

Comment (jlapeyre) [reply crates/circuit/src/packed_instruction.rs:178]: So this is an example of when you *would* want to use expect?

**Comment by jlapeyre** [comment]
I won't be able to get back to this till next week. Since this is 1) important and 2) re-implements core data structures, I'm ok with merging it now if there are no other objections.

**Comment by jakelishman** [comment]
The last failing test here is blocked by #12776.  I'll fix the latest merge conflicts once that's on its way to merge.

File: crates/circuit/src/packed_instruction.rs (hunk 4 above)
Comment (jakelishman) [reply crates/circuit/src/packed_instruction.rs:178]: Actually, looking back - this particular one isn't even an `unwrap`, it's an `ok`.  That's not a panicking method - it just turns a `Result<T, _>` into an `Option<T>` by erasure of any error variant, which is what this method is doing.

And yeah, I'd `expect` if a file failed to open that we knew should exist.

File: crates/circuit/src/packed_instruction.rs (hunk 1 above)
Comment (jakelishman) [reply crates/circuit/src/packed_instruction.rs:156]: I'm not a big fan of the additional runtime check for internal Qiskit bugs here, especially since particular one wouldn't help narrow down any source of errors - that would have come before by something writing an invalid pointer into the value - and wouldn't catch the category of bugs that are "invalid pointer but _not_ null", which seems equally likely if something unknown has written into the field.

File: crates/circuit/src/packed_instruction.rs (hunk 3 above)
Comment (jakelishman) [reply crates/circuit/src/packed_instruction.rs]: Done in f991157574cfd9c462418366486b307e712f9059.

File: crates/circuit/src/packed_instruction.rs (hunk 2 above)
Comment (jakelishman) [reply crates/circuit/src/packed_instruction.rs]: I changed a couple of `unwrap`s to `expects` with a little note on the reason for the assumption, though I couldn't think of much more to say than the "panics" documentation section already attached.

File: crates/circuit/src/packed_instruction.rs (hunk 1 above)
Comment (jakelishman) [reply crates/circuit/src/packed_instruction.rs:156]: I added an expect message in f991157574cfd9c462418366486b307e712f9059.

**Comment by jakelishman** [comment]
This is up-to-date with current `main` (give or take) and passing all tests. I've addressed the current review comments, so ready for review.

**Review by kevinhartman — APPROVED** [review]
LGTM.

Thanks for doing this work, @jakelishman!
