### PR TITLE
Preserve Python `range` objects in for loops

### LINKED ISSUE #15380: Restore special-case `range` handling to `ForLoop` in Rust-space control-flow
PR #14568 is merging with a regression in the handling of Python-space `range` objects in the `ForLoopOp`.  Efficiently representing ranges is fairly critical to the intended semantics of the range, so we need to include correct handling of it.

This should be done before the 2.3 release, but it's more important to get #14568 merged right now.

Blocked by #15387.

### PR DESCRIPTION
**Pull request by jakelishman**
The `ForLoopOp` always preserved Python `range` objects in the structured form, and had special-purpose visualisation and OQ3 export capabilities to ensure that these were handled in a structured way end-to-end.  While the initial Rust port preserved the Python type hints (`range` _is_ an `Iterable[int]`), it didn't preserve all the intended behaviour.

This commit includes the setup to allow the for-loop collection to be more dynamically typed as well.

### Details and comments

Fix #15380.

No additional tests because the existing tests would already have caught this, except that we don't run them because of #15402.  No release note because the bug isn't released.

### CODE REVIEW

File: crates/circuit/src/operations.rs [hunk 1]
```diff
@@ -365,6 +366,91 @@ pub enum BoxDuration {
...
+            || (self.step.get() < 0 && self.start > self.stop)
+        {
+            // The `diff-1` is guaranteed safe because the `start < stop` or `start > stop`
+            // conditions guarantee that `diff` is at least 1.
+            1 + (diff - 1) / step
+        } else {
+            0
+        }
+    }
+}
```
Comment (raynelfss) [inline crates/circuit/src/operations.rs:400]: Hmmm... This struct looks very similar to parts of `SequenceIndex` an enum struct you designed during #12669. Would you be able to repurpose that struct instead of creating a new one for this? Or if not, should you repurpose that one to use the one offered here?

File: crates/circuit/src/operations.rs [hunk 2]
```diff
@@ -365,6 +366,91 @@ pub enum BoxDuration {
...
+
+/// Possible specifications of the "collection" that a for loop iterates over.
+#[derive(Clone, Debug, IntoPyObject, IntoPyObjectRef, FromPyObject, PartialEq, Eq)]
+pub enum ForCollection {
+    /// A literal Python `range` object extracted to Rust.
+    PyRange(PyRange),
+    /// Some ordered collection of integers.
+    List(Vec<usize>),
+}
```
Comment (raynelfss) [inline crates/circuit/src/operations.rs:438]: This here looks very similar to `PySequenceIndex` which you introduced in #12669. The only difference I see here is that you're not using the int variant? Or would we be able to repurpose it to work wit this one.

**Review by raynelfss — COMMENTED** [review]
I haven't fully looked at the code but there are two questions on my mind as I'm looking.

File: crates/circuit/src/operations.rs (hunk 1 above)
Comment (jakelishman) [reply crates/circuit/src/operations.rs:400]: Not really - a `slice` and a `range` are different Python objects, although they share some passing similarities. Slices can have `None` in various places, and have different semantics on negative indices.

**Comment by debasmita2102** [comment]
I’m a bit confused about should `ForCollection::len()` is meant to line up always with the actual number of loop iterations. For both the `PyRange` and `List` cases, should I always expect `len()` to equal the number of times the body will run, even for larger or nested loops? If that’s the intended invariant, should we add tests that build `ForLoops` with both `PyRange` and `List` collections and check that `len()` matches the actual iteration count when the loop is expanded.

File: crates/circuit/src/operations.rs (hunk 1 above)
Comment (raynelfss) [reply crates/circuit/src/operations.rs:400]: I understand that, in which case since `SequenceIndex` uses Ranges and this type consolidates them into one. Should we replace the `PosRange` and `NegRange` variants to use this instead??

File: crates/circuit/src/operations.rs [hunk 3]
```diff
@@ -365,6 +366,91 @@ pub enum BoxDuration {
     Expr(expr::Expr),
 }
 
+/// A literal Python range extracted to a Rust object.
+///
+/// This is separate to `PyO3`'s `PyRange` type, since that keeps everything internally safe for
+/// subclassing and modification the Python heap.
+#[derive(Clone, Copy, Debug, PartialEq, Eq)]
+pub struct PyRange {
```
Comment (raynelfss) [inline crates/circuit/src/operations.rs:374]: Should we consider changing the name of the struct to something that doesn't have `Py` in the name? even if this struct comes from Python, it doesn't keep any Python tokens or pointers. If anything we can change the name to something along the lines of:
```rs
pub struct IndexRange {
```
Or something like that.

**Review by raynelfss — COMMENTED** [review]
I don't have any strong feelings on this addition. Although, I believe the naming here is a bit misleading and we should consider renaming it to something more rust friendly.

File: crates/circuit/src/operations.rs (hunk 3 above)
Comment (jakelishman) [reply crates/circuit/src/operations.rs:374]: This object here is `PyRange` because it's a very literal description of a Python `range` object.  We expect that the `collection` of a `ForLoop` will expand to involve more runtime ranges / collections, which actually would be pure Rust and unrelated to Python built-ins, including something like `Range { start: Expr, stop: Expr, step: Option<Expr> }`, which is why I was leaving naming space for it.

File: crates/circuit/src/operations.rs (hunk 1 above)
Comment (jakelishman) [reply crates/circuit/src/operations.rs:400]: It doesn't feel to me that unifying `PosRange` and `NegRange` into `PyRange` would actually make things easier; the reason `PosRange` and `NegRange` are already split from each other is that handling `step`s that can be either positive or negative is already very awkward.  The semantics of the ranges within `SliceIndex` are slightly different too, because of how the end-points work (particularly with regard to negative steps).

Fwiw, I don't expect this `PyRange` object to live forever - we will almost certainly rework how for-loop collections work at some point.

**Review by raynelfss — APPROVED** [review]

**Comment by jakelishman** [comment]
> I’m a bit confused about should `ForCollection::len()` is meant to line up always with the actual number of loop iterations. For both the `PyRange` and `List` cases, should I always expect `len()` to equal the number of times the body will run, even for larger or nested loops? If that’s the intended invariant, should we add tests that build `ForLoops` with both `PyRange` and `List` collections and check that `len()` matches the actual iteration count when the loop is expanded.

Debasmita: sorry, I didn't reply to your comment properly before.  `ForCollection::len` should return the number of elements that will be iterated over.  It could have been a good idea to add tests of the `PyRange::len` method (the `List` variant is trivial) - it should line up exactly with Python's `range` object.  If you wanted to make a PR adding Rust-space tests to this file that test the length, I can review it.
