### PR TITLE
Reimplementing QSD using faer instead of nalgebra.

### LINKED ISSUE #15870: Schur decomposition fails during transpilation of a circuit built from a unitary matrix.
### Environment

- **Qiskit version**: 2.3.1
- **Python version**: 3.13.7
- **Operating system**: MacOS 26.3.1

### What is happening?

I have a unitary matrix that I would like to turn into a circuit using the `QuantumCircuit.unitary` method, then compile to a target device/gateset with `qiskit.transpile`. When I attempt to do this with, I get an error saying that the Schur decomposition failed during transpilation.

### How can we reproduce the issue?

I ran the following script
```
import numpy as np
import scipy.linalg as la
from qiskit import transpile, QuantumCircuit, transpile

unitary_matrix = np.array([
    [0j, 0j, 0j, 0j, 0j, 0j, 0j, (1+0j)], 
    [0j, 0j, 0j, 0j, 0j, 0j, (1+0j), 0j], 
    [0j, 0j, 0j, 0j, 0j, (1+0j), 0j, 0j], 
    [0j, (1+0j), 0j, 0j, 0j, 0j, 0j, 0j], 
    [0j, 0j, 0j, 0j, (1+0j), 0j, 0j, 0j], 
    [0j, 0j, (1+0j), 0j, 0j, 0j, 0j, 0j], 
    [0j, 0j, 0j, (1+0j), 0j, 0j, 0j, 0j], 
    [(1+0j), 0j, 0j, 0j, 0j, 0j, 0j, 0j]
])

# Check that the matrix is indeed unitary.
assert la.norm(np.eye(unitary_matrix.shape[0]) - unitary_matrix.conj().T @ unitary_matrix) <= 1e-12
assert la.norm(np.eye(unitary_matrix.shape[0]) - unitary_matrix @ unitary_matrix.conj().T) <= 1e-12

circuit = QuantumCircuit(3)
circuit.unitary(unitary_matrix, list(range(3)))
trans_circuit = transpile(circuit, basis_gates=['u', 'cx'])
```
and got the error ouptut
```
Traceback (most recent call last):
  File "transpiler_error.py", line 22, in <module>
    trans_circuit = transpile(circuit, basis_gates=['u', 'cx'])
  File "<repo path>/.venv/lib/python3.13/site-packages/qiskit/compiler/transpiler.py", line 291, in transpile
    out_circuits = pm.run(circuits, callback=callback, num_processes=num_processes)
  File "<repo path>/.venv/lib/python3.13/site-packages/qiskit/transpiler/passmanager.py", line 420, in run
    return super().run(circuits, output_name, callback, num_processes=num_processes)
           ~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<repo path>/.venv/lib/python3.13/site-packages/qiskit/transpiler/passmanager.py", line 457, in wrapper
    return meth(*meth_args, **meth_kwargs)
  File "<repo path>/.venv/lib/python3.13/site-packages/qiskit/transpiler/passmanager.py", line 197, in run
    return super().run(
           ~~~~~~~~~~~^
        in_programs=circuits,
        ^^^^^^^^^^^^^^^^^^^^^
    ...<3 lines>...
        property_set=property_set,
        ^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "<repo path>/.venv/lib/python3.13/site-packages/qiskit/passmanager/passmanager.py", line 238, in run
    _run_workflow(
    ~~~~~~~~~~~~~^
        program=program,
        ^^^^^^^^^^^^^^^^
    ...<3 lines>...
        **kwargs,
        ^^^^^^^^^
    )
    ^
  File "<repo path>/.venv/lib/python3.13/site-packages/qiskit/passmanager/passmanager.py", line 311, in _run_workflow
    passmanager_ir, final_state = flow_controller.execute(
                                  ~~~~~~~~~~~~~~~~~~~~~~~^
        passmanager_ir=passmanager_ir,
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    ...<3 lines>...
        callback=kwargs.get("callback", None),
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "<repo path>/.venv/lib/python3.13/site-packages/qiskit/passmanager/base_tasks.py", line 218, in execute
    passmanager_ir, state = next_task.execute(
                            ~~~~~~~~~~~~~~~~~^
        passmanager_ir=passmanager_ir,
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        state=state,
        ^^^^^^^^^^^^
        callback=callback,
        ^^^^^^^^^^^^^^^^^^
    )
    ^
  File "<repo path>/.venv/lib/python3.13/site-packages/qiskit/transpiler/basepasses.py", line 167, in execute
    new_dag, state = super().execute(
                     ~~~~~~~~~~~~~~~^
        passmanager_ir=passmanager_ir,
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        state=state,
        ^^^^^^^^^^^^
        callback=callback,
        ^^^^^^^^^^^^^^^^^^
    )
    ^
  File "<repo path>/.venv/lib/python3.13/site-packages/qiskit/passmanager/base_tasks.py", line 98, in execute
    ret = self.run(passmanager_ir)
  File "<repo path>/.venv/lib/python3.13/site-packages/qiskit/transpiler/passes/synthesis/unitary_synthesis.py", line 187, in run
    out = run_main_loop(
        dag,
    ...<8 lines>...
        self._pulse_optimize,
    )
qiskit.exceptions.QiskitError: 'Schur decomposition failed'
```
(I have edited the paths in the stacktrace for privacy.)

### What should happen?

The circuit should transpile successfully.

### Any suggestions?

_No response_

### PR DESCRIPTION
**Pull request by alexanderivrii**
### Summary

This PR reimplements quantum Shannon decomposition to use `faer` instead of `nalgebra` as `faer` is significantly better for involved linear algebra calculations.

Fixes #15870.

### CODE REVIEW

File: crates/synthesis/src/linalg/mod.rs [hunk 1]
```diff
@@ -222,6 +225,98 @@ pub fn svd_decomposition(
...
+}
+
+/// Verifies the given matrix U is unitary by comparing U*U to the identity matrix
+pub fn verify_unitary_faer(u: MatRef<Complex64>) -> bool {
+    let n = u.shape().0;
+
+    let id_mat = Mat::<Complex64>::identity(n, n);
+    let uu = u.adjoint() * u;
+
+    (uu.as_ref() - id_mat.as_ref()).norm_max() < 1e-7
```
Comment (ShellyGarion) [inline crates/synthesis/src/linalg/mod.rs]: should we add 1e-7 as a constant? maybe as VERIFY_TOL? it also appears in other parts of the code.

File: crates/synthesis/src/linalg/mod.rs [hunk 2]
```diff
@@ -222,6 +225,98 @@ pub fn svd_decomposition(
     (u_na.into(), s_na, v_na)
 }
 
+pub fn svd_decomposition_faer(
```
Comment (ShellyGarion) [inline crates/synthesis/src/linalg/mod.rs]: perhaps it's worth to add a code for `verify_svd_faer`, and add it here with `debug_assert!`

**Comment by mtreinish** [comment]
I'm curious is there any runtime difference between this and the previous implementation. Since this is a correctness fix it doesn't really matter since we're going to do it anyway, I'm just curious.

File: crates/synthesis/src/linalg/mod.rs [hunk 3]
```diff
@@ -222,6 +225,98 @@ pub fn svd_decomposition(
...
+    a: MatRef<Complex64>,
+    b: MatRef<Complex64>,
+    c: MatRef<Complex64>,
+    d: MatRef<Complex64>,
+) -> Mat<Complex64> {
+    let n = a.nrows();
+    let mut block_matrix = Mat::<Complex64>::zeros(2 * n, 2 * n);
+    for i in 0..n {
+        for j in 0..n {
+            block_matrix[(i, j)] = a[(i, j)];
```
Comment (ShellyGarion) [inline crates/synthesis/src/linalg/mod.rs]: is there an efficient way to do it in rust w/o the for loops?
(similar comment to b,c,d below)

File: crates/accelerate/Cargo.toml [hunk 4]
```diff
@@ -26,6 +26,7 @@ qiskit-circuit.workspace = true
 qiskit-transpiler.workspace = true
 qiskit-quantum-info.workspace = true
 nalgebra.workspace = true
+faer.workspace = true
```
Comment (mtreinish) [inline crates/accelerate/Cargo.toml]: Why do we need faer on the accelerate crate?

File: crates/synthesis/src/qsd.rs [hunk 5]
```diff
@@ -110,7 +113,7 @@ pub fn quantum_shannon_decomposition(
     let one_qubit_decomposer = one_qubit_decomposer_basis_set.unwrap_or(&default_1q_basis);
     let two_qubit_decomposer = two_qubit_decomposer.unwrap_or(&default_2q_decomposer);
 
-    if abs_diff_eq!(DMatrix::identity(dim, dim), mat) {
+    if (Mat::<Complex64>::identity(dim, dim).as_ref() - mat).norm_max() < 1e-8 {
```
Comment (ShellyGarion) [inline crates/synthesis/src/qsd.rs]: why is it 1e-8? maybe we should hard-code this constant.
similarly for the 1e-7 constants in other places of the code (that are used for verification).

File: crates/synthesis/src/qsd.rs [hunk 6]
```diff
@@ -325,64 +323,81 @@ fn qsd_inner(
...
+    let c_block = block_matrix_faer(iden.as_ref(), zero.as_ref(), zero.as_ref(), c);
 
-    let mat_check = a_block * b_block * c_block * Complex64::from(0.5);
+    let mat_check = &a_block * &b_block * &c_block * Scale(Complex64::from(0.5));
 
-    abs_diff_eq!(mat, &mat_check, epsilon = 1e-7)
+    (mat - mat_check).norm_max() < 1e-7
+}
+
+fn eigendecomposition(
```
Comment (ShellyGarion) [inline crates/synthesis/src/qsd.rs]: why is this function here and not in linalg?
I also think it deserves a docstring explaining what it does.

File: crates/synthesis/src/qsd.rs [hunk 7]
```diff
@@ -325,64 +323,81 @@ fn qsd_inner(
...
+    mat: MatRef<Complex64>,
+) -> Result<(Vec<Complex64>, Mat<Complex64>), QSDError> {
+    let eigh = mat.eigen();
+
+    match eigh {
+        Ok(eigh) => {
+            let vmat = eigh.U().to_owned();
+            // ToDo: check if I can remove this?
```
Comment (ShellyGarion) [inline crates/synthesis/src/qsd.rs]: this ToDo is still relevant? if so, please better explain it

File: crates/synthesis/src/qsd.rs [hunk 8]
```diff
@@ -516,23 +524,24 @@ fn demultiplex(
...
-    let u_check = v_block * d_block * w_block;
+    let u_block = block_matrix_faer(um0, zero.as_ref(), zero.as_ref(), um1);
+    let v_block = block_matrix_faer(vmat, zero.as_ref(), zero.as_ref(), vmat);
+    let w_block = block_matrix_faer(wmat, zero.as_ref(), zero.as_ref(), wmat);
+    let d_inv = dmat.adjoint().to_owned();
+    let d_block = block_matrix_faer(dmat, zero.as_ref(), zero.as_ref(), d_inv.as_ref());
+    let u_check = &v_block * &d_block * &w_block;
 
-    abs_diff_eq!(u_block, u_check, epsilon = 1e-7)
+    (u_block.as_ref() - u_check.as_ref()).norm_max() < 1e-7
```
Comment (ShellyGarion) [inline crates/synthesis/src/qsd.rs]: should we add 1e-7 as a constant? maybe as VERIFY_TOL? it also appears in other parts of the code.

File: crates/synthesis/src/qsd.rs [hunk 9]
```diff
@@ -663,19 +672,13 @@ fn extract_multiplex_blocks(umat: &DMatrix<Complex64>, k: usize) -> [DMatrix<Com
...
     let um10 = ud4.slice(s![1, .., 0, ..]);
     [
-        DMatrix::from_fn(um00.shape()[0], um00.shape()[1], |i, j| um00[[i, j]]),
-        DMatrix::from_fn(um11.shape()[0], um11.shape()[1], |i, j| um11[[i, j]]),
-        DMatrix::from_fn(um01.shape()[0], um01.shape()[1], |i, j| um01[[i, j]]),
-        DMatrix::from_fn(um10.shape()[0], um10.shape()[1], |i, j| um10[[i, j]]),
+        Mat::from_fn(um00.shape()[0], um00.shape()[1], |i, j| um00[[i, j]]),
+        Mat::from_fn(um11.shape()[0], um11.shape()[1], |i, j| um11[[i, j]]),
+        Mat::from_fn(um01.shape()[0], um01.shape()[1], |i, j| um01[[i, j]]),
+        Mat::from_fn(um10.shape()[0], um10.shape()[1], |i, j| um01[[i, j]]),
```
Comment (ShellyGarion) [inline crates/synthesis/src/qsd.rs]: note the copy-pasting bug :) 
```suggestion
        Mat::from_fn(um10.shape()[0], um10.shape()[1], |i, j| um10[[i, j]]),
```

File: crates/synthesis/src/linalg/mod.rs [hunk 10]
```diff
@@ -222,6 +225,98 @@ pub fn svd_decomposition(
...
+            if i == j { s[i] } else { C_ZERO }
+        },
+    );
+
+    (u, sigma, v)
+}
+
+pub fn closest_unitary_faer(mat: MatRef<Complex64>) -> Mat<Complex64> {
+    let (u, _sigma, v_t) = svd_decomposition_faer(mat);
+    u.as_ref() * v_t.as_ref()
```
Comment (mtreinish) [inline crates/synthesis/src/linalg/mod.rs]: This results in unnecessary array copies being made. You could do:


```suggestion
    let svd = mat.svd().expect("Call to faer SVD failed");
    svd.U() * svd.V().adjoint()
```

And avoids the extra 2 array copies

File: crates/synthesis/src/linalg/mod.rs [hunk 11]
```diff
@@ -222,6 +225,98 @@ pub fn svd_decomposition(
     (u_na.into(), s_na, v_na)
 }
 
+pub fn svd_decomposition_faer(
+    mat: MatRef<Complex64>,
+) -> (Mat<Complex64>, Mat<Complex64>, Mat<Complex64>) {
+    let svd = mat.svd().expect("Call to faer SVD failed");
```
Comment (mtreinish) [inline crates/synthesis/src/linalg/mod.rs]: Should we handle this and return a user facing error like we do for nalgebra. From what I can see in the faer docs this will be a convergence error which I'm not sure we'd want to result in a panic.

File: releasenotes/notes/reimplement-qsd-using-faer-6f402a8d766e5db1.yaml [hunk 12]
```diff
@@ -0,0 +1,9 @@
+---
+fixes:
+  - |
+    Fixed in issue in Schur decomposition for certain matrices by reimplementing it
+    using ``faer`` instead of ``nalgebra``. The issue could occur when running
+    the quantum Shannon decomposition via the :class:`.UnitarySynthesis` transpiler
+    pass or via :func:`.transpile`.
```
Comment (ShellyGarion) [inline releasenotes/notes/reimplement-qsd-using-faer-6f402a8d766e5db1.yaml]: or by calling qs_decomposition directly

**Review by ShellyGarion — COMMENTED** [review]
Thnaks for fixing this bug so quickly... I do hope that with faer we won't have the numeric issues in QSD anymore...

File: crates/synthesis/src/linalg/mod.rs [hunk 13]
```diff
@@ -222,6 +225,98 @@ pub fn svd_decomposition(
...
+/// Returns a block matrix `[a, b; c, d]`.
+/// The matrices `a`, `b`, `c`, `d` are all assumed to be square matrices of the same size
+pub fn block_matrix_faer(
+    a: MatRef<Complex64>,
+    b: MatRef<Complex64>,
+    c: MatRef<Complex64>,
+    d: MatRef<Complex64>,
+) -> Mat<Complex64> {
+    let n = a.nrows();
+    let mut block_matrix = Mat::<Complex64>::zeros(2 * n, 2 * n);
```
Comment (mtreinish) [inline crates/synthesis/src/linalg/mod.rs:335]: Do you need to initialize this with zero? It feels unnecessary because you should be populating every element in the matrix based on the blocks.

**Review by mtreinish — COMMENTED** [review]
I've only gotten through the linear algebra module and not the bulk of the qsd yet. But I'm about to step away so I thought I'd share my comments so far

File: crates/accelerate/Cargo.toml (hunk 4 above)
Comment (alexanderivrii) [reply crates/accelerate/Cargo.toml]: With this PR, we use `faer` both in `synthesis` and `transpiler` crates. I thought that this is the right approach to specify the package version only once, but I am might be wrong about it -- what is the recommended way?

File: crates/synthesis/src/linalg/mod.rs (hunk 1 above)
Comment (alexanderivrii) [reply crates/synthesis/src/linalg/mod.rs]: All the error constants (`1e-7`, `1e-8`, etc.) are pre-existing. But I agree that it would be a good idea to add them at the top of the file.

File: crates/synthesis/src/qsd.rs (hunk 9 above)
Comment (alexanderivrii) [reply crates/synthesis/src/qsd.rs]: I will fix this-  the same bug that Gadi already recently fixed in main.

File: crates/accelerate/Cargo.toml (hunk 4 above)
Comment (mtreinish) [reply crates/accelerate/Cargo.toml]: No, using a workspace version is the correct way. But this is adding faer as a dependency on the qiskit-accelerate crate but afaict nothing in qiskit-accelerate is using faer. Unless I missed it somewhere

**Comment by alexanderivrii** [comment]
A quick answer on performance comparison. 

Running the following simple script on my laptop (generating 10 random unitary matrix over `nq` qubits, running `qs_decomposition`, and taking the average of runtimes):
```python
run_times = []
num_trials = 10
for nq in range(1, 11):
    total_time = 0
    for seed in range(num_trials):
        n = 2 ** nq
        mat = random_unitary(n, seed=seed).data
        time_start = time.time()
        qc = qsd.qs_decomposition(mat)
        time_end = time.time()
        total_time += time_end - time_start
    avg_time = total_time / num_trials
    run_times.append(avg_time)
print(run_times)
```
returns the following
```
main = [9.09566879272461e-05, 4.303455352783203e-05, 0.00023097991943359374, 0.0009044647216796875, 0.004224538803100586, 0.019590377807617188, 0.10117588043212891, 0.5623687744140625, 3.393336462974548, 22.304159712791442]

this_pr = [9.09566879272461e-05, 4.079341888427734e-05, 0.00023005008697509765, 0.0009874343872070313, 0.0043228864669799805, 0.018857145309448244, 0.09331314563751221, 0.47628915309906006, 2.518214392662048, 12.950119781494141]
```

image

Overall it seems like we have a performance improvement as well, especially for larger number of qubits (I believe it's due to translating from nalgebra to faer and back for the SVD).

File: crates/synthesis/src/linalg/mod.rs (hunk 2 above)
Comment (alexanderivrii) [reply crates/synthesis/src/linalg/mod.rs]: Oops, I have accidentally removed this check; restoring.

File: crates/synthesis/src/linalg/mod.rs (hunk 3 above)
Comment (alexanderivrii) [reply crates/synthesis/src/linalg/mod.rs]: Thanks, there is indeed a nice and slightly more performant way.

File: crates/synthesis/src/qsd.rs (hunk 7 above)
Comment (alexanderivrii) [reply crates/synthesis/src/qsd.rs]: updating the comment: unfortunately we seem to need this call to `closest_unitary` here

File: crates/accelerate/Cargo.toml (hunk 4 above)
Comment (alexanderivrii) [reply crates/accelerate/Cargo.toml]: you are right, removing it (no idea how it slipped there)

File: crates/synthesis/src/linalg/mod.rs (hunk 10 above)
Comment (alexanderivrii) [reply crates/synthesis/src/linalg/mod.rs]: good idea!

File: crates/synthesis/src/linalg/mod.rs (hunk 13 above)
Comment (alexanderivrii) [reply crates/synthesis/src/linalg/mod.rs:335]: The only way I can see how to avoid this (keeping the current code structure) is doing something like
```rust
 let mut block_matrix = Mat::<Complex64>::with_capacity(2 * n, 2 * n);
 unsafe { block_matrix.set_dims(2 * n, 2 * n) };
 ```
However, I semi-expect that the compiler should be able to optimize this itself. I have kept the original code for now, but replaced the loops as per Shelly's suggestion. I am also not very worried about this specific code as for now it's only used in debug assertions.

File: crates/synthesis/src/linalg/mod.rs (hunk 11 above)
Comment (alexanderivrii) [reply crates/synthesis/src/linalg/mod.rs]: I have improved the error checking as part of [a4a1172](https://github.com/Qiskit/qiskit/pull/15874/commits/a4a1172198b656f3db33988826db5e963abe43ef), however I did not succeed to wrap errors produced by faer similarly to errors coming from python or circuit data (while there is a class `FaerError`, see https://docs.rs/faer/latest/faer/sparse/enum.FaerError.html, it does not seem to account for errors coming from say SVD decomposition).

File: crates/synthesis/src/linalg/mod.rs (hunk 13 above)
Comment (mtreinish) [reply crates/synthesis/src/linalg/mod.rs:335]: I was thinking something along those lines. I wasn't sure if faer's `Mat` type had a method for creating an uninitialized matrix directly or you had to do something like that. But it would be inside an unsafe either way. The other option would be to use `from_fn` and have conditions on the index ranges.

I find it unlikely that the compiler will able to optimize it away because `Mat::zeros()` is calling `Mat::from_fn` which is explicitly calling the closure that returns zero for every element in the array. But it's only a small performance difference, it's something we can explore later if this becomes a bottleneck.

**Review by ShellyGarion — DISMISSED** [review]
LGTM. but I'll wait with merging to see if @mtreinish has any further comments.

File: crates/synthesis/src/linalg/mod.rs [hunk 14]
```diff
@@ -232,6 +239,106 @@ pub fn svd_decomposition(
     (u_na.into(), s_na, v_na)
 }
 
+/// Result for the SVD decomposition: a triple of matries (U, S, V) such that A = U * S * V
+type SVDResult = (Mat<Complex64>, Mat<Complex64>, Mat<Complex64>);
```
Comment (mtreinish) [inline crates/synthesis/src/linalg/mod.rs]: My first two thoughts here were first why not just use `[Mat<Complex64>; 3]` instead of a tuple? But then I think why didn't you go for a struct here. Then you could have named fields and not have to remember that `SVDResult.1` is `S`.

File: crates/synthesis/src/linalg/mod.rs [hunk 15]
```diff
@@ -232,6 +239,106 @@ pub fn svd_decomposition(
...
+}
+
+pub fn closest_unitary_faer(mat: MatRef<Complex64>) -> Result<Mat<Complex64>, QSDError> {
+    let svd = mat.svd().map_err(|_| QSDError::SVDDecompositionFailed)?;
+    Ok(svd.U() * svd.V().adjoint())
+}
+
+pub fn from_diagonal_faer(diag: &[Complex64]) -> Mat<Complex64> {
+    let n = diag.len();
+    Mat::from_fn(n, n, |i, j| if i == j { diag[i] } else { Complex64::ZERO })
```
Comment (mtreinish) [inline crates/synthesis/src/linalg/mod.rs]: Would it be faster to do?


```suggestion
    let n = diag.len();
    let mut mat = Mat::zeros(n, n);
    mat.diagonal_mut().column_vector_mut().iter_mut().zip(diag).for_each(|(x, y)| *x = *y);
    mat
```

File: crates/transpiler/src/passes/unitary_synthesis/mod.rs [hunk 16]
```diff
@@ -409,9 +410,8 @@ fn synthesize_matrix_onto(
                     return Ok(false);
                 }
             }
-            let unitary =
-                DMatrix::from_fn(1 << num_qubits, 1 << num_qubits, |i, j| unitary[[i, j]]);
-            let circuit = quantum_shannon_decomposition(&unitary, None, None, None, None)?;
+            let unitary = Mat::from_fn(1 << num_qubits, 1 << num_qubits, |i, j| unitary[[i, j]]);
```
Comment (mtreinish) [inline crates/transpiler/src/passes/unitary_synthesis/mod.rs]: Do we need to make a copy here? We should be able to build a faer MatRef view from the ndarray directly by reference. There are functions for this in `qiskit_synthesis::linalg`. 

I also think we should add a public function that takes an `ArrayView2` for qsd and isolate the faer usage to the synthesis crate. We don't need actually need to use faer in the transpiler crate, we can just make the public interface work with an ndarray view instead.

File: crates/synthesis/src/qsd.rs [hunk 17]
```diff
@@ -91,7 +100,7 @@ enum VWType {
 ///
 /// Decomposed quantum circuit.
 pub fn quantum_shannon_decomposition(
-    mat: &DMatrix<Complex64>,
+    mat: MatRef<Complex64>,
```
Comment (mtreinish) [inline crates/synthesis/src/qsd.rs]: I mentioned this in the transpiler module, but I think we should make this an `ArrayView2`, we only use qsd from either Python or the transpiler. In both contexts it's easier to work with an ndarray view, since rust-numpy gives us an ndarray array view and similarly we can run `UnitaryGate::matrix_view()` returns an `ArrayView2`. We can just make the call `crate::linalg::ndarray_to_faer` to get the `MatRef` from the `ArrayView2` with no copies when we start using faer.

File: crates/synthesis/src/qsd.rs [hunk 18]
```diff
@@ -41,12 +43,16 @@ use qiskit_circuit::{BlocksMode, Qubit, VarsMode};
 use qiskit_quantum_info::convert_2q_block_matrix::instructions_to_matrix;
 
 const EPS: f64 = 1e-10;
+const MINIMUM_TOL: f64 = 1e-8;
```
Comment (mtreinish) [inline crates/synthesis/src/qsd.rs]: Isn't this a really loose tolerance compared to our other synthesis methods for identity equivalence? Like we use 1e-12 in remove_identity_equiv.rs, and I thought the 2q basis decomposer used the same value.

File: crates/synthesis/src/qsd.rs [hunk 19]
```diff
@@ -327,64 +331,65 @@ fn qsd_inner(
...
-    let (v, sigma, w_dg) = svd_decomposition(a);
+fn zxz_decomp_svd(a: MatRef<Complex64>) -> Result<(Mat<Complex64>, Mat<Complex64>), QSDError> {
+    let (v, sigma, w_dg) = svd_decomposition_faer(a)?;
 
-    let s = &v * &sigma * &v.adjoint();
+    let s = v.as_ref() * sigma * v.adjoint();
     let u = v * w_dg;
 
-    (s, u)
+    Ok((s, u))
```
Comment (mtreinish) [inline crates/synthesis/src/qsd.rs]: The helper makes an owned copy of the svd's output matrices. When I see this I'm wondering do we even want that helper method? You can avoid these copies if you just call faer directly just like the comment I left in the linalg file yesterday. I assumed the `to_owned` calls in the helper function were because something needed an owned copy, but this could work with references instead.

File: crates/synthesis/src/qsd.rs [hunk 20]
```diff
@@ -327,64 +331,65 @@ fn qsd_inner(
...
 }
 
+/// ZXZ decomposition result
+type ZXZResult = (
+    Mat<Complex64>,
+    Mat<Complex64>,
+    Mat<Complex64>,
+    Mat<Complex64>,
+);
```
Comment (mtreinish) [inline crates/synthesis/src/qsd.rs]: Is there a reason to not use a struct here and give names to the 4 matrices? I get this was using a tuple before but when I saw this I had no idea how you're expected to know which position is which field in the decomposition.

**Review by mtreinish — COMMENTED** [review]
Overall this is fairly straightforward. I left a few inline comments. The biggest thing is I don't think we need to add faer as a dependency to the transpiler crate. We should just adjust our public interface to use ndarray types, because that's (and nalgebra for 1q and 2q unitaries) actually what we use for storage in the transpiler. So it's more natural if we just move the ndarray -> faer conversion inside the qsd function (and do it without copies).

File: crates/synthesis/src/linalg/mod.rs (hunk 15 above)
Comment (alexanderivrii) [reply crates/synthesis/src/linalg/mod.rs]: I don't see a noticeable difference when running the full algorithm with and without this change, but I do like the suggestion.

File: crates/transpiler/src/passes/unitary_synthesis/mod.rs (hunk 16 above)
Comment (alexanderivrii) [reply crates/transpiler/src/passes/unitary_synthesis/mod.rs]: This is a great suggestion!

File: crates/synthesis/src/qsd.rs (hunk 17 above)
Comment (alexanderivrii) [reply crates/synthesis/src/qsd.rs]: This makes sense - I love this! With this change, only the `synthesis` crates needs to be aware about `faer`. Does it still make sense to include the faer version in the topmost level `Cargo.toml` file (and set `faer.workspace` in the synthesis toml file), or is the older version of setting the faer version in synthesis toml directly preferable?

File: crates/synthesis/src/qsd.rs (hunk 18 above)
Comment (alexanderivrii) [reply crates/synthesis/src/qsd.rs]: I do agree with you, though in `remove_identity_equivs` the tolerance reflects average fidelity and here it's maximum element difference - on the top of my head I am not sure how these are related. @ShellyGarion what do you think?

Note that in this PR I did not change the actual numerical values, but it would be a good follow-up to improve upon various magic values used in the code (`MINIMUM_TOL`, `EPS`, `ATOL`, `RTOL`).

Comment (ShellyGarion) [reply crates/synthesis/src/qsd.rs]: It seems that `MINIMUM_TOL=1e-8` was introduced as part of this PR to check if a matrix is close to Identity (line 124). any reason for choosing this value? perhpas it could be changed to `1e-12` ? 

`ATOL=1e-8` and `RTOL=1e-5` are standard in quantum info:
https://github.com/Qiskit/qiskit/blob/913f89110309d4c6c1bd42cfa1281e46f86c5a1f/qiskit/quantum_info/operators/predicates.py#L21
https://github.com/Qiskit/qiskit/blob/913f89110309d4c6c1bd42cfa1281e46f86c5a1f/qiskit/quantum_info/operators/predicates.py#L22

`EPS=1e-10` is taken from the UCRZ synthesis python code:
https://github.com/Qiskit/qiskit/blob/913f89110309d4c6c1bd42cfa1281e46f86c5a1f/qiskit/circuit/library/generalized_gates/uc_pauli_rot.py#L29

Generally, QSD is less accurate then other trasnpiler passes, so we can't set very small tolerance levels here.

Comment (alexanderivrii) [reply crates/synthesis/src/qsd.rs]: Oh, sorry, my bad: for some reason I thought that `abs_diff_eq!` for matrices defaults to `1e-8`, but that's not the case. I will change it to `1e-12`.

File: crates/synthesis/src/qsd.rs (hunk 19 above)
Comment (alexanderivrii) [reply crates/synthesis/src/qsd.rs]: I tried removing this helper, but surprisingly it did not noticeably change runtimes, even for large matrices, while making the code a bit uglier. But I ended up removing the helper function `zxz_decomp_svd` which also copies matrices.

File: crates/synthesis/src/qsd.rs (hunk 20 above)
Comment (alexanderivrii) [reply crates/synthesis/src/qsd.rs]: Good idea, I will change this.

File: crates/synthesis/src/linalg/mod.rs [hunk 21]
```diff
@@ -232,6 +239,108 @@ pub fn svd_decomposition(
...
+    mat: MatRef<Complex64>,
+) -> Result<(Vec<Complex64>, Mat<Complex64>), QSDError> {
+    let eigh = mat
+        .eigen()
+        .map_err(|_| QSDError::EigenDecompositionFailed)?;
+
+    let vmat = eigh.U().to_owned();
+    // unfortunately, we need to call closest_unitary_faer here
+    let vmat = closest_unitary_faer(vmat.as_ref())?;
+    let eigvals: Vec<Complex64> = eigh.S().column_vector().iter().cloned().collect();
```
Comment (mtreinish) [inline crates/synthesis/src/linalg/mod.rs]: Isn't `Complex64` `Copy`? 

```suggestion
    let eigvals: Vec<Complex64> = eigh.S().column_vector().iter().copied().collect();
```

File: crates/synthesis/src/linalg/mod.rs [hunk 22]
```diff
@@ -232,6 +239,108 @@ pub fn svd_decomposition(
...
+///
+/// The decomposition is given by three matrices `(U, S, V)` such that `A = U * S * V^\dagger`.
+pub struct SVDResult {
+    pub u: Mat<Complex64>,
+    pub s: Mat<Complex64>,
+    pub v: Mat<Complex64>,
+}
+
+/// Runs singular valued decomposition on `mat`.
+pub fn svd_decomposition_faer(mat: MatRef<Complex64>) -> Result<SVDResult, QSDError> {
```
Comment (mtreinish) [inline crates/synthesis/src/linalg/mod.rs]: Based on the error type is this only for QSD? If so I'd say this helper should live in the QSD module. If you intend for this to be a general utility this should return an error type that's unique to the failure mode. QSD can wrap it in a qsd error if it needs to.

File: crates/synthesis/src/linalg/mod.rs [hunk 23]
```diff
@@ -232,6 +239,108 @@ pub fn svd_decomposition(
...
+    let svd_result = SVDResult { u, s, v };
+    debug_assert!(verify_svd_decomposition_faer(mat.as_ref(), &svd_result));
+
+    Ok(svd_result)
+}
+
+/// Computes the eigenvalues and the eigenvectors of a square matrix
+pub fn eigendecomposition_faer(
+    mat: MatRef<Complex64>,
+) -> Result<(Vec<Complex64>, Mat<Complex64>), QSDError> {
```
Comment (mtreinish) [inline crates/synthesis/src/linalg/mod.rs]: Based on the error type is this only for QSD? If so I'd say this helper should live in the QSD module. If you intend for this to be a general utility this should return an error type that's unique to the failure mode. QSD can wrap it in a qsd error if it needs to.

File: crates/synthesis/src/linalg/mod.rs [hunk 24]
```diff
@@ -232,6 +239,108 @@ pub fn svd_decomposition(
...
+        .map_err(|_| QSDError::EigenDecompositionFailed)?;
+
+    let vmat = eigh.U().to_owned();
+    // unfortunately, we need to call closest_unitary_faer here
+    let vmat = closest_unitary_faer(vmat.as_ref())?;
+    let eigvals: Vec<Complex64> = eigh.S().column_vector().iter().cloned().collect();
+    Ok((eigvals, vmat))
+}
+
+pub fn closest_unitary_faer(mat: MatRef<Complex64>) -> Result<Mat<Complex64>, QSDError> {
```
Comment (mtreinish) [inline crates/synthesis/src/linalg/mod.rs]: Based on the error type is this only for QSD? If so I'd say this helper should live in the QSD module. If you intend for this to be a general utility this should return an error type that's unique to the failure mode. QSD can wrap it in a qsd error if it needs to.

File: crates/synthesis/src/qsd.rs [hunk 25]
```diff
@@ -327,64 +327,61 @@ fn qsd_inner(
...
-    let (v, sigma, w_dg) = svd_decomposition(a);
-
-    let s = &v * &sigma * &v.adjoint();
-    let u = v * w_dg;
-
-    (s, u)
+/// Result for the block-ZXZ decomposition of a matrix `A`.
+///
+/// See [2] equation (5) for details.
+pub struct ZXZResult {
```
Comment (mtreinish) [inline crates/synthesis/src/qsd.rs]: Does this need to be pub? Is it something we return outside the crate?

File: crates/synthesis/src/linalg/mod.rs (hunk 22 above)
Comment (alexanderivrii) [reply crates/synthesis/src/linalg/mod.rs]: This makes sense. I think it would be nice to have this (and some other) functions as general utility functions. I  have removed the usage of `QiskitError` from `mod.rs`, but added a new error type `LinAlgError`. Done in [7408540](https://github.com/Qiskit/qiskit/pull/15874/commits/740854027818362ecc003a74635d891f5604ee8c).

File: crates/synthesis/src/qsd.rs (hunk 25 above)
Comment (alexanderivrii) [reply crates/synthesis/src/qsd.rs]: good catch, no need for this to be pub. Done in [f932a20](https://github.com/Qiskit/qiskit/pull/15874/commits/f932a20fb8e3b95783d31cd012a9a5e5d94ad01b).

File: crates/synthesis/src/linalg/mod.rs (hunk 21 above)
Comment (alexanderivrii) [reply crates/synthesis/src/linalg/mod.rs]: Done in [527894c](https://github.com/Qiskit/qiskit/pull/15874/commits/527894c2b3eec98d09659be3ea4f3cf7f7f70919).

File: crates/synthesis/src/linalg/mod.rs (hunk 23 above)
Comment (alexanderivrii) [reply crates/synthesis/src/linalg/mod.rs]: Done in [7408540](https://github.com/Qiskit/qiskit/pull/15874/commits/740854027818362ecc003a74635d891f5604ee8c).

File: crates/synthesis/src/linalg/mod.rs (hunk 24 above)
Comment (alexanderivrii) [reply crates/synthesis/src/linalg/mod.rs]: Done in [7408540](https://github.com/Qiskit/qiskit/pull/15874/commits/740854027818362ecc003a74635d891f5604ee8c).

File: crates/synthesis/src/qsd.rs [hunk 26]
```diff
@@ -60,9 +63,8 @@ pub enum QSDError {
 impl From<QSDError> for PyErr {
     fn from(error: QSDError) -> Self {
         match error {
-            QSDError::SchurDecompositionFailed => {
-                QiskitError::new_err("Schur decomposition failed")
-            }
+            QSDError::ErrorFromLinAlg(err) => err.into(),
```
Comment (mtreinish) [inline crates/synthesis/src/qsd.rs:66]: I do wonder if we want a better error message here. Right now a user calls qsd, unitary synthesis, or the transpiler and will get an exception: `QiskitError: Eigen decomposition failed" that points to the qsd rust function. I'm worried this is too opaque since this will end up potentially user facing. Maybe we should change the error message to something like, "internal eigendecomposition run as part of qsd failed. This can point to a numerical tolerance issue...."

File: crates/synthesis/Cargo.toml [hunk 27]
```diff
@@ -27,7 +27,7 @@ num-traits.workspace = true
 rand.workspace = true
 rand_pcg.workspace = true
 rand_distr.workspace = true
-faer = "0.24"
+faer.workspace = true
```
Comment (mtreinish) [inline crates/synthesis/Cargo.toml:30]: We don't really need this change anymore but it doesn't hurt either, since we've agreed at this point we'll rely on faer for all the heavy linear algebra. So there is a fairly good chance we'll use it in another crate at some point.

**Review by mtreinish — COMMENTED** [review]
Thanks for all the updates and work on this. I just had one small comment inline about error messages. Right now I'm a bit worried they're a bit opaque for the internal tolerance checks or the decompositions fail. After updating that that I'm ready to approve I think.

File: crates/synthesis/src/qsd.rs (hunk 26 above)
Comment (alexanderivrii) [reply crates/synthesis/src/qsd.rs:66]: Improved error messages in [91f40b5](https://github.com/Qiskit/qiskit/pull/15874/commits/91f40b582351e8fb8f70a3c7fc3e315a9efad897).

**Review by mtreinish — APPROVED** [review]
I think this is good to merge now, thanks for all your hard work on this. I'm still a bit worried about the error message text not being descriptive enough for end users. But I don't have a concrete suggestion on how to improve it right now. So if we come up with something better we can update the error message text in the future.
