### PR TITLE
Use Arc instead of Box for internal expression nodes in SymbolExpr

### LINKED ISSUE #14653: Significant performance regression of transpilation in 2.1.0 compared to 2.0.2
### Environment

- **Qiskit version**: 2.1.0
- **Python version**: 3.12.11
- **Operating system**: macOS 15.5

### What is happening?

Transpilation in Qiskit 2.1.0 requires 9 times more time compared to version 2.0.2.

### How can we reproduce the issue?

```python
from timeit import timeit

from qiskit import __version__, generate_preset_pass_manager
from qiskit.circuit.library import zz_feature_map
from qiskit_ibm_runtime.fake_provider import FakeFez

print(f"qiskit_version={__version__}")
qubits = range(4, 30, 4)
circuits = [zz_feature_map(i, reps=4) for i in qubits]
backend = FakeFez()
pm = generate_preset_pass_manager(backend=backend, optimization_level=3)
print(f"{timeit(lambda: pm.run(circuits), number=1)} sec")
```

```
qiskit_version=2.1.0
34.34797391600023 sec
```

```
qiskit_version=2.0.3
3.7458205000002636 sec
```

### What should happen?

Transpiler should be as fast as Qiskit 2.0.2

### Any suggestions?

No idea.

Attach a frame graph just FYI

Image

### PR DESCRIPTION
**Pull request by mtreinish**
### Summary

This commit updates the internal construction of the SymbolExpr struct use a reference counting pointer instead of a regular pointer to a heap allocated object. The way the binary tree gets constructed internally using a normal pointer results in a lot of a copies of elements on the tree. This creates a large performance overhead for the symbol expr as we end up copying and freeing elements on the binary tree a large amount. This was the root cause of the regression reported in #14653 as the expression that gets generated by the transpiler internally ends up adding a lot of elements to global phase expression and that results in a lot of memory allocation and deallocation overhead. By using a reference counting pointer instead of creating and freeing copies of the expressions on the tree we instead only keep a single copy and just increment or decrement the reference count.

### Details and comments

Fixes #14653

### CODE REVIEW

**Comment by t-imamichi** [comment]
Thank you for making this fix. I tried it on my mac environment with [script](https://github.com/Qiskit/qiskit/issues/14653#issue-3166482657)

```
qiskit_version=2.0.3
2.4967326250043698 sec
```

```
qiskit_version=2.1.0
23.56942770799651 sec
```

```
qiskit_version=2.2.0.dev0+ea61602
5.4967313330053 sec
```

File: crates/circuit/src/symbol_expr.rs [hunk 1]
```diff
@@ -28,16 +29,16 @@ pub const SYMEXPR_EPSILON: f64 = f64::EPSILON * 8.0;
...
 pub enum SymbolExpr {
-    Symbol(Box<String>),
+    Symbol(Arc<String>),
     Value(Value),
     Unary {
         op: UnaryOp,
-        expr: Box<SymbolExpr>,
+        expr: Arc<SymbolExpr>,
     },
     Binary {
```
Comment (kevinhartman) [inline crates/circuit/src/symbol_expr.rs:38]: At least for `Expr`, I put expression variants with multiple inner `Expr`s within a single smart pointer, e.g. in this case:

```rust
struct Binary {
    op: BinaryOp,
    lhs: SymbolExpr,
    rhs: SymbolExpr,
}

pub enum SymbolExpr {
    Symbol(Box<String>),
    Symbol(Arc<String>),
    Value(Value),
    Unary {
        op: UnaryOp,
        expr: Arc<SymbolExpr>,
    },
    Binary(Arc<Binary>),
}
```

I think maybe @doichanj had this as well originally. Perhaps that could help reduce fan-out.

**Review by kevinhartman — COMMENTED** [review]
This looks good to me.

I've got one comment for a potential follow-up (hence approval without merge queue).

**Review by kevinhartman — APPROVED** [review]

File: crates/circuit/src/symbol_expr.rs (hunk 1 above)
Comment (mtreinish) [reply crates/circuit/src/symbol_expr.rs:38]: Yeah lets save this for a potential follow up PR. I was thinking this should be backported for a 2.1.1 and I would like to keep the diff minimal for the backport. I think adding a struct like you're proposing and using a single pointer like you're proposing is nice change.

**Comment by t-imamichi** [comment]
@doichanj made a follow-up PR #14548
