### PR TITLE
Handle huge integers in OpenQASM 2 expression evaluator

### LINKED ISSUE #11561: PanicException: called `Result::unwrap()` on an `Err` value: ParseIntError { kind: PosOverflow }
### Environment

- **Qiskit Terra version**: qiskit 0.44.1
- **Python version**: 3.9
- **Operating system**: linux

### What is happening?

I'm simply trying to generate a QuantumCircuit object from different QASM files. Why can some files be generated successfully while others result in an error?

### How can we reproduce the issue?

'''from qiskit import QuantumCircuit
qc = QuantumCircuit.from_qasm_file("ae_indep_qiskit_69.qasm")'''

### What should happen?

generate a QuantumCircuit object

### Any suggestions?

_No response_

### PR DESCRIPTION
**Pull request by jakelishman**
### Summary

This modifies the expression evaluator to directly parse the backing string data of an integer token in a floating-point context, which lets us handle numbers that would otherwise overflow a `usize`.  It's possible for this to be totally valid, if, for example, the integer is a multiple of some very large power of two that doesn't overflow a double-precision float.

We already needed to immediately cast the integer to a float, so this is just a more accurate way of doing the evaluation, and doesn't affect when we use integers in other contexts.

### Details and comments

Fix #11561

### CODE REVIEW

File: crates/qasm2/src/lex.rs [hunk 1]
```diff
@@ -264,7 +264,7 @@ impl Token {
     /// If the token is a real number, this method can be called to evaluate its value.  Panics if
     /// the token is not a real number.
```
Comment (kevinhartman) [inline crates/qasm2/src/lex.rs]: Comment needs an update 😄.

File: crates/qasm2/src/expr.rs [hunk 2]
```diff
@@ -502,7 +502,13 @@ impl<'a> ExprParser<'a> {
...
             | TokenType::Tan => Ok(Some(Atom::Function(token.ttype.into()))),
             TokenType::Real => Ok(Some(Atom::Const(token.real(self.context)))),
-            TokenType::Integer => Ok(Some(Atom::Const(token.int(self.context) as f64))),
+            // This deliberately parses an _integer_ token as a float, since all OpenQASM 2.0
+            // integers can be interpreted as floats, and doing that allows us to gracefully handle
+            // cases where a huge float would overflow a `usize`.  Never mind that in such a case,
+            // there's almost certainly precision loss from the floating-point representating
+            // having insufficient mantissa digits to faithfully represent the angle mod 2pi;
+            // that's not our fault in the parser.
+            TokenType::Integer => Ok(Some(Atom::Const(token.real(self.context)))),
```
Comment (kevinhartman) [inline crates/qasm2/src/expr.rs]: Nitpicking, but would it be better to use a single case for `Real | Integer` so it's more immediately obvious to the reader that these are handled in exactly the same way?

The comment ought to stay, though 🙂.

File: crates/qasm2/src/lex.rs (hunk 1 above)
Comment (jakelishman) [reply crates/qasm2/src/lex.rs]: Thanks - I have a bad habit of forgetting to unfold documentation comments in my editor.  Really I should have called the token `Float`, but I think I was just following the OQ2 paper's names.  Fixed in 9f4fbf1c67.

(tbf, an integer is a kind of real number!)

File: crates/qasm2/src/expr.rs (hunk 2 above)
Comment (jakelishman) [reply crates/qasm2/src/expr.rs]: Good call, done in 9f4fbf1c67.

**Review by kevinhartman — APPROVED** [review]
LGTM, thanks for the changes!

**Comment by jakelishman** [comment]
@Mergifyio backport stable/0.46
