### PR TITLE
QPY Rust and Python compatibility fixes

### LINKED ISSUE #15856: QPY dumper in 2.4 does not handle conditions with registers
### Environment

- **Qiskit version**:  `2.4.0rc1`
- **Python version**: 3.11.8
- **Operating system**: MacOS

### What is happening?

Internal testing by @emilkovacev revealed a regression in 2.4 (relative to 2.3) when serializing dynamic circuits with conditions.

### How can we reproduce the issue?

```python
from qiskit import ClassicalRegister, QuantumCircuit, QuantumRegister
from qiskit.qpy import dump

n_qubits = 2
cr0 = ClassicalRegister(n_qubits)
cr1 = ClassicalRegister(n_qubits)
                                     
qr = QuantumRegister(n_qubits)
qc = QuantumCircuit(qr, cr0, cr1)
                                     
qc.x(qr)
qc.measure(qr, cr0)
with qc.if_test((cr0, 0)):
    qc.x(qr)
qc.measure(qr, cr1)

with open('control_flow._60_qubits.qpy', 'wb') as fd:
    dump(qc, fd)
```
```log
---------------------------------------------------------------------------
QpyError
line 18
     15 qc.measure(qr, cr1)
     17 with open('control_flow._60_qubits.qpy', 'wb') as fd:
---> 18     dump(qc, fd)
QpyError: 'missing required data: Register condition value is missing'
```

### What should happen?

The same code works in 2.3

### Any suggestions?

_No response_

### PR DESCRIPTION
**Pull request by gadial**
### Summary
Fixes several incompatibilities between the Python and Rust file formats; in all cases, the Rust code was changed to conform to the Python expected standard

### Details and comments
This PR handles several problems detected with the Rust QPY component, most related to problems arising when an older, Python-based version of the QPY module attempts to read files generated with the Rust module. New tests were added to cover all these cases.

#### ParameterVector in qpy_reply
In Python, the data type of a `ParameterVector` inside the qpy_replay object is stored as Parameter (`b'p'`) and not ParameterVector (`b'v'`). Rust saved them with separate types, resulting in Python failing to load QPY files generated with Rust when the circuits contained parameter expressions involving ParameterVectors.

The fix makes Rust save the data type as `Parameter` as well. This should not cause problems, as parameters and parameter vectors are treated exactly the same when unpacking a parameter expression:

```
let lhs: Option<ParameterValueType> = match op.lhs_type {
                ParameterType::Parameter | ParameterType::ParameterVector => {
                    if let Some(value) = param_uuid_map.get(&op.lhs) {
                        Some(parameter_value_type_from_generic_value(value)?)
                    } else {
```

Note that writing `b'v' here breaks the QPY17 format, meaning that version 2.4.0rc1 does not fully conform to QPY17.

#### BoxOp duration parameter
In Rust, the `BoxOp` duration parameter was stored as `GenericData` which is either duration or expression. This should be the implementation going forward to QPY18 and beyond, but in Python support for duration in instruction parameters was nonexistant, so a hack was used instead, where `BoxOp` had two parameters, one for the numerical value and the other for the **string** of the duration's units - as well as "expr" when storing an expression. The current Rust code now conforms to this hack.

#### Control flow names
Previously, Rust stored the "new style" control flow names, e.g. `if_else`. This makes Python unable to correctly create those gates as it expects the actual class name. A conversion method from the new to the old style was added.

#### SwitchCaseOp handling
The way in which `SwitchCaseOp` parameters are stored in Python QPY is obsolete since the introduction of Rust based control flow ops. However, for now we still need to conform to the old method and the code was changed to reflect this. This allows us to dispose of the specialized treatment for this case in `unpack_py_instruction` since now we won't read switch instructions via this path.

Since the qpy write code of 2.4.0rc1 already used the new (now reverted) style that does not conform to QPY17 (although control flows are not defined in the spec), but we'll probably transition to it on QPY18, the read code now supports both approaches.

#### Additional bugfixes
As part of the new testing, another bug was discovered in the way condition register is handled - if its value is 0, the program would raise an error. This was fixed.

Another problem discovered was related to parameter vector name lookup in the old style using name-hashing (which was dumped in QPY15). For a parameter vector element e.g. `rz[0]` the name used was `rz` while the lookup tried to find `rz`. This was fixed and the correct name is now stored. However, I did not manage to reproduce the error even with the QPY which led to it being reported. The user that raised the issue confirmed this PR solved it for him.

### CODE REVIEW

File: crates/qpy/src/circuit_writer.rs [hunk 1]
```diff
@@ -163,9 +163,8 @@ fn pack_condition(
             let register_size = bytes.len() as u16;
             let data = formats::ConditionData::Register(bytes);
             // TODO: this may cause loss of data, but we are constrained by the current qpy format
```
Comment (Cryoris) [inline crates/qpy/src/circuit_writer.rs]: Is this comment still valid or is it resolved with the 0-default value?

File: crates/qpy/src/params.rs [hunk 2]
```diff
@@ -284,7 +284,7 @@ fn pack_parameter_replay_entry(
             (ParameterType::Parameter, *parameter.symbol.uuid.as_bytes())
         }
         ParameterValueType::VectorElement(element) => (
-            ParameterType::ParameterVector,
```
Comment (Cryoris) [inline crates/qpy/src/params.rs:287]: I'm a bit surprised the `ParameterVector` type is not needed for anything -- why did we introduce it then? 🤔 The one additional info that a parameter vector element has is the index, was it connected to that?

File: crates/qpy/src/circuit_writer.rs [hunk 3]
```diff
@@ -474,7 +505,7 @@ fn pack_control_flow_inst(
         extras_key: condition_key | annotations_key,
         num_ctrl_qubits: 0, // standard instructions have no control qubits
         ctrl_state: 0,
-        gate_class_name: control_flow_inst.name().to_string(), // this name is NOT a proper python class name, but we don't instantiate from the python class anymore
+        gate_class_name: control_flow_class_name(control_flow_inst.name())?, // need to use the Python class names for backward compatability
```
Comment (Cryoris) [inline crates/qpy/src/circuit_writer.rs]:
```suggestion
        gate_class_name: control_flow_class_name(control_flow_inst.name())?, // need to use the Python class names for backward compatibility
```

Comment (Cryoris) [inline crates/qpy/src/circuit_writer.rs]: Small nit: why not just pass the enum variant by reference directly? I would expect the enum match to be faster since we don't end up comparing string values 🤔

**Review by Cryoris — COMMENTED** [review]
I don't quite understand between which versions this PR fixes compatibility issues. Isn't V17 always loaded by Rust already?

**Comment by gadial** [comment]
> I don't quite understand between which versions this PR fixes compatibility issues. Isn't V17 always loaded by Rust already?

The problem is when writing V17 via Rust then reading it via Python. This path wasn't tested enough, as opposed to the other direction (writing in Python, reading in Rust). The main problem is regarding how control flows are handled; in Rust the parameters were written differently and Python didn't know how to handle them. This breaks V17 and so must be fixed.

File: crates/qpy/src/circuit_writer.rs (hunk 1 above)
Comment (gadial) [reply crates/qpy/src/circuit_writer.rs]: No, it's unrelated. The potential loss of data is when the value is too large. We **do** have BigUint support in the module, it's simply that V17 doesn't use it at this point.

File: crates/qpy/src/params.rs (hunk 2 above)
Comment (gadial) [reply crates/qpy/src/params.rs:287]: It is needed in general, but in that specific point of the replay there's no real difference between it and Parameter.

File: crates/qpy/src/circuit_writer.rs (hunk 3 above)
Comment (gadial) [reply crates/qpy/src/circuit_writer.rs]: Good idea, done in https://github.com/Qiskit/qiskit/pull/15847/commits/61ed23660995add718c220ca392ff5f9189db17f

File: crates/qpy/src/circuit_writer.rs [hunk 4]
```diff
@@ -163,9 +164,8 @@ fn pack_condition(
             let register_size = bytes.len() as u16;
             let data = formats::ConditionData::Register(bytes);
             // TODO: this may cause loss of data, but we are constrained by the current qpy format
-            let low_digits = target_value.iter_u64_digits().next().ok_or_else(|| {
-                QpyError::MissingData("Register condition value is missing".to_string())
-            })? as i64;
+            // Handle zero case: iter_u64_digits() returns empty iterator for 0
+            let low_digits = target_value.iter_u64_digits().next().unwrap_or(0) as i64;
```
Comment (eliarbel) [inline crates/qpy/src/circuit_writer.rs:175]: In Python, if you use a condition value which is larger than the `q` specifier size (8 bytes), `struct.pack` raises an error. Here, we silently truncate the extra bits. Should we instead use `.to_i64().ok_or_else(...)` to exactly match the Python behavior?

File: crates/qpy/src/circuit_writer.rs [hunk 5]
```diff
@@ -216,6 +216,29 @@ fn pack_instruction_blocks(
...
 }
+
+/// extracts instruction blocks from an instruction into a vector of GenericValues
+fn extract_instruction_blocks(
+    inst: &PackedInstruction,
+    qpy_data: &mut QPYWriteData,
+) -> Result<Vec<GenericValue>, QpyError> {
+    let blocks = qpy_data
+        .circuit_data
+        .unpack_blocks_to_circuit_parameters(inst.params.as_deref())
```
Comment (eliarbel) [inline crates/qpy/src/circuit_writer.rs]: Performance related: currently we clone the block twice here: in `unpack_blocks_to_circuit_paramaters` and in the collection into `Vec<GenericValue>` below. I think that instead of using `unpack_blocks_to_circuit_parameters` you should be able to iterate through `PackedInstruction::params` and map the block ids to `CircuitData` refs using `CircuitData::blocks::get`, and then clone those.

File: crates/qpy/src/circuit_writer.rs [hunk 6]
```diff
@@ -374,6 +397,19 @@ fn pack_pauli_product_rotation(
...
+fn control_flow_class_name(control_flow: &ControlFlow) -> String {
+    match control_flow {
+        ControlFlow::Box { .. } => "BoxOp".to_string(),
+        ControlFlow::BreakLoop => "BreakLoopOp".to_string(),
+        ControlFlow::ContinueLoop => "ContinueLoopOp".to_string(),
+        ControlFlow::IfElse { .. } => "IfElseOp".to_string(),
+        ControlFlow::While { .. } => "WhileLoopOp".to_string(),
+        ControlFlow::ForLoop { .. } => "ForLoopOp".to_string(),
+        ControlFlow::Switch { .. } => "SwitchCaseOp".to_string(),
+    }
```
Comment (eliarbel) [inline crates/qpy/src/circuit_writer.rs]: Nitpick, but if you want to be consistent with the other name getters in the crate: 

```suggestion
    String::from(match control_flow {
        ControlFlow::Box { .. } => "BoxOp",
        ControlFlow::BreakLoop => "BreakLoopOp",
        ControlFlow::ContinueLoop => "ContinueLoopOp",
        ControlFlow::IfElse { .. } => "IfElseOp",
        ControlFlow::While { .. } => "WhileLoopOp",
        ControlFlow::ForLoop { .. } => "ForLoopOp",
        ControlFlow::Switch { .. } => "SwitchCaseOp",
    })
```

File: crates/qpy/src/circuit_writer.rs [hunk 7]
```diff
@@ -395,8 +431,37 @@ fn pack_control_flow_inst(
                 },
             };
             let mut params = Vec::new();
-            params.push(pack_generic_value(&duration_param, qpy_data)?);
+            // ideally, we'd do params.push(pack_generic_value(&duration_param, qpy_data)?);
+            // however, Python expects the BoxOp params to be handled differentely, so this is code for backwards compatibility:
```
Comment (eliarbel) [inline crates/qpy/src/circuit_writer.rs]:
```suggestion
            // however, Python expects the BoxOp params to be handled differently, so this is code for backwards compatibility:
```

File: crates/qpy/src/circuit_reader.rs [hunk 8]
```diff
@@ -187,8 +187,12 @@ fn recognize_instruction_type(
...
         || matches!(
             name,
-            // We don't handle old style SwitchCaseOp in rust yet
-            "IfElseOp" | "WhileLoopOp" | "ForLoopOp" | "BreakLoopOp" | "ContinueLoopOp"
+            "IfElseOp"
+                | "WhileLoopOp"
+                | "ForLoopOp"
+                | "BreakLoopOp"
+                | "ContinueLoopOp"
+                | "SwitchCaseOp"
```
Comment (eliarbel) [inline crates/qpy/src/circuit_reader.rs:195]: I may be missing something here, but don't we need `BoxOp` as well? And related to this, what is the difference between `unpack_control_flow` and `unpack_py_instruction` when it comes to handling control flow ops?

File: crates/qpy/src/circuit_writer.rs [hunk 9]
```diff
@@ -395,8 +431,37 @@ fn pack_control_flow_inst(
...
+                    // we follow the python default
+                    let duration_value_pack = pack_generic_value(&GenericValue::Null, qpy_data)?;
+                    let duration_unit_string = GenericValue::String("dt".to_string());
+                    params.push(duration_value_pack);
+                    params.push(pack_generic_value(&duration_unit_string, qpy_data)?);
+                }
+                _ => {
+                    return Err(QpyError::InvalidInstruction(
+                        "Box instruction with unknown duration data".to_string(),
+                    ));
```
Comment (eliarbel) [inline crates/qpy/src/circuit_writer.rs]: I don't think this should be a `QpyError`, since we're packing a valid in-memory control flow instruction.  You could probably merge this `match` block with the one on line 426.

File: crates/qpy/src/circuit_writer.rs [hunk 10]
```diff
@@ -395,8 +431,37 @@ fn pack_control_flow_inst(
...
             let mut params = Vec::new();
-            params.push(pack_generic_value(&duration_param, qpy_data)?);
+            // ideally, we'd do params.push(pack_generic_value(&duration_param, qpy_data)?);
+            // however, Python expects the BoxOp params to be handled differentely, so this is code for backwards compatibility:
             params.extend(pack_instruction_blocks(instruction, qpy_data)?);
+            match duration_param {
+                GenericValue::Duration(duration) => {
+                    let duration_value_pack = Python::attach(|py| {
+                        py_pack_param(&duration.py_value(py), qpy_data, Endian::Little)
+                    })?;
```
Comment (eliarbel) [inline crates/qpy/src/circuit_writer.rs]: Can we do this without Python? Or with Python but only for `dt`?

File: crates/qpy/src/circuit_writer.rs (hunk 4 above)
Comment (gadial) [reply crates/qpy/src/circuit_writer.rs:175]: I agree, we need to verify explicitly that the `BigUInt` is not too large. Done in https://github.com/Qiskit/qiskit/pull/15847/commits/bef5c55b985ad23134de90f528a6c3c6ee3e6a7c

File: crates/qpy/src/circuit_reader.rs (hunk 8 above)
Comment (gadial) [reply crates/qpy/src/circuit_reader.rs:195]: `unpack_control_flow` is Rust pure whereas `unpack_py_instruction` creates a python instruction by using a python constructor (which in turn, might be simply rust code accessed through a wrapper). We still use `unpack_py_instruction` to handle `BoxOp` instructions (this can be changed, but I think it's out of scope for this PR).

File: crates/qpy/src/circuit_writer.rs (hunk 5 above)
Comment (gadial) [reply crates/qpy/src/circuit_writer.rs]: Great catch. Using `PackedInstruction::blocks_view` for the first step simplifies this even further.

File: crates/qpy/src/circuit_writer.rs (hunk 10 above)
Comment (gadial) [reply crates/qpy/src/circuit_writer.rs]: I was trying to avoid explicitly matching the duration but there's no real reason for this. Fixed in https://github.com/Qiskit/qiskit/pull/15847/commits/e18c72a846da46c9832762be7cfab909ccffb5da

File: crates/qpy/src/circuit_writer.rs (hunk 9 above)
Comment (gadial) [reply crates/qpy/src/circuit_writer.rs]: Agreed, fixed in https://github.com/Qiskit/qiskit/pull/15847/commits/e18c72a846da46c9832762be7cfab909ccffb5da

File: crates/qpy/src/circuit_reader.rs [hunk 11]
```diff
@@ -597,24 +601,52 @@ fn unpack_control_flow(
...
-                .next()
-                .zip(iter.next())
-                .zip(iter.next())
-                .ok_or_else(|| {
-                    QpyError::MissingData(
-                        "Switch case instruction missing some of its parameters".to_string(),
-                    )
-                })?;
-            let target = match target_value {
+            let (target_value, case_label_list) = if instruction_values.len() < 3 {
```
Comment (eliarbel) [inline crates/qpy/src/circuit_reader.rs:604]: Don't we want here exactly 2 values (params)?

File: crates/qpy/src/circuit_reader.rs [hunk 12]
```diff
@@ -597,24 +601,52 @@ fn unpack_control_flow(
...
+                // we follow the python way of storing switch params
+                // the first param is the target, the next param is the cases specificer
```
Comment (eliarbel) [inline crates/qpy/src/circuit_reader.rs]:
```suggestion
                // the first param is the target, the next param is the cases specifier
```

File: crates/qpy/src/circuit_reader.rs [hunk 13]
```diff
@@ -597,24 +601,52 @@ fn unpack_control_flow(
...
+                        return Err(QpyError::InvalidInstruction(
+                            "bad parameters for switch statement".to_string(),
+                        ));
+                    };
+                    param_values.push(case_circuit.clone());
+                    case_label_list.push(case_labels.clone());
+                }
+                (target_value, case_label_list)
+            } else {
+                param_values = instruction_values.split_off(3);
```
Comment (eliarbel) [inline crates/qpy/src/circuit_reader.rs:634]: With the updated `pack_control_flow_inst`, can we get here?

File: crates/qpy/src/circuit_reader.rs (hunk 11 above)
Comment (gadial) [reply crates/qpy/src/circuit_reader.rs:604]: We do, and if we don't have them - there's an error being raised down the line.

File: crates/qpy/src/circuit_reader.rs (hunk 13 above)
Comment (gadial) [reply crates/qpy/src/circuit_reader.rs:634]: No, but this is the way to parse the faulty 2.4.0rc1 files (and pass backwards compatibility). In QPY18 this should be the way to write/read, in my opinion, since it's closer in spirit to how the data is stored, rust-side.

Comment (eliarbel) [reply crates/qpy/src/circuit_reader.rs:634]: Ok, yeah, I thought this is something for a future format. NP, we can keep this.

File: crates/qpy/src/circuit_reader.rs (hunk 11 above)
Comment (eliarbel) [reply crates/qpy/src/circuit_reader.rs:604]: The following pattern matching is also written as "at least 2 items in the slice". I think it would be better to spell this out explicitly. But any way, not worth blocking on this, we can handle later.

File: crates/qpy/src/value.rs [hunk 14]
```diff
@@ -355,6 +355,19 @@ impl GenericValue {
             _ => None,
         }
     }
+    // return the inner Vec when the GenericData is a Tuple
+    pub(crate) fn as_vec(&self) -> Option<&Vec<GenericValue>> {
```
Comment (Cryoris) [inline crates/qpy/src/value.rs]: Using `as_slice` and returning `Option<&[GenericValue]>` seems more Rust idiomatic here

File: crates/qpy/src/circuit_writer.rs [hunk 15]
```diff
@@ -162,10 +165,14 @@ fn pack_condition(
                 serialize_param_register_value(&ParamRegisterValue::Register(reg), qpy_data)?;
             let register_size = bytes.len() as u16;
             let data = formats::ConditionData::Register(bytes);
-            // TODO: this may cause loss of data, but we are constrained by the current qpy format
-            let low_digits = target_value.iter_u64_digits().next().ok_or_else(|| {
-                QpyError::MissingData("Register condition value is missing".to_string())
-            })? as i64;
+            if target_value > BigUint::from(i64::MAX as u64) {
```
Comment (Cryoris) [inline crates/qpy/src/circuit_writer.rs:168]: Not urgent, but do we have a test triggering this?

File: crates/qpy/src/circuit_writer.rs [hunk 16]
```diff
@@ -374,6 +394,19 @@ fn pack_pauli_product_rotation(
     })
 }
 
+/// Convert snake_case name (e.g., "if_else") to Python class names (e.g., "IfElseOp")
+/// for backwards compatibility with old QPY versions
```
Comment (Cryoris) [inline crates/qpy/src/circuit_writer.rs]:
```suggestion
/// Get Python class names (e.g., "IfElseOp") for a control flow op.
/// This is for backwards compatibility with old QPY versions, since the 
/// Rust name uses snake_case.
```

File: crates/qpy/src/circuit_writer.rs [hunk 17]
```diff
@@ -387,16 +420,40 @@ fn pack_control_flow_inst(
...
-                    BoxDuration::Duration(duration) => GenericValue::Duration(duration),
-                    BoxDuration::Expr(exp) => GenericValue::Expression(exp),
-                },
-            };
             let mut params = Vec::new();
-            params.push(pack_generic_value(&duration_param, qpy_data)?);
             params.extend(pack_instruction_blocks(instruction, qpy_data)?);
+            match duration {
+                None => {
+                    // we follow the python default
```
Comment (Cryoris) [inline crates/qpy/src/circuit_writer.rs:428]: I wonder how helpful all the "Python" comments will be in a few months/years when we come back to this. Especially because now we know we mean V17 but the Python format also changed. Could we maybe put the QPY version and say Python V17 or whichever is the right one? (not just here but there's a bunch of places)

File: crates/qpy/src/circuit_writer.rs [hunk 18]
```diff
@@ -437,29 +498,41 @@ fn pack_control_flow_inst(
...
+                                        })?)
+                                        .as_le())
+                                    }
+                                }
+                            })
+                            .collect::<Result<Vec<GenericValue>, _>>()?,
+                    ))
+                })
+                .collect::<Result<Vec<GenericValue>, _>>()?;
+            let cases = GenericValue::Tuple(
```
Comment (Cryoris) [inline crates/qpy/src/circuit_writer.rs:503]: We could just merge this into the `case_labels` generation and avoid collecting them explicitly, couldn't we?

File: crates/qpy/src/params.rs [hunk 19]
```diff
@@ -328,11 +327,7 @@ pub(crate) fn unpack_parameter_expression(
                     }
                     _ => load_value(symbol_pack.value_key, &symbol_pack.value_data, qpy_data)?,
                 };
-                (
-                    symbol_pack.symbol_data.uuid,
-                    value,
-                    symbol_pack.symbol_data.name.clone(),
-                )
+                (symbol_pack.symbol_data.uuid, value, symbol.repr(false))
```
Comment (Cryoris) [inline crates/qpy/src/params.rs:330]: This change to `symbol.repr(false)`, which will print the vector index too, is because of Python doing that, right?

**Review by Cryoris — COMMENTED** [review]
Some implementation comments, though this now mostly looks clear, thanks! I'll play with this now and try and break it 🙂

File: crates/qpy/src/circuit_writer.rs (hunk 15 above)
Comment (gadial) [reply crates/qpy/src/circuit_writer.rs:168]: No. I created one manually but didn't want to add it to the test suite since we don't have a standard across QPY versions how to deal with this situation (in Python it crashed ungracefully). I can add if we want to adopt the Rust error message.

File: crates/qpy/src/circuit_writer.rs (hunk 17 above)
Comment (gadial) [reply crates/qpy/src/circuit_writer.rs:428]: The "Python" part is relevant since it deals with the ad-hoc manner in which the python code itself operates when loading gates, not the QPY17 standard which is vague on this point. If one wants to understand what's going on here, they need to read the Python code (we have version history, it'll survive the coming purge of Python QPY from the codebase).

File: crates/qpy/src/params.rs (hunk 19 above)
Comment (gadial) [reply crates/qpy/src/params.rs:330]: Yes. The problem we had was with reading old QPY files which used this convention (also, it makes sense - without the index we can't distinguish by name different parameters belonging to the same vector).

File: crates/qpy/src/value.rs (hunk 14 above)
Comment (gadial) [reply crates/qpy/src/value.rs]: Still not fluent enough in Rust to naturally think of doing it... fixed in https://github.com/Qiskit/qiskit/pull/15847/commits/f4e4391791b6f2f87e4d090e49049a999525ceeb

File: crates/qpy/src/circuit_writer.rs (hunk 15 above)
Comment (gadial) [reply crates/qpy/src/circuit_writer.rs:168]: Couldn't even find a test for the 0 case (which explains why we failed on it, in retrospect...) so I added a test to cover both in https://github.com/Qiskit/qiskit/pull/15847/commits/f4e4391791b6f2f87e4d090e49049a999525ceeb

File: crates/qpy/src/circuit_writer.rs (hunk 18 above)
Comment (gadial) [reply crates/qpy/src/circuit_writer.rs:503]: Yes, that's a refactoring I didn't think through. Fixed in https://github.com/Qiskit/qiskit/pull/15847/commits/f4e4391791b6f2f87e4d090e49049a999525ceeb

File: crates/qpy/src/params.rs (hunk 2 above)
Comment (jakelishman) [reply crates/qpy/src/params.rs:287]: More specifically: this is a completely different part of the QPY spec to the bit that specifies `Parameter`, it just happens to use the same magic sigil (`p`).  There's no need to distinguish _what_ subclass of `Parameter` it is, because this part of the format doesn't store all the information about a `Parameter` anyway - it stores the UUID and the rebuilder has to retrieve the complete `Parameter` or `ParameterVector` from a running map of `UUID: Parameter` that it keeps.

File: crates/qpy/src/circuit_reader.rs [hunk 20]
```diff
@@ -597,24 +601,52 @@ fn unpack_control_flow(
...
-                    )
-                })?;
-            let target = match target_value {
+            let (target_value, case_label_list) = if instruction_values.len() < 3 {
+                // we follow the python way of storing switch params
+                // the first param is the target, the next param is the cases specifier
+                // the cases specifier is a list of pairs (tuples)
+                // the second element in each pair is the subcircuit for this case
+                // the first element is the list of the case labels, or a single case label
+                // or the special default case label
```
Comment (jakelishman) [inline crates/qpy/src/circuit_reader.rs:610]: > we follow the python way

For the Rust-space QPY dumper to maintain the same semantics as the Python one (i.e. to be cross-compatible), we must always treat anything special that the Python-space one did with parameters based on the instruction name as actually being part of the QPY spec and simply not written down.

We should also follow-up to write down all these special cases in the specification; you cannot load up a circuit from QPY that contains one of the special-cased objects without knowing what the intended semantics are.

File: crates/qpy/src/circuit_reader.rs (hunk 13 above)
Comment (jakelishman) [reply crates/qpy/src/circuit_reader.rs:634]: Let's take a follow-on action item to either insert a comment explaining that this path should only be taken by the to-be-yanked 2.4.0rc1, or to delete the code.

File: crates/qpy/src/circuit_writer.rs (hunk 17 above)
Comment (jakelishman) [reply crates/qpy/src/circuit_writer.rs:428]: Let's take an follow-on issue to move all these comments about "Python default" to being documented semantics of QPY in the specification.

File: crates/qpy/src/circuit_writer.rs [hunk 21]
```diff
@@ -424,10 +482,14 @@ fn pack_control_flow_inst(
...
-            label_spec,
-            cases,
+            target, label_spec, ..
         } => {
+            // we follow the python way of storing switch params
+            // the first param is the target, the next param is the cases specificer
+            // the cases specifier is a list of pairs (tuples)
+            // the second element in each pair is the subcircuit for this case
+            // the first element is the list of the case labels, or a single case label
+            // or the special default case label
```
Comment (jakelishman) [inline crates/qpy/src/circuit_writer.rs:492]: Another thing that should move to documentation of the specification.

**Review by jakelishman — APPROVED** [review]
I've left a few comments to follow up on, and the rest of this comment here is because I wanted to clarify some points in the main PR comment.

I believe this fixes all the current known issues against QPY.  I suspect there might be more lurking, but I think we've probably squashed the main ones now, and it's best to try and get out an rc2.

---


> ParameterVector in qpy_reply
> 
> In Python, the data type of a ParameterVector inside the qpy_replay object is stored as Parameter (b'p') and not ParameterVector (b'v'). Rust saved them with separate types, resulting in Python failing to load QPY files generated with Rust when the circuits contained parameter expressions involving ParameterVectors.

I just really want to stress that the fact that there is a key called `Parameter` with magic sigil `p` here in the ParameterExpression replay format _does not_ mean that it is in any way related to the same key called `Parameter` with magic sigil `p` used in a different place in the QPY format.  The naming is confusing, but in Rust terms: think of the available magic sigils in any given place in the spec as completely different `enum`s.

> In Rust, the BoxOp duration parameter was stored as GenericData which is either duration or expression. This should be the implementation going forward to QPY18 and beyond, but in Python support for duration in instruction parameters was nonexistant, so a hack was used instead, where BoxOp had two parameters, one for the numerical value and the other for the string of the duration's units - as well as "expr" when storing an expression. The current Rust code now conforms to this hack.

This isn't a hack (or at least, not any more than the rest of QPY loading anything other than a standard gate, barrier or measure is) - it's because there's an undocumented and implied behaviour needed to load QPY that for the "magic" built-in Qiskit objects, you construct them by doing `ClassType(*params)`.  Since `BoxOp` is constructed as `BoxOp(body, duration, unit, label, annotations)` where `duration, unit` uses the same `float | expr.Expr, str` thing as `Delay`, that's how you end up with the behaviour you observed.

Now the fact that QPY does not specify which objects have to be loaded as `MagicClassName(*params)` and which as `Instruction(name, num_qubits, num_clbits, params)` is part of why I say it's not a fully specified format.

> Previously, Rust stored the "new style" control flow names, e.g. if_else. This makes Python unable to correctly create those gates as it expects the actual class name.

This is the same problem as the last paragraph above: there are "magic" names that the QPY specification does not mention, but are critical for reloading the same semantics.

**Comment by jakelishman** [comment]
Oh also, I made the "round trip" tests more aggressive at testing _every_ combination of read/write between Rust and Python space in [84686c8](https://github.com/Qiskit/qiskit/pull/15847/commits/84686c8f1940eaaec53918d6e98b372a067a8fb6), which gave me a bit more faith in the suite.
