### PR TITLE
Expose both forms of VF2 layout passes in the C API

### LINKED ISSUE #14454: Add VF2PostLayout to the C API
### What should we add?

Right now portions of the pass are written in Rust, but most of the logic is still in Python. The porting to rust is being tracked here: https://github.com/Qiskit/qiskit/issues/12276 once the pass is written in rust we should add it as a standalone function to the C API as described in https://github.com/Qiskit/qiskit/issues/14245

### LINKED ISSUE #14866: EPIC: on-the-fly pruning in VF2
This is the tracking issue for the patch series that implements on-the-fly scoring/tree-pruning in `VF2Layout` and `VF2PostLayout`, including lowering the passes to be near-100% in Rust (aside from minor Python-space IO) and exposing the passes entirely to the C API.

I wrote this as a linear patch series, so each PR is effectively dependent on its predecessor.  The list, from "merge first" to "merge last" is:

- [x] #14235 
- [x] #14236 
- [x] #14856 
- [x] #14857 
- [x] #14858 
- [x] #14859 
- [x] #14860 
- [x] #14861 
- [x] #14862 
- [x] #14863 
- [ ] #14864 

In particular, the commit messages of #14856 and #14857 explain in some detail the modifications to the algorithm, some of the benefits, and a couple of cases where there might be drawbacks (though I think other modifications to the VF2 algorithm made in the patch series should largely mask regressions).

The rough overview is this: instead of using VF2 to find complete mappings _and then_ scoring them, we instead imbibe the algorithm with the ability to incrementally score a layout as we build it up.  That lets us avoid a lot of repeat scoring calculations in high-degeneracy situations (which I believe is a computational complexity improvement for certain score distributions), but it also lets us more eagerly prune the VF2 decision tree when the partial score shows that the search can longer produce a _better_ result, even if there are structurally valid results deeper in this particular branch.

### PR DESCRIPTION
**Pull request by jakelishman**
Spiritually, this is exposing `VF2PostLayout(strict_direction=True)` through the C API, since `VF2Layout` and `VF2PostLayout` both with `strict_direction=False` are indistinguishable from Rust- and C-space (they differ only in how the modify the `PropertySet`).  The actual mechanism is by exposing the same names in Rust space for the two behaviours to C space.

Closes #14454 
Close #14866

### CODE REVIEW

File: crates/cext/src/transpiler/passes/vf2.rs [hunk 1]
```diff
@@ -351,7 +377,90 @@ pub unsafe extern "C" fn qk_transpiler_pass_standalone_vf2_layout(
...
+///
+/// This function is suitable for use on circuits that have already been fully lowered to hardware,
+/// and you are now looking to see if a qubit permutation can lead to better estimated error rates.
+/// If your circuit is still in terms of non-hardware-supported operations, use
+/// ``qk_transpile_pass_standalone_vf2_layout_average`` instead.
+///
+/// If this pass finds a solution that means there is a "perfect layout" and that no
+/// further compilation is needed (aside from applying the layout). However, there is not always a
+/// possible solution, or a solution might exist but it is not found within the limits specified
+/// when the pass is called.
```
Comment (alexanderivrii) [inline crates/cext/src/transpiler/passes/vf2.rs]: I find this explanation a bit confusing for the `VF2PostLayout` pass, as it already starts with a solution. Moreover, this should probably mention the `NoImprovement` variant as a possible result.

File: test/c/test_vf2_layout.c [hunk 2]
```diff
@@ -69,9 +69,9 @@ static int test_vf2_layout_line(void) {
     QkVF2LayoutConfiguration *layout_config = qk_vf2_layout_configuration_new();
     qk_vf2_layout_configuration_set_call_limit(layout_config, 10000, 10000);
     QkVF2LayoutResult *layout_result =
-        qk_transpiler_pass_standalone_vf2_layout(qc, target, layout_config, false);
+        qk_transpiler_pass_standalone_vf2_layout_average(qc, target, layout_config, false);
```
Comment (alexanderivrii) [inline test/c/test_vf2_layout.c:72]: For consistency with the newly-added tests, would it make sense to rename this and the other existing test as `test_vf2_average_<...>`?

File: test/c/test_vf2_layout.c [hunk 3]
```diff
@@ -134,11 +135,284 @@ static int test_vf2_no_layout_found(void) {
     return result;
 }
 
+/**
+ * Test exact-match VF2 layout when no solution is possible because of available 1q operations.
+ */
```
Comment (alexanderivrii) [inline test/c/test_vf2_layout.c:140]: I very much like the added tests in terms of their coverage of the possible behaviors of the `qk_transpiler_pass_standalone_vf2_layout_exact` function. Though my previous understanding was that we do the main testing in Python/Rust, and have the C tests only make sure that we can the external "C" Rust code (+ process the result). Is this still the case?

**Review by alexanderivrii — COMMENTED** [review]
This looks great, modulo needing to merge #14863 first. Also please see the inline question on the intended functionality for python/rust and c testing.

File: crates/cext/src/transpiler/passes/vf2.rs (hunk 1 above)
Comment (jakelishman) [reply crates/cext/src/transpiler/passes/vf2.rs]: I've rewritten this in the force-push that sorted out the documentation and rebased it.

File: test/c/test_vf2_layout.c (hunk 2 above)
Comment (jakelishman) [reply test/c/test_vf2_layout.c:72]: Sure, done in 80ce20b15db3cb4106ae7e3985e56ec47c1168d6.

File: test/c/test_vf2_layout.c (hunk 3 above)
Comment (jakelishman) [reply test/c/test_vf2_layout.c:140]: Yeah, it's largely still the case that that's the minimum necessary from C.  That said, I don't think it's a huge problem to have decent C tests as well, if they're not horrible to read - it never really hurts to dogfood our own interfaces.

In this case, the expanded test cases are to ensure we have test coverage of all the methods on `QkVf2LayoutResult` as well - we need to ensure `has_improvement`, `has_match` etc all behave as expected in those cases.

**Comment by jakelishman** [comment]
Should be all rebased and ready for review now.  There might be a couple of references in the documentation to stuff that's in the split-off #15369, but the idea is that they both merge.

File: releasenotes/notes/vf2-updates-51c215bb041f2c0f.yaml [hunk 4]
```diff
@@ -0,0 +1,47 @@
...
+    "trials" only increments when a new layout is encountered that is better in error rate than a
+    previous one.  You should instead use ``call_limit`` as the deterministic runtime limiter; where
+    ``max_trials`` measures complete layouts encountered, ``call_limit`` measures partial-layout
+    extensions.
+deprecations_c:
+  - |
+    The function :c:func:`qk_transpiler_pass_standalone_vf2_layout` is deprecated, as callers should
+    now use :c:func:`qk_transpiler_pass_standalone_vf2_layout_average`.  The new function name is
+    more descriptive of the scoring heuristic, and the API allows encapsulated access to the whole
+    new
```
Comment (alexanderivrii) [inline releasenotes/notes/vf2-updates-51c215bb041f2c0f.yaml]: This sentence looks a bit unfinished.

**Review by alexanderivrii — COMMENTED** [review]
Looks good. Just one minor nitpick about the release note.

File: releasenotes/notes/vf2-updates-51c215bb041f2c0f.yaml (hunk 4 above)
Comment (jakelishman) [reply releasenotes/notes/vf2-updates-51c215bb041f2c0f.yaml]: Whoops thanks, fixed in a35410c7fd.

**Review by alexanderivrii — APPROVED** [review]
Thanks Jake for this amazing contribution to Qiskit, I am really happy to see the VF2 epic fully completed for 2.3.
