### PR TITLE
Fix non-determinism VF2Layout with only 1q gates

### LINKED ISSUE #14729: Transpile with seed_transpiler doesn't yield the same circuit
### Environment

- **Qiskit version**: 2.1.1
- **Python version**: 3.12.9
- **Operating system**: MacOS

### What is happening?

Transpiling with a pass manager created with `seed_transpiler` doesn't yield the same circuit after 2.1.

### How can we reproduce the issue?

```python
import numpy as np
from qiskit.circuit import ParameterVector, QuantumCircuit
from qiskit.providers.fake_provider import GenericBackendV2
from qiskit.transpiler import generate_preset_pass_manager

params = ParameterVector("θ", length=3)

circ = QuantumCircuit(3)
for i, par in enumerate(params):
    circ.rx(par, i)
circ.measure_all()

backend = GenericBackendV2(10, noise_info=True, seed=123)
isa_circs = []
for _ in range(10):
    pm = generate_preset_pass_manager(optimization_level=2, target=backend.target, seed_transpiler=123)
    isa_circs.append(pm.run(circ))  

assert all(x == isa_circs[0] for x in isa_circs)
```

This code works okey with 2.0.

With 2.1.* the pass manger layout is inconsistent.

```
global phase: π/2
         ┌─────────┐┌────┐┌──────────────┐┌────┐┌──────────┐ ░    ┌─┐   
q_1 -> 0 ┤ Rz(π/2) ├┤ √X ├┤ Rz(π + θ[1]) ├┤ √X ├┤ Rz(5π/2) ├─░────┤M├───
         ├─────────┤├────┤├──────────────┤├────┤├──────────┤ ░    └╥┘┌─┐
q_2 -> 3 ┤ Rz(π/2) ├┤ √X ├┤ Rz(π + θ[2]) ├┤ √X ├┤ Rz(5π/2) ├─░─────╫─┤M├
         ├─────────┤├────┤├──────────────┤├────┤├──────────┤ ░ ┌─┐ ║ └╥┘
q_0 -> 8 ┤ Rz(π/2) ├┤ √X ├┤ Rz(π + θ[0]) ├┤ √X ├┤ Rz(5π/2) ├─░─┤M├─╫──╫─
         └─────────┘└────┘└──────────────┘└────┘└──────────┘ ░ └╥┘ ║  ║ 
 meas: 3/═══════════════════════════════════════════════════════╩══╩══╩═
                                                                0  1  2 
global phase: π/2
         ┌─────────┐┌────┐┌──────────────┐┌────┐┌──────────┐ ░       ┌─┐
q_2 -> 0 ┤ Rz(π/2) ├┤ √X ├┤ Rz(π + θ[2]) ├┤ √X ├┤ Rz(5π/2) ├─░───────┤M├
         ├─────────┤├────┤├──────────────┤├────┤├──────────┤ ░    ┌─┐└╥┘
q_1 -> 3 ┤ Rz(π/2) ├┤ √X ├┤ Rz(π + θ[1]) ├┤ √X ├┤ Rz(5π/2) ├─░────┤M├─╫─
         ├─────────┤├────┤├──────────────┤├────┤├──────────┤ ░ ┌─┐└╥┘ ║ 
q_0 -> 8 ┤ Rz(π/2) ├┤ √X ├┤ Rz(π + θ[0]) ├┤ √X ├┤ Rz(5π/2) ├─░─┤M├─╫──╫─
         └─────────┘└────┘└──────────────┘└────┘└──────────┘ ░ └╥┘ ║  ║ 
 meas: 3/═══════════════════════════════════════════════════════╩══╩══╩═
                                                                0  1  2 
global phase: π/2
         ┌─────────┐┌────┐┌──────────────┐┌────┐┌──────────┐ ░    ┌─┐   
q_1 -> 0 ┤ Rz(π/2) ├┤ √X ├┤ Rz(π + θ[1]) ├┤ √X ├┤ Rz(5π/2) ├─░────┤M├───
         ├─────────┤├────┤├──────────────┤├────┤├──────────┤ ░    └╥┘┌─┐
q_2 -> 3 ┤ Rz(π/2) ├┤ √X ├┤ Rz(π + θ[2]) ├┤ √X ├┤ Rz(5π/2) ├─░─────╫─┤M├
         ├─────────┤├────┤├──────────────┤├────┤├──────────┤ ░ ┌─┐ ║ └╥┘
q_0 -> 8 ┤ Rz(π/2) ├┤ √X ├┤ Rz(π + θ[0]) ├┤ √X ├┤ Rz(5π/2) ├─░─┤M├─╫──╫─
         └─────────┘└────┘└──────────────┘└────┘└──────────┘ ░ └╥┘ ║  ║ 
 meas: 3/═══════════════════════════════════════════════════════╩══╩══╩═
                                                                0  1  2 
global phase: π/2
         ┌─────────┐┌────┐┌──────────────┐┌────┐┌──────────┐ ░    ┌─┐   
q_1 -> 0 ┤ Rz(π/2) ├┤ √X ├┤ Rz(π + θ[1]) ├┤ √X ├┤ Rz(5π/2) ├─░────┤M├───
         ├─────────┤├────┤├──────────────┤├────┤├──────────┤ ░    └╥┘┌─┐
q_2 -> 3 ┤ Rz(π/2) ├┤ √X ├┤ Rz(π + θ[2]) ├┤ √X ├┤ Rz(5π/2) ├─░─────╫─┤M├
         ├─────────┤├────┤├──────────────┤├────┤├──────────┤ ░ ┌─┐ ║ └╥┘
q_0 -> 8 ┤ Rz(π/2) ├┤ √X ├┤ Rz(π + θ[0]) ├┤ √X ├┤ Rz(5π/2) ├─░─┤M├─╫──╫─
         └─────────┘└────┘└──────────────┘└────┘└──────────┘ ░ └╥┘ ║  ║ 
 meas: 3/═══════════════════════════════════════════════════════╩══╩══╩═
                                                                0  1  2 
global phase: π/2
         ┌─────────┐┌────┐┌──────────────┐┌────┐┌──────────┐ ░       ┌─┐
q_2 -> 0 ┤ Rz(π/2) ├┤ √X ├┤ Rz(π + θ[2]) ├┤ √X ├┤ Rz(5π/2) ├─░───────┤M├
         ├─────────┤├────┤├──────────────┤├────┤├──────────┤ ░ ┌─┐   └╥┘
q_0 -> 3 ┤ Rz(π/2) ├┤ √X ├┤ Rz(π + θ[0]) ├┤ √X ├┤ Rz(5π/2) ├─░─┤M├────╫─
         ├─────────┤├────┤├──────────────┤├────┤├──────────┤ ░ └╥┘┌─┐ ║ 
q_1 -> 8 ┤ Rz(π/2) ├┤ √X ├┤ Rz(π + θ[1]) ├┤ √X ├┤ Rz(5π/2) ├─░──╫─┤M├─╫─
         └─────────┘└────┘└──────────────┘└────┘└──────────┘ ░  ║ └╥┘ ║ 
 meas: 3/═══════════════════════════════════════════════════════╩══╩══╩═
                                                                0  1  2 
global phase: π/2
         ┌─────────┐┌────┐┌──────────────┐┌────┐┌──────────┐ ░    ┌─┐   
q_1 -> 0 ┤ Rz(π/2) ├┤ √X ├┤ Rz(π + θ[1]) ├┤ √X ├┤ Rz(5π/2) ├─░────┤M├───
         ├─────────┤├────┤├──────────────┤├────┤├──────────┤ ░    └╥┘┌─┐
q_2 -> 3 ┤ Rz(π/2) ├┤ √X ├┤ Rz(π + θ[2]) ├┤ √X ├┤ Rz(5π/2) ├─░─────╫─┤M├
         ├─────────┤├────┤├──────────────┤├────┤├──────────┤ ░ ┌─┐ ║ └╥┘
q_0 -> 8 ┤ Rz(π/2) ├┤ √X ├┤ Rz(π + θ[0]) ├┤ √X ├┤ Rz(5π/2) ├─░─┤M├─╫──╫─
         └─────────┘└────┘└──────────────┘└────┘└──────────┘ ░ └╥┘ ║  ║ 
 meas: 3/═══════════════════════════════════════════════════════╩══╩══╩═
                                                                0  1  2 
global phase: π/2
         ┌─────────┐┌────┐┌──────────────┐┌────┐┌──────────┐ ░    ┌─┐   
q_1 -> 0 ┤ Rz(π/2) ├┤ √X ├┤ Rz(π + θ[1]) ├┤ √X ├┤ Rz(5π/2) ├─░────┤M├───
         ├─────────┤├────┤├──────────────┤├────┤├──────────┤ ░    └╥┘┌─┐
q_2 -> 3 ┤ Rz(π/2) ├┤ √X ├┤ Rz(π + θ[2]) ├┤ √X ├┤ Rz(5π/2) ├─░─────╫─┤M├
         ├─────────┤├────┤├──────────────┤├────┤├──────────┤ ░ ┌─┐ ║ └╥┘
q_0 -> 8 ┤ Rz(π/2) ├┤ √X ├┤ Rz(π + θ[0]) ├┤ √X ├┤ Rz(5π/2) ├─░─┤M├─╫──╫─
         └─────────┘└────┘└──────────────┘└────┘└──────────┘ ░ └╥┘ ║  ║ 
 meas: 3/═══════════════════════════════════════════════════════╩══╩══╩═
                                                                0  1  2 
global phase: π/2
         ┌─────────┐┌────┐┌──────────────┐┌────┐┌──────────┐ ░       ┌─┐
q_2 -> 0 ┤ Rz(π/2) ├┤ √X ├┤ Rz(π + θ[2]) ├┤ √X ├┤ Rz(5π/2) ├─░───────┤M├
         ├─────────┤├────┤├──────────────┤├────┤├──────────┤ ░ ┌─┐   └╥┘
q_0 -> 3 ┤ Rz(π/2) ├┤ √X ├┤ Rz(π + θ[0]) ├┤ √X ├┤ Rz(5π/2) ├─░─┤M├────╫─
         ├─────────┤├────┤├──────────────┤├────┤├──────────┤ ░ └╥┘┌─┐ ║ 
q_1 -> 8 ┤ Rz(π/2) ├┤ √X ├┤ Rz(π + θ[1]) ├┤ √X ├┤ Rz(5π/2) ├─░──╫─┤M├─╫─
         └─────────┘└────┘└──────────────┘└────┘└──────────┘ ░  ║ └╥┘ ║ 
 meas: 3/═══════════════════════════════════════════════════════╩══╩══╩═
                                                                0  1  2 
global phase: π/2
         ┌─────────┐┌────┐┌──────────────┐┌────┐┌──────────┐ ░ ┌─┐      
q_0 -> 0 ┤ Rz(π/2) ├┤ √X ├┤ Rz(π + θ[0]) ├┤ √X ├┤ Rz(5π/2) ├─░─┤M├──────
         ├─────────┤├────┤├──────────────┤├────┤├──────────┤ ░ └╥┘┌─┐   
q_1 -> 3 ┤ Rz(π/2) ├┤ √X ├┤ Rz(π + θ[1]) ├┤ √X ├┤ Rz(5π/2) ├─░──╫─┤M├───
         ├─────────┤├────┤├──────────────┤├────┤├──────────┤ ░  ║ └╥┘┌─┐
q_2 -> 8 ┤ Rz(π/2) ├┤ √X ├┤ Rz(π + θ[2]) ├┤ √X ├┤ Rz(5π/2) ├─░──╫──╫─┤M├
         └─────────┘└────┘└──────────────┘└────┘└──────────┘ ░  ║  ║ └╥┘
 meas: 3/═══════════════════════════════════════════════════════╩══╩══╩═
                                                                0  1  2 
global phase: π/2
         ┌─────────┐┌────┐┌──────────────┐┌────┐┌──────────┐ ░ ┌─┐      
q_0 -> 0 ┤ Rz(π/2) ├┤ √X ├┤ Rz(π + θ[0]) ├┤ √X ├┤ Rz(5π/2) ├─░─┤M├──────
         ├─────────┤├────┤├──────────────┤├────┤├──────────┤ ░ └╥┘┌─┐   
q_1 -> 3 ┤ Rz(π/2) ├┤ √X ├┤ Rz(π + θ[1]) ├┤ √X ├┤ Rz(5π/2) ├─░──╫─┤M├───
         ├─────────┤├────┤├──────────────┤├────┤├──────────┤ ░  ║ └╥┘┌─┐
q_2 -> 8 ┤ Rz(π/2) ├┤ √X ├┤ Rz(π + θ[2]) ├┤ √X ├┤ Rz(5π/2) ├─░──╫──╫─┤M├
         └─────────┘└────┘└──────────────┘└────┘└──────────┘ ░  ║  ║ └╥┘
 meas: 3/═══════════════════════════════════════════════════════╩══╩══╩═
                                                                0  1  2 

```

### What should happen?

Transpile with a fixed seed should always generate the same layout. This is problematic at least for unittest of my codebase. Not sure if applications can be also affected by this.

### Any suggestions?

I don't have bandwidth to investigate.

(edit) 
After carefully looking into transpiled circuits, I realized that the circuit is always consistent at the level of physical qubit set. Since each wire in my circuit is logically equivalent, the behavior of transpiler is still reasonable. Maybe this is undocumented policy update?

### PR DESCRIPTION
**Pull request by mtreinish**
### Summary

This commit fixes an issue in the VF2Layout transpiler pass that would cause a non-deterministic output if the circuit had any qubit that only had single qubit operations. The dedicated internal function to deal with this special case sorts the qubits in the circuit by number of operations and the physical qubits on the target by error rate, to map the qubits with the lowest error rate. However this sorting wasn't fully stable as it was done on a hash set which doesn't have a stable iteration order. This commit fixes this by also sorting based on the qubit index so in the case of a tie the sort is stable.

### Details and comments

Fixes #14729

### CODE REVIEW

File: crates/transpiler/src/passes/vf2/vf2_layout.rs [hunk 1]
```diff
@@ -347,10 +347,14 @@ fn map_free_qubits(
             .get(&[PhysicalQubit::new(*qubit_b), PhysicalQubit::new(*qubit_b)])
             .unwrap_or(&0.);
         // Reverse comparison so lower error rates are at the end of the vec.
-        score_b.partial_cmp(&score_a).unwrap()
+        match score_b.partial_cmp(&score_a).unwrap() {
+            Ordering::Equal => qubit_b.cmp(qubit_a),
+            Ordering::Less => Ordering::Less,
+            Ordering::Greater => Ordering::Greater,
+        }
```
Comment (jakelishman) [inline crates/transpiler/src/passes/vf2/vf2_layout.rs:354]: No need to change what's written, but if you like: `Ordering` has a helper method for tuple-ish comparisons, which is `Ordering::then` (or `then_with`), so
```rust
score_b.partial_cmp(&score_a).expect("no scores are nan").then(qubit_b.cmp(qubit_a))
```
is possible too.

File: releasenotes/notes/fix-1q-non-determinism-vf2-75490119547bf656.yaml [hunk 2]
```diff
@@ -0,0 +1,8 @@
+---
+fixes:
+  - |
+    Fixed an issue in the :class:`.VF2Layout` transpiler pass where even with
+    a fixed seed set the output from the pass was potentially non-deterministic;
+    specifically if the input circuit had any active qubits that only contained
+    single qubit operations.
```
Comment (jakelishman) [inline releasenotes/notes/fix-1q-non-determinism-vf2-75490119547bf656.yaml:7]: Technically I suppose the condition was that you had at least two individually isolated qubits with the same number of operations on them.

**Review by jakelishman — APPROVED** [review]

File: releasenotes/notes/fix-1q-non-determinism-vf2-75490119547bf656.yaml (hunk 2 above)
Comment (mtreinish) [reply releasenotes/notes/fix-1q-non-determinism-vf2-75490119547bf656.yaml:7]: Or the average error rates for any two free qubits are the same. You could have a single isolated qubit that would get placed randomly between those tied error rates. Both of those details felt a bit too specific for trying to explain in a release note though.
