### PR TITLE
Fix incorrect mapping of ControlFlow block qargs in `BasisTranslator`

### LINKED ISSUE #13728: Transpiler pass does not update qubits registers within body of control flow operations
### Environment

- **Qiskit version**: 1.3.2
- **Python version**: 3.10
- **Operating system**: Mac OS Sequoia

### What is happening?

The issue arises due to the way Qiskit handles control flow structures like for_loop when applying transpilation passes. Specifically, the for_loop construct internally stores a new QuantumCircuit object that does not retain the physical qubit mapping intended for the calibrated custom gate (as defined in the backend target object).

When the transpilation pipeline reaches the HighLevelSynthesis pass, the method _definitely_skip_node should return True if the gate already has a valid calibration. However, it does not because the physical qubits referenced in the circuit structure do not align with those recorded in the initial_layout during pass execution.

### How can we reproduce the issue?

```python
from qiskit.circuit import QuantumCircuit, ParameterVector, Gate, Parameter
from qiskit import pulse, schedule, transpile
from qiskit.providers.fake_provider import GenericBackendV2
from qiskit.transpiler import InstructionProperties, generate_preset_pass_manager, CouplingMap

params = [Parameter(f'a_{i}') for i in range(2)]
qc = QuantumCircuit(2)
ecr_cal = Gate(name='ecr_cal', num_qubits=2, params=params)
qc_loop = QuantumCircuit(2)
qc.append(ecr_cal, [0, 1])
with qc_loop.for_loop([0, 3]) as i:
    qc_loop.compose(qc, inplace=True)

backend = GenericBackendV2(num_qubits=4,
                           basis_gates=["x", "sx", "ecr", "rz", "measure", "reset"],
                           coupling_map=CouplingMap.from_full(4),
                           calibrate_instructions=True,
                           control_flow=True)

with pulse.build(backend, name="custom_sched") as custom_sched:
    pulse.play(pulse.Constant(100, params[0]), pulse.DriveChannel(3))
    pulse.play(pulse.Constant(100, params[1]), pulse.DriveChannel(4))

backend.target.add_instruction(ecr_cal, properties={(3,4): InstructionProperties(calibration=custom_sched)})
pm = generate_preset_pass_manager(optimization_level=1,
                                  backend=backend,
                                  initial_layout=(3,4))

transpiled_circ = pm.run(qc_loop)
transpiled_circ.draw('mpl')`
```

### What should happen?

The transpilation process should correctly recognize that the ecr_cal gate, mapped to physical qubits (3,4), already has a calibration, and avoid unnecessary synthesis steps.
Instead of skipping synthesis, the transpiler does not identify the calibration, likely due to the for_loop internally storing logical qubit indices instead of physical qubits.

### Any suggestions?

A potential solution could involve ensuring that physical qubit mappings are correctly maintained within control flow constructs, or updating the handling of control flow operations within transpilation passes to correctly propagate the intended qubit mappings.

### PR DESCRIPTION
**Pull request by raynelfss**
### Summary
When extracting the basis of the target and applying the translations onto the dag, the `BasisTranslator` would not use the absolute indices of the operating qubits when a control flow operation block was processed during recursion. The following commit adds a mapping to the following `BasisTranslator` methods:
- `extract_target_basis_circuit` which only gets called during a recursion step.
- `apply_translation` in which it is always `None` unless a recursion step happens.

The provided mapping will correctly direct local block qubit indices into the absolute ones stored by the original circuit from which the operation comes from.

### Details and comments
This should help fix #13728.

### CODE REVIEW

File: crates/transpiler/src/passes/basis_translator/mod.rs [hunk 1]
```diff
@@ -455,7 +491,7 @@ fn apply_translation(
                         bound_obj.call_method1("replace_blocks", (flow_blocks,))?;
                     new_op = Some(replaced_blocks.extract()?);
                     Ok(())
-                }).map_err(|_| BasisTranslatorError::BasisCircuitError("Error replacing control flow operation blocks".to_string()))?;
+                }).map_err(|err| BasisTranslatorError::BasisCircuitError(err.to_string()))?;
```
Comment (Cryoris) [inline crates/transpiler/src/passes/basis_translator/mod.rs]: Isn't `err` here a `PyErr` so we can't call `to_string` on it? I thought that's why we had the hardcoded string in place here.

**Review by Cryoris — COMMENTED** [review]
Needs a reno and a test but otherwise LGTM, I verified that the backport fixes the issue. Thanks for looking into it so quickly!

File: crates/transpiler/src/passes/basis_translator/mod.rs (hunk 1 above)
Comment (raynelfss) [reply crates/transpiler/src/passes/basis_translator/mod.rs]: Oh yes, I had changed it to see the message within. I can change it back.

Comment (raynelfss) [reply crates/transpiler/src/passes/basis_translator/mod.rs]: Reverted in 5174f854bdc29556bd4b9364f2e4d3dd9fed86ac

**Review by Cryoris — APPROVED** [review]

**Comment by Cryoris** [comment]
We'll open a manual backport for `stable/1.4` since the files are in different locations and some functionality used here is was not yet available back then.
