### PR TITLE
Oxidize `synth_cnot_count_full_pmh`

### LINKED ISSUE #12106: The synthesis function ``synth_cnot_count_full_pmh`` returns invalid circuits for certain ``section_size`` values
### Environment

- **Qiskit version**: 1.0
- **Python version**: 3.10
- **Operating system**: Windows

### What is happening?

The following code
```
from qiskit.synthesis import synth_cnot_count_full_pmh
from qiskit.synthesis.linear import random_invertible_binary_matrix

mat = random_invertible_binary_matrix(5, seed=1234)
qc = synth_cnot_count_full_pmh(mat, section_size=6)
```
produces an empty circuit. 

### How can we reproduce the issue?

Run the code above.

### What should happen?

Setting `section_size` to a large number would probably produce suboptimal results, however it should still produce a valid (non-empty) circuit.

### Any suggestions?

I believe that something wrong is going on when ``section size`` is larger than the size of the matrix, for instance in the above example setting ``section_size`` to a number ``5`` or lower does work correctly.

### LINKED ISSUE #12227: Port `synth_cnot_count_full_pmh` to Rust

### PR DESCRIPTION
**Pull request by Cryoris**
### Summary

Closes #12227. 

In a benchmark to synthesize 100 qubit linear networks 1000 times, the runtime is ~44 times faster:
```
(main) Took 172.75505709648132s
(this PR) Took 3.920625925064087s
```
I would assume the main speedup is due to a more efficient circuit construction.

### Details and comments

* Does not address #12106, which is currently tackled in a different PR. 
* There certainly is some way to use iterators more by iterating over sections, but I couldn't yet wrap my head around it (and it might not give a significant speedup), suggestions are welcome 🙂

### CODE REVIEW

File: crates/accelerate/src/synthesis/cnot_synthesis.rs [hunk 1]
```diff
@@ -0,0 +1,163 @@
...
+/// This function uses the Patel-Markov-Hayes algorithm, described in arXiv:quant-ph/0302002,
+/// using section-wise elimination of the rows.
+#[pyfunction]
+#[pyo3(signature = (matrix, section_size=2))]
+pub fn synth_cnot_count_full_pmh(
+    py: Python,
+    matrix: PyReadonlyArray2<bool>,
+    section_size: i64,
+) -> PyResult<CircuitData> {
+    let mut mat: Array2<bool> = matrix.as_array().to_owned();
```
Comment (ShellyGarion) [inline crates/accelerate/src/synthesis/cnot_synthesis.rs]: perhaps you can use: 
`let mut mat: ArrayViewMut2<bool> = = matrix.as_array_mut()` and then you don't need to use `.to_owned()`

File: crates/accelerate/src/lib.rs [hunk 2]
```diff
@@ -29,6 +29,7 @@ pub mod sabre;
 pub mod sampled_exp_val;
 pub mod sparse_pauli_op;
 pub mod stochastic_swap;
+pub mod synthesis;
```
Comment (ShellyGarion) [inline crates/accelerate/src/lib.rs]: we should discuss the lib structure. in my PR #12456 I called the module `linear_matrix`, here it's `synthesis` and in #12601 it's `clifford`. we probably need some hierarchy here.

File: crates/accelerate/src/synthesis/cnot_synthesis.rs [hunk 3]
```diff
@@ -0,0 +1,163 @@
...
+            (
+                StandardGate::CXGate,
+                smallvec![],
+                smallvec![Qubit(ctrl as u32), Qubit(target as u32)],
+            )
+        });
+
+    Ok(
+        CircuitData::from_standard_gates(py, num_qubits as u32, instructions, Param::Float(0.0))
+            .expect("Something went sideways in Qiskit's Python realm!"),
```
Comment (ShellyGarion) [inline crates/accelerate/src/synthesis/cnot_synthesis.rs]: is it a standard Qiskit error?

File: crates/accelerate/src/synthesis/cnot_synthesis.rs [hunk 4]
```diff
@@ -0,0 +1,163 @@
...
+                    patterns.insert(pattern, row_idx);
+                }
+            }
+        }
+
+        // gaussian eliminate the remainder of the section
+        for col_idx in (section - 1) * section_size..section * section_size {
+            let mut diag_el = matrix[[col_idx, col_idx]];
+
+            for r in col_idx + 1..n {
```
Comment (ShellyGarion) [inline crates/accelerate/src/synthesis/cnot_synthesis.rs]: I think this can be done using iterators like in the usual gaussian elimination in #12456

File: crates/accelerate/src/synthesis/cnot_synthesis.rs [hunk 5]
```diff
@@ -0,0 +1,163 @@
...
+
+use qiskit_circuit::circuit_data::CircuitData;
+use qiskit_circuit::operations::{Param, StandardGate};
+use qiskit_circuit::Qubit;
+
+use pyo3::prelude::*;
+
+/// Mutate a matrix inplace by adding the value of the ``ctrl`` row to the
+/// ``target`` row. If ``add_columns`` is true, add columns instead of rows.
+fn _add(mat: &mut Array2<bool>, add_columns: &bool, ctrl: usize, trgt: usize) {
```
Comment (ShellyGarion) [inline crates/accelerate/src/synthesis/cnot_synthesis.rs]: is it the same function as `_row_op` and `_col_op` in #12456 ?
do we want to keep just one of these suggestions?

**Review by ShellyGarion — COMMENTED** [review]
Generally, it looks very well. Please see some comments and questions. 
Also, release notes are needed.

File: crates/accelerate/src/synthesis/cnot_synthesis.rs [hunk 6]
```diff
@@ -0,0 +1,163 @@
...
+/// using section-wise elimination of the rows.
+#[pyfunction]
+#[pyo3(signature = (matrix, section_size=2))]
+pub fn synth_cnot_count_full_pmh(
+    py: Python,
+    matrix: PyReadonlyArray2<bool>,
+    section_size: i64,
+) -> PyResult<CircuitData> {
+    let mut mat: Array2<bool> = matrix.as_array().to_owned();
+    // let mut mat = matrix.to_owned();
```
Comment (ShellyGarion) [inline crates/accelerate/src/synthesis/cnot_synthesis.rs]: this comment should be removed (also the one 3 lines later)

File: crates/accelerate/src/synthesis/cnot_synthesis.rs (hunk 5 above)
Comment (Cryoris) [reply crates/accelerate/src/synthesis/cnot_synthesis.rs]: Yes it's the same indeed! I don't mind in which PR we add it, maybe we could just keep which ever merges first and then update the other one? Or we can wait with this until #12456 merges 🙂

File: crates/accelerate/src/synthesis/cnot_synthesis.rs (hunk 3 above)
Comment (Cryoris) [reply crates/accelerate/src/synthesis/cnot_synthesis.rs]: Yeah, from what I understand this must be handled every time we use the `from_standard_gates`, see e.g. https://github.com/mtreinish/qiskit-core/commit/4edf3fbd3d6f763053d67cc6dadec83f5174228f#diff-61c072175672ef132e5e682a51401abd08288938d864b2090f4dc446e772837eR855-R868 🙂 (Also the compiler is complaining otherwise)

File: crates/accelerate/src/lib.rs (hunk 2 above)
Comment (Cryoris) [reply crates/accelerate/src/lib.rs]: Yes, let's sync offline 👍🏻

File: crates/accelerate/src/synthesis/cnot_synthesis.rs (hunk 1 above)
Comment (Cryoris) [reply crates/accelerate/src/synthesis/cnot_synthesis.rs]: The `to_owned` is currently necessary since the Python matrix remains unchanged -- so we copy it here to be able to modify it in Rust space 🙂

File: crates/accelerate/src/synthesis/cnot_synthesis.rs (hunk 5 above)
Comment (ShellyGarion) [reply crates/accelerate/src/synthesis/cnot_synthesis.rs]: in this case we should discuss the preferred API (let's talk offline) - 
do we prefer one function or two (for row and col)?
the name "_add" is too general. maybe "_add_row_or_col" ?

File: crates/accelerate/src/synthesis/cnot_synthesis.rs (hunk 4 above)
Comment (Cryoris) [reply crates/accelerate/src/synthesis/cnot_synthesis.rs]: I could get it more or less to work without the "backreduce" in the end of the iteration (L147 and following). But the backreduce accesses the pivot row repeatedly and Rust is complaining about multiple mutable borrows in the iterator... If you have any more ideas I'm happy to try more 🙂

File: crates/accelerate/src/synthesis/cnot_synthesis.rs [hunk 7]
```diff
@@ -0,0 +1,188 @@
...
+
+use qiskit_circuit::circuit_data::CircuitData;
+use qiskit_circuit::operations::{Param, StandardGate};
+use qiskit_circuit::Qubit;
+
+use pyo3::prelude::*;
+
+/// Mutate a matrix inplace by adding the value of the ``ctrl`` row to the
+/// ``target`` row. If ``add_cols`` is true, add columns instead of rows.
+fn _add_row_or_col(mat: &mut Array2<bool>, add_cols: &bool, ctrl: usize, trgt: usize) {
```
Comment (ShellyGarion) [inline crates/accelerate/src/synthesis/cnot_synthesis.rs]: I think it is better to have:
`fn _add_row_or_col(mut mat: ArrayViewMut2<bool>, add_cols: &bool, ctrl: usize, trgt: usize) {`
I added this function to linear matrix utils in #12456

Comment (Cryoris) [reply crates/accelerate/src/synthesis/cnot_synthesis.rs]: Done in 5684f62 🙂

File: crates/accelerate/src/synthesis/cnot_synthesis.rs [hunk 8]
```diff
@@ -0,0 +1,188 @@
...
+
+use qiskit_circuit::circuit_data::CircuitData;
+use qiskit_circuit::operations::{Param, StandardGate};
+use qiskit_circuit::Qubit;
+
+use pyo3::prelude::*;
+
+/// Mutate a matrix inplace by adding the value of the ``ctrl`` row to the
+/// ``target`` row. If ``add_cols`` is true, add columns instead of rows.
+fn _add_row_or_col(mut mat: ArrayViewMut2<bool>, add_cols: &bool, ctrl: usize, trgt: usize) {
```
Comment (ShellyGarion) [inline crates/accelerate/src/synthesis/cnot_synthesis.rs]: this function is now in synthesis/linear/utils.rs

File: crates/accelerate/src/synthesis/cnot_synthesis.rs [hunk 9]
```diff
@@ -0,0 +1,188 @@
...
+        (s![ctrl, ..], s![trgt, ..])
+    };
+    let (row0, mut row1) = mat.multi_slice_mut(info);
+
+    // add them inplace
+    row1.zip_mut_with(&row0, |x, &y| *x ^= y);
+}
+
+/// This helper function allows transposed access to a matrix.
+fn _index(transpose: &bool, i: &usize, j: &usize) -> (usize, usize) {
```
Comment (ShellyGarion) [inline crates/accelerate/src/synthesis/cnot_synthesis.rs]: if this is a helper function for linear matrices, I would suggest to add it to synthesis/linear/utils.rs

File: crates/accelerate/src/synthesis/cnot_synthesis.rs [hunk 10]
```diff
@@ -0,0 +1,188 @@
...
+#[pyo3(signature = (matrix, section_size=2))]
+pub fn synth_cnot_count_full_pmh(
+    py: Python,
+    matrix: PyReadonlyArray2<bool>,
+    section_size: i64,
+) -> PyResult<CircuitData> {
+    let arrayview = matrix.as_array();
+    let mut mat: Array2<bool> = arrayview.to_owned();
+    // let mat: ArrayViewMut2<bool> = matrix.as_array().to_owned().view_mut();
+    // let mut mat: ArrayViewMut2<bool> = matrix.as_array().to_owned().view_mut();
```
Comment (ShellyGarion) [inline crates/accelerate/src/synthesis/cnot_synthesis.rs]: these 2 commented lines should be removed

File: crates/accelerate/src/synthesis/cnot_synthesis.rs [hunk 11]
```diff
@@ -0,0 +1,188 @@
...
+    } else {
+        (*i, *j)
+    }
+}
+
+/// Synthesize a linear function, given by a boolean square matrix, into a circuit.
+/// This function uses the Patel-Markov-Hayes algorithm, described in arXiv:quant-ph/0302002,
+/// using section-wise elimination of the rows.
+#[pyfunction]
+#[pyo3(signature = (matrix, section_size=2))]
```
Comment (ShellyGarion) [inline crates/accelerate/src/synthesis/cnot_synthesis.rs]: I would suggest to set the default value of section_size to `None` and if it's not given then use `log(n)` instead, as it produces a lower number of CX gates, after the bugs mentioned in #12166 will be fixed (see the discussion in #12166).

**Review by ShellyGarion — CHANGES_REQUESTED** [review]
This code looks good, but it should be refactored as #12456 was merged.

My main comment is that perhaps we should consider incorporating the suggestion in 
https://github.com/Qiskit/qiskit/pull/12166#issuecomment-2198448523 to handle invalid values `section_size` as well as tests to verify the correctness of the valid circuit (see https://github.com/Qiskit/qiskit/pull/12166#issuecomment-2088040391).
Then, perhaps it would be better to have the default `section_size` as `log(n)` since it produces a circuit with smaller CX count.

File: qiskit/synthesis/linear/cnot_synth.py [hunk 12]
```diff
@@ -17,33 +17,34 @@
...
+            the state of the input circuit.
         section_size: The size of each section in the Patel–Markov–Hayes algorithm [1].
 
     Returns:
-        QuantumCircuit: a CX-only circuit implementing the linear transformation.
+        A CX-only circuit implementing the linear transformation.
 
     Raises:
-        QiskitError: when variable ``state`` isn't of type ``numpy.ndarray``
+        QiskitError: when variable ``state`` isn't of type ``numpy.ndarray``.
```
Comment (ShellyGarion) [inline qiskit/synthesis/linear/cnot_synth.py]: do we still raise this error?

File: crates/accelerate/src/synthesis/cnot_synthesis.rs (hunk 11 above)
Comment (ShellyGarion) [reply crates/accelerate/src/synthesis/cnot_synthesis.rs]: Actually I'm not sure that it's better, see https://github.com/Qiskit/qiskit/pull/12166#issuecomment-2198521174

File: crates/accelerate/src/synthesis/cnot_synthesis.rs (hunk 9 above)
Comment (Cryoris) [reply crates/accelerate/src/synthesis/cnot_synthesis.rs]: I don't think this is used anywhere else, so it might be cleaner to keep it private in this file -- if we find that we need it elsewhere I agree we should move it 🙂

File: qiskit/synthesis/linear/cnot_synth.py (hunk 12 above)
Comment (Cryoris) [reply qiskit/synthesis/linear/cnot_synth.py]: Yeah we still do, I didn't touch that check (just added proper sentence punctuation 😉) but looking at it I would prefer removing it as the type is given in the type hint so we assume it is correctly given.

File: releasenotes/notes/oxidize-pmh-ec74e4002510eaad.yaml [hunk 13]
```diff
@@ -0,0 +1,6 @@
+---
+upgrade_synthesis:
```
Comment (alexanderivrii) [inline releasenotes/notes/oxidize-pmh-ec74e4002510eaad.yaml]: We should mark this as `features_synthesis` not as `upgrade_synthesis`; I have just pushed a tiny PR #12715 that fixes it in other places.

File: crates/accelerate/src/synthesis/cnot_synthesis.rs (hunk 11 above)
Comment (Cryoris) [reply crates/accelerate/src/synthesis/cnot_synthesis.rs]: Done as discussed offline 🙂

File: qiskit/synthesis/linear/cnot_synth.py (hunk 12 above)
Comment (Cryoris) [reply qiskit/synthesis/linear/cnot_synth.py]: Now we don't anymore, I removed that check.

File: qiskit/synthesis/linear/cnot_synth.py [hunk 14]
```diff
@@ -17,126 +17,53 @@
...
            Quantum Information & Computation 8.3 (2008): 282-294.
            `arXiv:quant-ph/0302002 [quant-ph] <https://arxiv.org/abs/quant-ph/0302002>`_
     """
-    if not isinstance(state, (list, np.ndarray)):
-        raise QiskitError(
-            f"state should be of type list or numpy.ndarray, but was of the type {type(state)}"
+    normalized = np.asarray(state).astype(bool)
+    if section_size is not None and normalized.shape[1] < section_size:
+        raise ValueError(
+            f"The section_size ({section_size}) is cannot be larger than the number of columns "
```
Comment (ShellyGarion) [inline qiskit/synthesis/linear/cnot_synth.py]: either "cannot be larger" or "is larger" but not both

File: releasenotes/notes/oxidize-pmh-ec74e4002510eaad.yaml [hunk 15]
```diff
@@ -0,0 +1,6 @@
+---
+features_synthesis:
```
Comment (ShellyGarion) [inline releasenotes/notes/oxidize-pmh-ec74e4002510eaad.yaml:2]: I think that it's worth to add that it also fixes a bug for certain values of section_size #12106,
and also that the default value of section_size has been changed to allow a more efficient synthesis for larger number of qubits

File: test/python/synthesis/test_linear_synthesis.py [hunk 16]
```diff
@@ -139,6 +140,29 @@ def test_synth_lnn_kms(self, num_qubits):
...
+        qc = QuantumCircuit(n)
+        for i in range(n - 1):
+            qc.cx(i, i + 1)
+        expected = Operator(qc)
+
+        mat = LinearFunction(qc).linear
+        for section_size in range(1, n + 1):
+            synthesized = synth_cnot_count_full_pmh(mat, section_size=section_size)
+            with self.subTest(section_size=section_size):
+                self.assertEqual(expected, Operator(synthesized))
```
Comment (ShellyGarion) [inline test/python/synthesis/test_linear_synthesis.py]: instead of using `Operator`, you can use: `mat_synth = LinearFunction(qc).linear` and check that it's identical to the original `mat`. The matrix is `nxn` and not `(2^n)x(2^n)`, so you can also check larger values of `n`.

File: test/python/synthesis/test_linear_synthesis.py [hunk 17]
```diff
@@ -139,6 +140,29 @@ def test_synth_lnn_kms(self, num_qubits):
                 dist = abs(q0 - q1)
                 self.assertEqual(dist, 1)
 
+    def test_pmh_section_sizes(self):
```
Comment (ShellyGarion) [inline test/python/synthesis/test_linear_synthesis.py]: I would be happy if we can add some pseudo-random tests with various values of `section_size` as well as `None`, see e.g  this test:
https://github.com/Qiskit/qiskit/blob/2c3ddf1e6f81c497297b1d3531f20ea62b4cb620/test/python/synthesis/test_linear_synthesis.py#L118

**Review by ShellyGarion — COMMENTED** [review]
Thanks @Cryoris - this PR looks great, I have some small comments.

File: crates/accelerate/src/synthesis/linear/pmh.rs [hunk 18]
```diff
@@ -0,0 +1,195 @@
...
+use qiskit_circuit::operations::{Param, StandardGate};
+use qiskit_circuit::Qubit;
+
+use pyo3::prelude::*;
+
+use super::utils::_add_row_or_col;
+
+/// This helper function allows transposed access to a matrix.
+fn _index(transpose: &bool, i: &usize, j: &usize) -> (usize, usize) {
+    if *transpose {
```
Comment (alexanderivrii) [inline crates/accelerate/src/synthesis/linear/pmh.rs]: Is there a reason to use `&bool`, `&usize` instead of `bool`, `usize`? I don't think we get any memory saving by passing the arguments "by reference" rather than directly.

File: crates/accelerate/src/synthesis/linear/pmh.rs [hunk 19]
```diff
@@ -0,0 +1,195 @@
...
+        (*j, *i)
+    } else {
+        (*i, *j)
+    }
+}
+
+fn _ceil_fraction(numerator: &usize, denominator: &usize) -> usize {
+    let mut fraction = numerator / denominator;
```
Comment (alexanderivrii) [inline crates/accelerate/src/synthesis/linear/pmh.rs]: same question here about `&usize` vs `usize`

**Review by alexanderivrii — COMMENTED** [review]
The code looks amazing! I just had one tiny question about function arguments.

File: test/python/synthesis/test_linear_synthesis.py (hunk 16 above)
Comment (Cryoris) [reply test/python/synthesis/test_linear_synthesis.py]: I just checked the smallest value for which we saw failures 🙂 I'll increase a bit.

File: crates/accelerate/src/synthesis/linear/pmh.rs (hunk 18 above)
Comment (Cryoris) [reply crates/accelerate/src/synthesis/linear/pmh.rs]: Nope, just initial Rust hiccups 😉 I'll change to use by value (same for your comment below).

File: releasenotes/notes/oxidize-pmh-ec74e4002510eaad.yaml (hunk 15 above)
Comment (Cryoris) [reply releasenotes/notes/oxidize-pmh-ec74e4002510eaad.yaml:2]: Added 🙂

File: test/python/synthesis/test_linear_synthesis.py (hunk 17 above)
Comment (Cryoris) [reply test/python/synthesis/test_linear_synthesis.py]: Done!

**Review by ShellyGarion — APPROVED** [review]
LGTM! Thanks @Cryoris !
