### PR TITLE
Port cosine-sine decomposition to Rust.

### LINKED ISSUE #14157: Problems with `scipy`'s cosine-sine decomposition
### Problem

The problem is that scipy's cosine-sine decomposition may produce absolutely incorrect results. The word "absolutely" means that we may get errors that exceed `0.1`, i.e. these are not just small floating-point precision errors. 

This is not a new problem, we have already discussed it within PR #10313 (especially see @jakelishman's comments) and within some internal slack threads. And unfortunately the problems did not go away since the last time we discussed them, see the recent failing tests for #13688.

To be fair, whether we get an error or not seems to heavily depend on the platform and on the type of matrices under consideration. For instance, running the following script on my Mac (python 3.13).

```
import scipy
import numpy as np
from qiskit.circuit._utils import _compute_control_matrix
from qiskit.quantum_info.random import random_unitary

def check_csd(mat):
    dim = mat.shape[0] // 2
    u, cs, vdh = scipy.linalg.cossin(mat, p=dim, q=dim)
    computed_mat = u @ cs @ vdh
    return np.allclose(mat, computed_mat)

for num_controls in [1, 2, 3, 4, 5]:
    for num_targets in [2, 3]:
        num_problems = 0
        for seed in range(50):
            base_mat = random_unitary(2**num_targets, seed).data
            mat = _compute_control_matrix(base_mat, num_controls)
            if not check_csd(mat):
                # print(f"PROBLEM WITH {num_ctrl_qubits = }, {num_target = }, {seed = }")
                num_problems += 1
        print(f"TESTS WITH {num_controls = }, {num_targets = }: {num_problems = }")
```
shows that there are 10 problematic tests (out of 50) for `num_controls = 3` and `num_targets = 3` (in addition, this behavior is fully deterministic). On the other hand, @ShellyGarion runs the above on her Linux VM without any problems. Also note that the matrices considered above are not "general" but controlled smaller-qubit matrices, I don't hit any problems if I run the cosine-sine decomposition on random unitary matrices (as compared to their controlled versions). At some point, @ewinston and @ShellyGarion have conjectured that the problems occur *only* for block diagonal matrices, but even that is not completely true (I can produce special problematic non-block-diagonal matrices but I can't quantify what exactly is wrong with these).

Also note that one of failing tests in #13688 is for arm-based ubuntu, with the error being 
```raise LinAlgError("{} did not converge: {}".format(method_name, info))```

### Why this is relevant to Qiskit

We are using scipy's sine-cosine decomposition as part of our "Quantum Shannon decomposition", when constructing definitions for unitary matrices, see: https://github.com/Qiskit/qiskit/blob/99d0fa99cd81258946bf3973ac046a1442609eb6/qiskit/circuit/library/generalized_gates/unitary.py#L158-L163

In addition, #13688 aims to replace the definition of controlled unitaries from using ``Isometry`` to using ``QSD``: https://github.com/Qiskit/qiskit/blob/99d0fa99cd81258946bf3973ac046a1442609eb6/qiskit/circuit/library/generalized_gates/unitary.py#L186-L198
See #10313 for data on the reduction in two-qubit gate count we could achieve with this change.

### Suggested approach

After a discussion with @ShellyGarion, we are thinking of changing the QSD code for unitary synthesis as follows: each time that `scipy.linalg.cossin` is used, we verify the results by multiplying the matrices in the decomposition, and in case of a problem call the ``Isometry`` code instead. This is not ideal: since it both makes the code slower and provides inferior circuits when ``Isometry`` is used, but it's probably much better than silently returning an incorrect result.

Another interesting possibility is to note that if $$A = [[U_1, 0], [0, U_2]] * [[C, S], [-S, C]] * [[V_1, 0], [0, V_2]]$$ is a cosine-sine decomposition for $A$, and $D = [[D_1, 0], [0, D_2]]$ is any diagonal matrix, then $$AD = [[U_1, 0], [0, U_2]] * [[C, S], [-S, C]] * [[V_1 D_1, 0], [0, V_2 D_2]]$$ is a cosine-sine decomposition for $$AD$$ (we believe). In other words, if `scipy.linalg.cossin` fails for matrix `A`, we could apply it to $$AD$$ instead, and then reconstruct a decomposition for $$A$$ by multiplying $$V$$ by $$D^{-1}$$. A quick local experiment shows that we can consider several simple diagonal matrices (with even the same value on the diagonal) and at least one of these works in all of the problematic tests above. Summarizing, instead of calling `cossin` once, we can call it multiple times (with different diagonal matrices $$D$$), stopping when we get a good decomposition, and only falling back on ``Isometry`` when all of these fail. This is also not ideal: since it makes the code even more slower (though I don't expect this to happen too often) and because I don't understand what are good diagonal matrices $$D$$ to choose for ``cossin`` not to fail, but at least it would provide more efficient circuits in almost all the cases.

What do you think?

### PR DESCRIPTION
**Pull request by alexanderivrii**
### Summary

This PR ports the cosine-sine decomposition to Rust, based on [Tket's implementation](https://github.com/CQCL/tket/blob/a61bbac1c07487521acd8da463023f3c85c799e8/tket/src/Utils/CosSinDecomposition.cpp).

In particular, this seems to fully avoid problems for computing CSDs for controlled unitary matrices described in #14157. 

 
### Details and comments

Tket has a specialized implementation in their code using eigen for the same problem space we need in qiskit for the qsd. This commit attempts to port their implementation into Rust for qiskit so we can have a native decomposition in rust. To start this just calls the function via python. But this is just a short term step to validate the implementation is correct. The eventual goal is to just replace the python implemenation of qsd and never expose this function to Python. This is just an intermediate steps towards working for that.

**Acknowledgements**: Tket developers, obviously. Matthew did the heavy lifting of porting the code to Rust and I have finalized the implementation. Thanks to Gadi and Shelly for helping me understand some of the technical details behind Tket's implementation.

**Note**: experimentally, it seems that the diagonal matrix `s` obtained using the QR-decomposition already satisfies that its entries are real and positive. If we could prove that this is always true, we could further simplify the algorithm.

### CODE REVIEW

File: crates/accelerate/src/cos_sin_decomp.rs [hunk 1]
```diff
@@ -0,0 +1,215 @@
...
+    // errors, it is possible that some of the c-values are just a tiny bit larger than 1,
+    // so we correct for that.
+    let thetas: Vec<f64> = c.iter().map(|f| f.min(1.0).acos()).collect();
+
+    // Apply QR to u10_r0_dag.
+    // We have u10 r0* = l1 s, where l1 is unitary and S is upper-triangular.
+    // Equivalently, u10 = l1 s r0.
+    let r0_dag = r0.adjoint();
+    let u10_r0_dag = u10 * r0_dag;
+    let qr = u10_r0_dag.clone().qr();
```
Comment (mtreinish) [inline crates/accelerate/src/cos_sin_decomp.rs]: I don't think you need this `clone()` the `qr()` method shouldn't need ownership of `u10_r0_dag`:

```suggestion
    let qr = u10_r0_dag.qr();
```

File: crates/accelerate/src/cos_sin_decomp.rs [hunk 2]
```diff
@@ -0,0 +1,215 @@
...
+    while start < end {
+        mat.swap_rows(start, end);
+        start += 1;
+        end -= 1;
+    }
+}
+
+/// Reverses columns in-place.
+fn reverse_columns(mat: &mut DMatrix<Complex64>) {
+    // Row-wise reverse u
```
Comment (mtreinish) [inline crates/accelerate/src/cos_sin_decomp.rs]:
```suggestion
```

File: crates/accelerate/src/cos_sin_decomp.rs [hunk 3]
```diff
@@ -0,0 +1,215 @@
...
+    DMatrix<Complex64>,
+    DMatrix<Complex64>,
+    DMatrix<Complex64>,
+    DMatrix<Complex64>,
+    Vec<f64>,
+);
+
+/// Reverses rows in-place.
+fn reverse_rows(mat: &mut DMatrix<Complex64>) {
+    // Row-wise reverse u
```
Comment (mtreinish) [inline crates/accelerate/src/cos_sin_decomp.rs]:
```suggestion
```

**Review by mtreinish — COMMENTED** [review]
Thanks for taking my very rough and incomplete starting point and making into a working function. It'll be really good to have this so we can finally implement #12213 (and potentially enable us to fix #10313 too). I took a quick skim through the code besides fixing the issues I had in my original draft it looks like you made some nice improvements on top of my WIP commit. I just left some small inline comments about incorrect comments that aren't needed anymore and one `clone()` that looked unnecessary.

File: crates/accelerate/src/cos_sin_decomp.rs (hunk 1 above)
Comment (alexanderivrii) [reply crates/accelerate/src/cos_sin_decomp.rs]: Removed.

File: crates/accelerate/src/cos_sin_decomp.rs (hunk 2 above)
Comment (alexanderivrii) [reply crates/accelerate/src/cos_sin_decomp.rs]: Removed.

File: crates/accelerate/src/cos_sin_decomp.rs (hunk 3 above)
Comment (alexanderivrii) [reply crates/accelerate/src/cos_sin_decomp.rs]: Removed.

File: crates/accelerate/src/two_qubit_decompose.rs [hunk 4]
```diff
@@ -668,7 +668,7 @@ impl TwoQubitWeylDecomposition {
                 .for_each(|(index, x)| *x = d_inner[index]);
 
             let compare = p_inner.dot(&diag_d).dot(&p_inner.t());
-            found = abs_diff_eq!(compare.view(), m2, epsilon = 1.0e-13);
+            found = abs_diff_eq!(compare.view(), m2, epsilon = 1.0e-11);
```
Comment (mtreinish) [inline crates/accelerate/src/two_qubit_decompose.rs]: This seems problematic to me. I don't think we should be doing this as part of a PR that's writing a standalone matrix decomposition, if we wanted to do this to potential address #4159 we should do it as a standalone PR. But I'm also skeptical this is the correct change to make, while reducing the tolerance on the comparison here would make it less likely to encounter a problem here it also would likely reduce the precision of the decomposition. @levbishop spent a long time on the original numpy weyl decomposition implementation getting the tolerances working well, so we definitely should check with him about this.

Comment (alexanderivrii) [reply crates/accelerate/src/two_qubit_decompose.rs]: I agree, this was not a correct way to handle the problem. I have reverted the change, and will try to understand why the problem occurs.

Comment (mtreinish) [reply crates/accelerate/src/two_qubit_decompose.rs]: So looking at the failure here: https://github.com/Qiskit/qiskit/pull/14233/checks?check_run_id=41007938380 assuming I didn't make a copy and paste/reformatting issue the failure in the 2q decomposer is likely a bug in qsd or this cs decomposition because the matrix being passed to the weyl decomposition is not exactly unitary (but is probably close). 

```python
import numpy as np
from qiskit.quantum_info.operators.predicates import is_unitary_matrix

failure = np.asarray(
    [
        [
            0.2524222544922381 - 0.15157333635398731j,
            -0.6643580856706417 - 0.15450431446543827j,
            0.05376565886648649 - 0.11031291050780709j,
            -0.5260218409567121 - 0.39535631839965424j,
        ],
        [
            0.2138249251847322 + 0.6059664893028895j,
            0.3608017430616281 - 0.09426493411600007j,
            -0.19914542956470765 + 0.1447031674200242j,
            -0.6162854139145573 + 0.0872589218018706,
        ],
        [
            0.34517845166422456 + 0.3023836476431612j,
            -0.19998673026159178 + 0.5417208282878708j,
            0.23068958815909718 + 0.547120459130864j,
            0.240902611894682 - 0.21299593130616845j,
        ],
        [
            -0.2792659501545185 - 0.46023748172058415j,
            0.17967532362631564 - 0.17307109873436446j,
            -0.0898287259368199 + 0.7508093792947167j,
            -0.2333192505578404 - 0.14742240551519192j,
        ],
    ]
)
print(is_unitary_matrix(failure))
```

But also double check that I wrote out the matrix correctly, it's definitely possible I made a mistake converting the ndarray/num-complex debug output to python.

Edit: this reminds me of this old discussion: https://github.com/Qiskit/qiskit/issues/7120

Comment (alexanderivrii) [reply crates/accelerate/src/two_qubit_decompose.rs]: Thanks Matthew. Indeed, the discussion in #7120 seems to be highly relevant. I can reproduce the problem locally on my Mac laptop, and here is a slightly deeper dive into this. The ``cossin`` is called on the original 8 x 8 unitary matrix ``M``. Two things are happening. First,  the 4x4 matrices ``l0``, ``l1``, ``r0``, ``r1`` returned by the algorithm are close to being unitary but not exactly unitary. Second, the reconstructed decomposition ``M = U * CS * V^\dagger`` is only approximately true. The immediate failure is due to the first point: when ``TwoQubitWeylDecomposition`` is called on the relevant 4x4 almost unitary matrix the obtained decomposition is not within the required tolerance of ``1e-13``. 

More precisely, let 
```
identity = np.eye(n)
l0_error = np.max(np.abs(l0.T.conjugate() @ l0 - identity))
l1_error = np.max(np.abs(l1.T.conjugate() @ l1 - identity))
r0_error = np.max(np.abs(r0.T.conjugate() @ r0 - identity))
r1_error = np.max(np.abs(r1.T.conjugate() @ r1 - identity))
```
then we get
```
l0_error: 3.3306690738754696e-16
l1_error: 1.3322676295501878e-15
r0_error: 1.1102230246251565e-15
r1_error: 4.065858760782248e-12
```
so it's probably ``r1`` that is problematic. Furthermore, the quality of the full decomposition is ``8.506964445333981e-11``.

For the very first step of our implementation of ``cossin``, there is a way to specify the tolerance ``eps`` when calling the nalgebra's SVD decomposition (see https://docs.rs/nalgebra/latest/src/nalgebra/linalg/svd.rs.html#700-715), however I was not able to improve the final errors by decreasing ``eps``. Yet this step only determines ``l0`` and ``r0`` (and ``c0``) and at least ``l0`` and ``r0`` seem fine.

Comment (alexanderivrii) [reply crates/accelerate/src/two_qubit_decompose.rs]: Update. I have used the `closest_unitary` idea from #7120 to improve the "unitary-ness" of ``r1`` (the other 3 matrices should be fine), which makes ``r1`` closer to being unitary (within a very small tolerance) at the expense of potentially making the full CSD decomposition a tiny bit worse.

File: test/python/synthesis/test_cos_sin_decomp.py [hunk 5]
```diff
@@ -0,0 +1,74 @@
...
+
+    @combine(num_qubits=[1, 2, 3, 4], seed=list(range(100)))
+    def test_random_unitary(self, num_qubits, seed):
+        """Test CSD for random unitary matricies."""
+        mat = random_unitary(2**num_qubits, seed=seed).data
+        self.assertCossinDecompositionIsCorrect(mat)
+
+    @combine(num_controls=[1, 2, 3], num_targets=[1, 2, 3], seed=list(range(50)))
+    def test_controlled_test_random_unitary(self, num_controls, num_targets, seed):
+        """Test CSD for controlled random unitary matricies."""
```
Comment (ShellyGarion) [inline test/python/synthesis/test_cos_sin_decomp.py]: matricies --> matrices

File: test/python/synthesis/test_cos_sin_decomp.py [hunk 6]
```diff
@@ -0,0 +1,74 @@
...
+        # Note that scipy has numerical stability problems on cotrolled
```
Comment (ShellyGarion) [inline test/python/synthesis/test_cos_sin_decomp.py]: cotrolled --> controlled

File: test/python/synthesis/test_cos_sin_decomp.py [hunk 7]
```diff
@@ -0,0 +1,74 @@
...
+
+        np.testing.assert_allclose(
+            mat,
+            recomputed_mat,
+            atol=1e-7,
+        )
+
+    @combine(num_qubits=[1, 2, 3, 4], seed=list(range(100)))
+    def test_random_unitary(self, num_qubits, seed):
+        """Test CSD for random unitary matricies."""
```
Comment (ShellyGarion) [inline test/python/synthesis/test_cos_sin_decomp.py]: matricies --> matrices

**Review by ShellyGarion — COMMENTED** [review]
The code looks great! I very much liked the detailed mathematical explanations.
I have found minor misprints in the comments.
I would also appreciate if @gadial  can look at the rust code to see if there any any possible optimizations. BTW, is it faster than using the current scipy code?

I would also like to suggest to add tests for hermitian and diagonal matrices:
```

    @combine(num_qubits=[1, 2, 3, 4], seed=list(range(20)))
    def test_random_hermitian(self, num_qubits, seed):
        """Test CSD for random hermitian matrices."""
        umat = random_unitary(2**num_qubits, seed=seed).data
        dmat = np.diag(np.exp(1j * np.random.normal(size=2**num_qubits)))
        mat = umat.T.conjugate() @ dmat @ umat
        self.assertCossinDecompositionIsCorrect(mat)

    @combine(num_qubits=[1, 2, 3, 4], seed=list(range(20)))
    def test_random_diagonla(self, num_qubits, seed):
        """Test CSD for random diagonal matrices."""
        dmat = np.diag(np.exp(1j * np.random.normal(size=2**num_qubits)))
        self.assertCossinDecompositionIsCorrect(dmat)


```

File: test/python/synthesis/test_cos_sin_decomp.py (hunk 7 above)
Comment (alexanderivrii) [reply test/python/synthesis/test_cos_sin_decomp.py]: Fixed.

File: test/python/synthesis/test_cos_sin_decomp.py (hunk 6 above)
Comment (alexanderivrii) [reply test/python/synthesis/test_cos_sin_decomp.py]: Fixed.

File: test/python/synthesis/test_cos_sin_decomp.py (hunk 5 above)
Comment (alexanderivrii) [reply test/python/synthesis/test_cos_sin_decomp.py]: Fixed.

**Comment by alexanderivrii** [comment]
Thanks @ShellyGarion for the extra tests, and, haha, with all your attention to typos you have misspelled the word "diagonal" 🤣.

**Review by ShellyGarion — APPROVED** [review]
